performance: create concurrent calls for listing s3 buckets
jina-ai/now pull request #1009
Opened 2023-02-02 10:30 UTC by IyadhKhalfallah

benchmark:

- Current solution: 80s
- Solution in PR: 38s

---

- [ ] This PR references an open issue
- [ ] Added a test
- [ ] Updated the documentation
- [ ] Added a screenshot of a successful customer deployment

2023-02-02 10:44 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +    with ThreadPoolExecutor(max_workers=MAX_WORKERS_S3_THREADPOOL) as executor:
We can probably use the number of cpu cores as `max_workers`.

2023-02-02 10:45 UTC, joschkabraun commented
Great! The solution is faster than previously, but it's still lacking behind the potential improvement to below one second. I think, if we improve the speed, we should go the full way.

2023-02-02 10:55 UTC, IyadhKhalfallah commented
> Great! The solution is faster than previously, but it's still lacking behind the potential improvement to below one second. I think, if we improve the speed, we should go the full way.

@joschkabraun True, we still need to solve the problem of the prompt toolkit event loop. With that, we could potentially go lower. But, I don't think we can generalize achieving the goal of going below one second, because we can't generatlize the structure of the firsr-level folders (could be also second-level, ...). In the case studied and discussed before, they could achieve very high speed because they knew the structure of the folders already, and they created concurrent calls for them in that pattern. The solution I implemented uses `bucket.meta.client.list_objects(Bucket=bucket.name, Delimiter='/')` as a general way to get the first-level folders since we have no pattern to follow.
We should also note that regarding the `async` that we might add, I'm not sure that this is a problem we want to solve since we need the data for indexing right after the loading part, so we will wait for it to finish either way. 
To conclude, the only thing that I see can help is the `Threadpool`, but it's all about defining the right prefixes. What do you think?

2023-02-02 12:42 UTC, joschkabraun commented
> > Great! The solution is faster than previously, but it's still lacking behind the potential improvement to below one second. I think, if we improve the speed, we should go the full way.
> 
> @joschkabraun True, we still need to solve the problem of the prompt toolkit event loop. With that, we could potentially go lower. But, I don't think we can generalize achieving the goal of going below one second, because we can't generatlize the structure of the firsr-level folders (could be also second-level, ...). In the case studied and discussed before, they could achieve very high speed because they knew the structure of the folders already, and they created concurrent calls for them in that pattern. The solution I implemented uses `bucket.meta.client.list_objects(Bucket=bucket.name, Delimiter='/')` as a general way to get the first-level folders since we have no pattern to follow. We should also note that regarding the `async` that we might add, I'm not sure that this is a problem we want to solve since we need the data for indexing right after the loading part, so we will wait for it to finish either way. To conclude, the only thing that I see can help is the `Threadpool`, but it's all about defining the right prefixes. What do you think?

Okay. Given the uncertainty with `asyncio`. How about we test & measure this option in isolation to see if it's worth it to make it work? Worst case scenario we call it in a separate process and in that process we write it in a DocArray to disk and then read it again later.

2023-02-10 08:17 UTC, joschkabraun requested changes
Really great work & experiments! Left some documentation suggestions.

2023-02-10 08:17 UTC, joschkabraun commented on now/data_loading/data_loading.py
>  def _list_s3_file_paths(bucket, folder_prefix):
Can you add some documentation on:
- the overall idea of this approach (in the docs of this function)
- what the single functions do (in the docs of the respective functions, e.g. `get_level_order_prefixes`)
This will make it easier for others, who haven't heard about how you are solving this issue, to understand your solution.

2023-02-10 08:17 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +    def list_objects(prefix):
let's remove this function, it's a one-liner

2023-02-10 08:17 UTC, joschkabraun commented on now/data_loading/data_loading.py
>          sigmap=sigmap, text="Listing files from S3 bucket ...", color="green"
Do you mind also change the text output of this spinner to that we create the documents from S3 or so? And add a spinner above where we actually list the files.

2023-02-10 08:44 UTC, IyadhKhalfallah commented on now/data_loading/data_loading.py
> +    def list_objects(prefix):
@joschkabraun this function is actually used inside the executor submit, that's why it is declared that way. I'll investigate if I can directly inject it

2023-02-10 09:39 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +        :param max_levels: The maximum number of level we can get to
Do you mind also adding intuition why the default value of `max_levels` was chosen as is?

2023-02-10 09:59 UTC, joschkabraun approved these changes
LGTM! 🚀

2023-02-10 10:31 UTC, IyadhKhalfallah commented
> few questions to understand the scope/motivation of this PR:
> 
> so you're basically stepping into the next level until the number of folders is more than some predefined constant, right? how did you come up with this number?
> 
> also, why do we need to choose the level? shouldn't we expect something like this? data/ folder1 folder2 ... foldern in which case we could just pass each folder to the runners? (i.e. level1)

@jupyterjazz Actually, that number is a constant that we define based on past experiments for now. We can't tell which is the best number but, for now we made an approximation for 100. Although we plan to study this in a different ticket (#294). For the format of the data, we don't necessarily have that, and that's why we introduced this levels logic (Customer data for reference) which answers this question: Where to stop, in terms of levels in the file structure, when choosing the concurrent threads?

2023-02-10 12:25 UTC, jupyterjazz approved these changes
LGTM

2023-02-10 13:16 UTC, merged