fix: only install the released version of jina now
jina-ai/now pull request #1027
Opened 2023-02-06 12:22 UTC by makram93

This PR solves the following:
- Install only the released version of Jina NOW to deploy the example, because the pre-release version can sometimes be unstable.
- Set DNS value as a list
- Check for all index fields, earlier it was just checking the first index fields since we allowed only one index field
- ~~Set autoscaling to 1 based on this [slack discussion]~~(https://jinaai.slack.com/archives/C03434J5BND/p1675851878421409) 

---

- [ ] This PR references an open issue
- [ ] Added a test
- [ ] Updated the documentation
- [ ] Added a screenshot of a successful customer deployment

2023-02-07 08:33 UTC, florian-hoenicke requested changes

2023-02-07 08:33 UTC, florian-hoenicke commented on .github/workflows/force-deploy-examples.yml
> +          pip install jina-now -U
In that case you don't need to checkout the code base

2023-02-10 13:01 UTC, joschkabraun requested changes

2023-02-10 13:01 UTC, joschkabraun commented on now/app/search_app/app.py
> +                'autoscale': {'min': 1, 'max': 5, 'metric': 'concurrency', 'target': 1}
why this change of `min`?

2023-02-10 13:01 UTC, joschkabraun commented on now/app/search_app/app.py
> +                'autoscale': {'min': 1, 'max': 5, 'metric': 'concurrency', 'target': 1}
why this change of `min`?

2023-02-10 13:09 UTC, makram93 commented on now/app/search_app/app.py
> +                'autoscale': {'min': 1, 'max': 5, 'metric': 'concurrency', 'target': 1}
During indexing, pods are terminated and restarted very frequently. There is no grace period supported yet by the wolf team autoscaling executors. As a workaround, Zac suggested using the min value as 1.
The restarting of pods causes indexing issues with large datasets
`
batch 37, try 0 HTTP Balancer service in fail-fast
trailing_metadata=Metadata((('content-length', '0'), ('l5d-proxy-error', 'HTTP Balancer service in fail-fast'), ('l5d-proxy-connection', 'close'), ('date', 'Wed, 08 Feb 2023 10:16:49 GMT')))
trailing_metadata=Metadata((('content-length', '0'), ('l5d-proxy-error', 'HTTP Balancer service in fail-fast'), ('l5d-proxy-connection', 'close'), ('date', 'Wed, 08 Feb 2023 10:16:49 GMT'))) |Gateway: Communication error with deployment preprocessor at address(es) {'preprocessor.jnamespace-e77920d288.svc:80'}. Head or worker(s) may be down.
trailing_metadata=Metadata((('content-length', '0'), ('l5d-proxy-error', 'HTTP Balancer service in fail-fast'), ('l5d-proxy-connection', 'close'), ('date', 'Wed, 08 Feb 2023 10:16:49 GMT')))
`
I am not 100% sure if this fixes it, since  I still see it sometimes.

The other reason I had in my mind, which could be unrelated, is that the pods go down to 0 and when the request comes, it takes time to bring back up the pod and that is why the first call to the flow is always slow. By keeping it to 1, I hope that one pod is always active and therefore the flow would always be ready to serve the request.

Let me know what you think.

2023-02-10 14:49 UTC, joschkabraun commented on now/app/search_app/app.py
> +                'autoscale': {'min': 1, 'max': 5, 'metric': 'concurrency', 'target': 1}
> I am not 100% sure if this fixes it, since I still see it sometimes.

So, instead of increasing `min` shouldn't we then rather remove it entirely or just leave it as is?

> The other reason I had in my mind, which could be unrelated, is that the pods go down to 0 and when the request comes, it takes time to bring back up the pod and that is why the first call to the flow is always slow. By keeping it to 1, I hope that one pod is always active and therefore the flow would always be ready to serve the request.

Starting the pods takes 5-15 seconds, which I think is fine, right?

2023-02-10 16:35 UTC, makram93 commented on now/app/search_app/app.py
> +                'autoscale': {'min': 1, 'max': 5, 'metric': 'concurrency', 'target': 1}
Yes, this is fine and also acceptable. The only downside is with the cloud apps. Now we are hosting demo deployments and when any demo is selected, the API first calls `dry_run` on the flow to check if it is active. This takes up some time - 2~30s, which is a bit much for the UI since it feels stuck. But anyways, I will revert the code and change it back to 0

2023-02-10 23:16 UTC, florian-hoenicke commented on now/app/search_app/app.py
> +                'autoscale': {'min': 1, 'max': 5, 'metric': 'concurrency', 'target': 1}
I agree, 0 is best for cost saving. I see that it is tempting to have always 1 replica running but I think it is rather fixing a symptom. As far as I understand, the dry_run() is causing it. Can we also check if the flow is running without doing a dry_run? What about the client.flow_running or something like this?

2023-02-13 08:38 UTC, makram93 commented on now/app/search_app/app.py
> +                'autoscale': {'min': 1, 'max': 5, 'metric': 'concurrency', 'target': 1}
`client.is_flow_ready` also calls dry_run afaik. Anyways, I have reverted the min to 0.

2023-02-13 10:40 UTC, violenil approved these changes
LGTM!

2023-02-13 10:47 UTC, jupyterjazz commented on .github/workflows/force-deploy-examples.yml
> -          sudo apt update && sudo apt install ffmpeg
so we don't need ffmpeg anymore?

2023-02-13 10:47 UTC, jupyterjazz commented on scripts/deploy_examples.py
> +    deployment_type = deployment_type.lower()
isn't this the same?

2023-02-13 11:03 UTC, makram93 commented on .github/workflows/force-deploy-examples.yml
> -          sudo apt update && sudo apt install ffmpeg
We do not have a music dataset so it is not needed

2023-02-13 12:34 UTC, jupyterjazz commented on .github/workflows/force-deploy-examples.yml
> -          sudo apt update && sudo apt install ffmpeg
then we should remove it from `ci.yml` and `cd.yml` too

2023-02-13 12:36 UTC, jupyterjazz approved these changes
LGTM!

we should remove ffmpeg from ci/cd too I think

2023-02-13 12:56 UTC, merged