feat: script for preparing laion100m data
jina-ai/now pull request #1055
Opened 2023-02-09 15:13 UTC by jupyterjazz

---

- [ ] This PR references an open issue
- [ ] Added a test
- [ ] Updated the documentation
- [ ] Added a screenshot of a successful customer deployment

2023-02-09 16:42 UTC, Tanguyabel approved these changes

2023-02-10 07:38 UTC, joschkabraun reviewed
Small suggestion & a question. Otherwise, LGTM!

2023-02-10 07:38 UTC, joschkabraun commented on scripts/prepare_laion_data.py
> +        new_doc.chunks[0]._metadata = chunk_metadata
Out of curiosity because I never saw this before, what is in the `_metadata` of the chunks?

2023-02-10 07:38 UTC, joschkabraun commented on scripts/prepare_laion_data.py
> +    for i in range(400):
What about an async download of `(size of RAM) / (size of single docarrays)` at the same time?

2023-02-10 12:43 UTC, florian-hoenicke commented on scripts/prepare_laion_data.py
> +            docs = DocumentArray.pull(f'jem-fu/laion400m_part_{i}', show_progress=True)
@jupyterjazz what do you think?

2023-02-10 14:25 UTC, girishc13 commented
How and where are you planning to run this script? This is not a trivial size dataset and there will be intermittent network failures. I'm still struggling to run my own custom script that is similar to this script on jcloud and push the data to Elasticsearch using a custom executor and custom k8s deployment.

This script needs to be much more customizable to allow running a single part or batch sequences so that the parts that failed can be retried as a separate job execution. 

This script should ideally be run as multiple jobs processing a particular sequence of batches.

2023-02-17 13:44 UTC, joschkabraun requested changes

2023-02-17 13:44 UTC, joschkabraun commented on scripts/prepare_laion_data.py
> +        new_doc = Document(chunks=Document(uri=doc.uri))
Let's create the docarray without hacks.

- https://docs.docarray.org/fundamentals/dataclass/new-type/#create-a-new-type
- https://github.com/jina-ai/now/blob/main/now/data_loading/create_dataclass.py#L112
- https://github.com/jina-ai/now/blob/main/now/data_loading/create_dataclass.py#L146

2023-02-20 12:14 UTC, jupyterjazz commented on scripts/prepare_laion_data.py
> +        new_doc.chunks[0]._metadata = chunk_metadata
It had a dictionary with `<DocumentMetadata.IMAGE_TYPE: 'image_type'>`
don't think it's relevant but still kept it
anyways, we're not using this approach anymore

2023-02-21 12:58 UTC, joschkabraun approved these changes
Small improvement, otherwise LGTM!

2023-02-21 12:58 UTC, joschkabraun commented on scripts/prepare_laion_data.py
> +        return Document(uri=value)
For the returned document, let's also set its modality to `image` to make sure that this is all correctly setup.

2023-02-21 14:50 UTC, merged