feat: integrate billing
jina-ai/now pull request #1069
Opened 2023-02-13 13:57 UTC by azayz

---

- [ ] This PR references an open issue
- [ ] Added a test
- [ ] Updated the documentation
- [ ] Added a screenshot of a successful customer deployment

2023-02-15 08:47 UTC, joschkabraun commented on now/executor/gateway/now_gateway.py
> +        metadata = {m.key: m.value for m in metadata}
we don't authenticate via the metadata in grpc as inference API does

2023-02-15 08:47 UTC, joschkabraun commented on now/executor/gateway/now_gateway.py
> +def get_user_token(request: Request) -> str:
this function isn't used as as far as I can see

2023-02-15 08:47 UTC, joschkabraun commented on now/executor/abstract/auth/auth.py
> +def check_user(kwargs, level, user_emails, admin_emails, api_keys):
this can be moved to `now_gateway` as it will be only used in there from now

2023-02-15 08:51 UTC, joschkabraun commented on now/executor/gateway/now_gateway.py
> +                deployment_id=self._deployment_id,
we don't have `deployment_id` AFAIK

2023-02-21 09:25 UTC, joschkabraun requested changes
Strong work :rocket: Added some suggestions

2023-02-21 09:25 UTC, joschkabraun commented on now/executor/abstract/auth/auth.py
> +    if not isinstance(admin_emails, list) or not isinstance(user_emails, list):
when is this needed?

2023-02-21 09:25 UTC, joschkabraun commented on now/executor/gateway/now_gateway.py
> +        internal_product_id: str = 'free-plan',
I thought I read it was 'pro'

2023-02-21 09:25 UTC, joschkabraun commented on now/executor/gateway/now_gateway.py
> +    def _create_gateway(self, gateway_cls, app_port, protocol='http', **kwargs):
`port` sounds more accurate then `app_port`, what do you think?

2023-02-21 09:25 UTC, joschkabraun commented on now/executor/gateway/now_gateway.py
> +            raise Exception('No authorization header')
let's raise a `HTTPException`

2023-02-21 09:25 UTC, joschkabraun commented on now/executor/gateway/now_gateway.py
> +            raise Exception('User has reached quota limit, please upgrade subscription')
Let's see what kind of exception the other teams raise here; `Exception` seems very general

2023-02-21 09:25 UTC, joschkabraun commented on now/executor/gateway/now_gateway.py
> +        access_token = metadata.get("authorization", "")
we don't check the access of the user, do we?

2023-02-21 09:25 UTC, joschkabraun commented on now/executor/gateway/now_gateway.py
> +    remain_credits = 100
should we set it to 0?

2023-02-21 09:25 UTC, joschkabraun commented on tests/executor/autocomplete/test_integration.py
> +    user_input.admin_emails = []
we can also change the default values of `admin_emails` and `api_key`

2023-02-21 09:25 UTC, joschkabraun commented on now/executor/gateway/now_gateway.py
> +        if not metadata or 'authorization' not in metadata:
we should maybe document in this class that only allow jwt authentication and not api key authentication for GRPC

2023-02-21 16:15 UTC, florian-hoenicke commented on now/executor/gateway/base_payment_gateway.py
> +        if ssl_keyfile and 'ssl_keyfile' not in self.uvicorn_kwargs.keys():
Do we need this here?
ssl_keyfile

2023-02-21 17:33 UTC, florian-hoenicke commented on now/executor/gateway/base_payment_gateway.py
> +        if ssl_keyfile and 'ssl_keyfile' not in self.uvicorn_kwargs.keys():
okay, as discussed with joschka, this is fine. We don't touch this file.

2023-02-21 17:38 UTC, florian-hoenicke commented
Great work, getting this to run.
The following two things are left to do:
- [ ] charge base fee (every 5 min) - can also be done in a followup pr
- [ ] validate that reporting works

2023-02-21 17:46 UTC, florian-hoenicke requested changes

2023-02-21 17:46 UTC, florian-hoenicke commented on .github/actions/push-executor/action.yml
> +      run: pip install --pre jina
fixed version is needed to be deterministic

2023-02-21 17:46 UTC, florian-hoenicke commented on now/executor/gateway/fast_api.py
> +import uuid
We should have another subfolder for everything that is base gateway related.

2023-02-21 17:48 UTC, florian-hoenicke commented on now/executor/gateway/fast_api.py
> +import uuid
Then, it will be easier for us to delete all related components.

2023-02-22 04:07 UTC, ZiniuYu commented on now/executor/gateway/now_gateway.py
> +                    current_user['token'],
I suggest to use named params, and maybe other similar api calls

2023-02-22 04:10 UTC, ZiniuYu commented on now/executor/gateway/now_gateway.py
> +        m2m_token: str,
so there is no need to pass all of them

2023-02-22 08:20 UTC, azayz commented on now/executor/abstract/auth/auth.py
> +    if not isinstance(admin_emails, list) or not isinstance(user_emails, list):
we need to make sure that they're lists, in some case I encountered it wasn't a list I believe

2023-02-22 08:34 UTC, azayz commented on now/executor/gateway/now_gateway.py
> +        access_token = metadata.get("authorization", "")
we dont for grpc we could do it though we need some refactoring

2023-02-22 09:06 UTC, azayz commented on now/executor/gateway/now_gateway.py
> +        internal_product_id: str = 'free-plan',
I just talked with degi it's 'free-plan' or 'pro-plan'

2023-02-22 09:52 UTC, joschkabraun commented on now/executor/gateway/now_gateway.py
> +        access_token = metadata.get("authorization", "")
Okay.

2023-02-22 09:53 UTC, joschkabraun commented on now/executor/gateway/now_gateway.py
> +        access_token = metadata.get("authorization", "")
I put it in a follow-up ticket: https://github.com/jina-ai/now/issues/1099

2023-02-22 10:02 UTC, joschkabraun commented on now/executor/abstract/auth/auth.py
> +    if not isinstance(admin_emails, list) or not isinstance(user_emails, list):
Yes, but it's odd & hacky to fix an issue on the typing of `UserInput` in some function and not in the class itself.

2023-02-22 12:41 UTC, azayz commented on now/executor/abstract/auth/auth.py
> +    if not isinstance(admin_emails, list) or not isinstance(user_emails, list):
I agree, fixed

2023-02-22 12:52 UTC, azayz commented on now/executor/gateway/now_gateway.py
> +        if not metadata or 'authorization' not in metadata:
I changed it to allow both

2023-02-22 13:11 UTC, azayz commented on now/executor/gateway/now_gateway.py
> +            raise Exception('User has reached quota limit, please upgrade subscription')
They return JSON response with 403 but because the interceptor cannot return such a response I think we need to raise such error

2023-02-22 13:25 UTC, azayz commented on now/executor/gateway/now_gateway.py
> +                    current_user['token'],
applied

2023-02-22 13:43 UTC, joschkabraun commented on now/executor/abstract/auth/auth.py
> +    if not isinstance(admin_emails, list) or not isinstance(user_emails, list):
so we can remove the check?

2023-02-22 13:52 UTC, joschkabraun requested changes

2023-02-22 13:52 UTC, joschkabraun commented on now/executor/gateway/now_gateway.py
> +        print(f'User input: {self.user_input.__dict__}')
can remove print

2023-02-22 13:52 UTC, joschkabraun commented on now/executor/gateway/now_gateway.py
> ~        self.logger.info(f'Running command: {command}')
remove todo

2023-02-22 13:52 UTC, joschkabraun commented on now/executor/gateway/now_gateway.py
> +                logger=self.logger,
remove todo

2023-02-22 13:52 UTC, joschkabraun commented on tests/integration/local/conftest.py
> +            token=get_request_body(secured=True)[1]['jwt']['token'],
can we use `hubble.get_token()` here as well?

2023-02-22 13:55 UTC, joschkabraun requested changes

2023-02-22 13:55 UTC, joschkabraun commented on now/executor/gateway/now_gateway.py
> +        # todo: report usage to hubble
this todo

2023-02-22 13:55 UTC, joschkabraun commented on now/executor/gateway/now_gateway.py
> +                # todo: add authentication mechanism from now.executors.abstract.auth which is based
remove this todo

2023-02-22 15:46 UTC, joschkabraun approved these changes
Awesome work! 🚀

2023-03-03 08:31 UTC, azayz commented
<img width="928" alt="Screenshot 2023-03-03 at 09 30 18" src="https://user-images.githubusercontent.com/40893766/222670776-2891622d-ef07-4c4e-afe0-73cc1c98e852.png">

2023-03-03 14:56 UTC, joschkabraun requested changes
First round of reviews, nice work!

2023-03-03 14:56 UTC, joschkabraun commented on now/app/base/app.py
> +            'prefetch': PREFETCH_NR,
we dropped `prefetch` and use default

2023-03-03 14:56 UTC, joschkabraun commented on now/executor/abstract/auth/auth.py
> +        raise TypeError(
That's fixing a symptom not a problem. Why is that necessary?

2023-03-03 14:56 UTC, joschkabraun commented on now/executor/gateway/bff/app/v1/routers/helper.py
> +def get_jina_client(host: str, port: int) -> Client:
can remove function as it's always simply `Client(host=host, port=port)` in this file

2023-03-03 14:56 UTC, joschkabraun commented on now/executor/gateway/bff/app/v1/routers/info.py
> +        data.jwt['token'] = auth_token
that's redundant code to the one above, let's write a function for that

2023-03-03 15:04 UTC, joschkabraun requested changes
Another round

2023-03-03 15:04 UTC, joschkabraun commented on now/executor/gateway/now_gateway.py
> +            logger.error(f'Failed to get payment summary: {resp}')
so if `remain_credits` is not `None` the logger will throw an error?

2023-03-06 08:41 UTC, azayz commented on now/executor/gateway/bff/app/v1/routers/helper.py
> +def get_jina_client(host: str, port: int) -> Client:
I think we can't do that because in multiple tests we much this specific function

2023-03-06 09:41 UTC, joschkabraun commented on now/executor/gateway/bff/app/v1/routers/helper.py
> +def get_jina_client(host: str, port: int) -> Client:
In which ones? Because we didn't need it lately / the function didn't exist.

2023-03-06 10:08 UTC, azayz commented on now/executor/gateway/bff/app/v1/routers/helper.py
> +def get_jina_client(host: str, port: int) -> Client:
in bff contest

2023-03-24 08:23 UTC, makram93 commented
@florian-hoenicke @azayz Closing this PR since billing is already integrated into the main branch.

2023-03-24 08:23 UTC, closed without merging