refactor: create utils module
jina-ai/now pull request #1169
Opened 2023-03-06 15:55 UTC by IyadhKhalfallah

---

- [ ] This PR references an open issue
- [ ] Added a test
- [ ] Updated the documentation
- [ ] Added a screenshot of a successful customer deployment

2023-03-09 12:56 UTC, joschkabraun commented on now/utils/implementation/helpers.py
> +import signal
what does `implementation` refer to?

2023-03-09 13:00 UTC, joschkabraun commented on now/utils/flow/helpers.py
> +import yaml
Let's call it `jcloud` instead of `flow` as these utils are needed for `jcloud`

2023-03-09 13:11 UTC, IyadhKhalfallah commented on now/utils/flow/helpers.py
> +import yaml
Sure!

2023-03-09 15:12 UTC, violenil requested changes
Looks good! Nice refactoring.

2023-03-09 15:12 UTC, violenil commented on now/utils/common/helpers.py
> +def debug(msg: Any):
Is this function even used anywhere?

2023-03-09 15:12 UTC, violenil commented on now/utils/common/helpers.py
> +def print_headline():
Can this function not be moved to the dialog.py? It is not used anywhere else in the codebase.

2023-03-09 16:28 UTC, joschkabraun approved these changes
LGTM, nice refactoring!

2023-03-13 08:25 UTC, violenil approved these changes
🚀

2023-03-13 08:49 UTC, merged