test: add preprocessor tests
jina-ai/now pull request #1179
Opened 2023-03-09 16:31 UTC by azayz

---

- [ ] This PR references an open issue
- [ ] Added a test
- [ ] Updated the documentation
- [ ] Added a screenshot of a successful customer deployment

2023-03-10 12:54 UTC, joschkabraun requested changes
Nice tests you added!
Can you also add one test in which we instaniate a preprocessor and test the `preprocess` function across data sources (docarray, s3, maybe elastic)? Then we cover the main functionality of the preprocesor and we have 100% test coverage

2023-03-10 12:54 UTC, joschkabraun commented on tests/executor/preprocessor/test_unit.py
> +        assert doc.tags
let's assert the `tags` being not empty

2023-03-10 12:54 UTC, joschkabraun commented on tests/executor/preprocessor/test_unit.py
> +def test_move_uri():
let's separate the testing for the "positive" and the "negative" in two functions

2023-03-10 12:54 UTC, joschkabraun commented on tests/executor/preprocessor/test_unit.py
> +def test_convert_fn(tmpdir):
I think that's a point to finally change the nme of this function

2023-03-10 15:05 UTC, joschkabraun requested changes

2023-03-10 15:05 UTC, joschkabraun commented on tests/executor/preprocessor/test_unit.py
> +def test_move_uri():
maybe call it `test_move_uri_not_s3`

2023-03-10 15:05 UTC, joschkabraun commented on tests/executor/preprocessor/test_unit.py
> +    assert len(result[0].chunks) > 0 and len(result[0].chunks[0].chunks) >= 0
let's check the entire dataset + the last check should be strict, shouldn't it be (otherwise something went wrong in the preprocessing)?

2023-03-10 15:07 UTC, joschkabraun commented
Looking at test coverage, do know why `maybe_download_from_s3` isn't hit in the preprocessor?

2023-03-10 15:53 UTC, violenil approved these changes
Looks good! I just have some questions for my own understanding.

2023-03-10 15:53 UTC, violenil commented on now/executor/preprocessor/executor.py
> +def move_uri(d: Document) -> Document:
Why does this function need to be moved outside of the executor?

2023-03-10 15:53 UTC, violenil commented on now/now_dataclasses.py
> -    dataset_url: Optional[str] = None
Do we not need this for S3?

2023-03-10 16:15 UTC, azayz commented on now/now_dataclasses.py
> -    dataset_url: Optional[str] = None
we don't need it at all that's why I deleted it

2023-03-10 16:15 UTC, azayz commented on now/executor/preprocessor/executor.py
> +def move_uri(d: Document) -> Document:
to be able to make the import previously it was inside the method

2023-03-13 08:43 UTC, jupyterjazz reviewed
Great PR!

can you also modify `test_text` in the unit tests to work for several index fields (including image fields)? currently it only considers one text field

2023-03-13 08:56 UTC, jupyterjazz commented
Also, `download_mock` isn't used anymore so we can remove it

2023-03-13 09:09 UTC, jupyterjazz commented
It is but not the case when docs have more than one index field. 
Also, I think we should move the file/tests to the preprocessor directory in the unit tests

2023-03-13 09:22 UTC, jupyterjazz approved these changes
LGTM!

2023-03-13 09:56 UTC, joschkabraun approved these changes
LGTM

2023-03-13 09:56 UTC, merged