feat: allow multiple filters to be passed in search request
jina-ai/now pull request #1180
Opened 2023-03-09 20:18 UTC by violenil

---

- [ ] This PR references an open issue
- [ ] Added a test
- [ ] Updated the documentation
- [ ] Added a screenshot of a successful customer deployment

2023-03-10 14:59 UTC, joschkabraun requested changes
Nice feature! Some small comments

2023-03-10 14:59 UTC, joschkabraun commented on now/executor/gateway/bff/app/v1/models/search.py
> +        example={'tags__color': ['blue'], 'tags__price': {'lt': 50.0}},
maybe we should change the examples to not include leading `tags__` due to the change in this PR

2023-03-10 14:59 UTC, joschkabraun commented on now/executor/gateway/bff/app/v1/routers/search.py
> +                'tags__price': {'lte': 100, 'gte': 50},
maybe we should change the examples to not include leading `tags__` due to the change in this PR

2023-03-10 14:59 UTC, joschkabraun commented on now/executor/gateway/playground/playground.py
> +def apply_filters(params):
except for `process_filters` this function is more something aligned with creating filter interface or do I misunderstand? For context: `apply_filters` evoked in me that filters will be applied for e.g. a search request

2023-03-10 14:59 UTC, joschkabraun commented on tests/executor/indexer/test_es_query_building.py
> +        print(processed_filters)
let's remove print

2023-03-10 15:08 UTC, violenil commented on now/executor/gateway/playground/playground.py
> +def apply_filters(params):
So true. I was struggling to think of a correct function name. Perhaps `create_filter_interface()`?

2023-03-10 15:09 UTC, violenil commented on now/executor/gateway/playground/playground.py
> +def apply_filters(params):
Or `render_filters`?

2023-03-10 15:13 UTC, joschkabraun commented on now/executor/gateway/playground/playground.py
> +def apply_filters(params):
Yes, I guess `render_filters` is the most intuitive

2023-03-10 16:16 UTC, makram93 reviewed
Nice work! Already in a good shape! 🚀 
Just some changes suggested to maintain uniformity

2023-03-10 16:16 UTC, makram93 commented on now/executor/gateway/bff/app/v1/models/search.py
> +    filters: Optional[Dict[str, Union[List, Dict[str, int]]]] = Field(
```suggestion
    filters: Optional[Dict[str, Union[List, Dict[str, float]]]] = Field(
```
since in the example provided value is float type?

2023-03-10 16:16 UTC, makram93 commented on now/executor/gateway/bff/app/v1/models/search.py
> +        example={'price': {'$lt': 50.0}},
Is `$` needed here? Can we have the same format for `tags` and `filters` so that FE does not have confusion while integrating?

2023-03-10 16:16 UTC, makram93 commented on tests/executor/indexer/test_elastic_in_flow.py
> +            parameters={'filter': {'tags__price': {'lt': 50.0}}},
```suggestion
            parameters={'filter': {'price': {'lt': 50.0}}},
```
test cases should replicate the values we expect

2023-03-10 20:01 UTC, violenil commented on now/executor/gateway/bff/app/v1/models/search.py
> +    filters: Optional[Dict[str, Union[List, Dict[str, int]]]] = Field(
It could be float or int actually! I can fix that.

2023-03-10 20:01 UTC, violenil commented on now/executor/gateway/bff/app/v1/models/search.py
> +        example={'price': {'$lt': 50.0}},
It is actually not allowed, the $ will cause an error. Will fix.

2023-03-13 08:33 UTC, violenil commented on tests/executor/indexer/test_elastic_in_flow.py
> +            parameters={'filter': {'tags__price': {'lt': 50.0}}},
Actually, we do expect this format for the filter parameters arriving at the indexer. The BFF will modify an incoming filter that looks like this: `'filter': {'price': {'lt': 50.0}}` to -> `'filter': {'tags__price': {'lt': 50.0}}`

2023-03-13 08:34 UTC, violenil commented on tests/executor/indexer/test_elastic_in_flow.py
> +            parameters={'filter': {'tags__price': {'lt': 50.0}}},
The `tags__` prefix helps the es query building to access the correct filter fields found in the tags.

2023-03-13 09:08 UTC, azayz reviewed
Nice changes, I would investigate why patch test coverage is dropping and add tests to that, I would also add some docstring to functions to make sure they are easy to understand

2023-03-13 09:21 UTC, violenil commented
> Nice changes, I would investigate why patch test coverage is dropping and add tests to that, I would also add some docstring to functions to make sure they are easy to understand

@azayz the codecov patch is failing because I am making a few changes to the playground, but we dont test the playground at all (with streamlit it is difficult to test). I added tests for the changes I made, somehow the codecov calculation is off: if you look at the test coverage for query building and for the search model in bff, these are both increased by `2.94%` and `0.04%` respectively

2023-03-13 09:24 UTC, joschkabraun commented
Just so we don't forget about it:

I believe that any key-value pairs in not DocArray data sources will be treated as strings such that the range filter won't be applicable.

2023-03-13 13:04 UTC, makram93 approved these changes
LGTM!

2023-03-13 14:01 UTC, merged