test: add run_k8s coverage
jina-ai/now pull request #1188
Opened 2023-03-13 14:40 UTC by IyadhKhalfallah

---

- [ ] This PR references an open issue
- [ ] Added a test
- [ ] Updated the documentation
- [ ] Added a screenshot of a successful customer deployment

2023-03-15 08:25 UTC, azayz approved these changes

2023-03-15 08:31 UTC, azayz reviewed
Can we try to get the coverage on run k8s even higher, it'S 72% now but I think we can get more

2023-03-15 09:00 UTC, joschkabraun requested changes
Nice changes! Let's push the test coverage higher than it currently is: https://app.codecov.io/gh/jina-ai/now/pull/1188/blob/now/run_all_k8s.py

2023-03-16 11:17 UTC, joschkabraun commented on tests/unit/test_run_all_k8s.py
> +    mock_file = mocker.mock_open(read_data='test')
not sure how to patch reading the file but the file should have a structure of e.g.
```
{
  "lottiefiles-v3-elastic-nowapi-9a817214b3": [
    [],
    [
      ["text_0", "text_0", "encodersbert", 1]
    ],
    [
      ["text_0", "video_0", "encoderclip", 1]
    ]
  ]
}
```
we need to make sure that the test only passes with such formatting

2023-03-20 10:01 UTC, joschkabraun requested changes

2023-03-20 13:52 UTC, joschkabraun approved these changes
After this, LGTM!

2023-03-20 13:54 UTC, merged

2023-03-20 13:56 UTC, IyadhKhalfallah commented on tests/unit/test_run_all_k8s.py
> +        return_value=[MMStructure(is_multimodal=True)],
Merged without paying attention to these comments. I'll add them to #1200