feat: data loading music
jina-ai/now pull request #120
Opened 2022-04-27 09:31 UTC by slettner

2022-05-01 15:58 UTC, florian-hoenicke requested changes

2022-05-01 15:58 UTC, florian-hoenicke commented on now/data_loading/data_loading.py
> +IMAGE_EXTENSIONS = {'.png', '.jpg', '.jpeg', '.tiff', '.bmp', '.gif'}
let's use all image extensions like `webp` and also more audio extensions. Maybe, there is a library which knows all. Or we assume that all files in a folder are images or audio, and we just try to parse them and if parsing fails, we could ignore the related files
Moreover, there are a lot of different name conventions for each file format like `.JPEG` or `.PNG`

2022-05-01 15:58 UTC, florian-hoenicke commented on now/data_loading/data_loading.py
> +        if user_input.custom_dataset_type == DatasetTypes.DOCARRAY:
Really nice to have these enum like types. Makes the code much more readable

2022-05-01 15:58 UTC, florian-hoenicke commented on now/data_loading/data_loading.py
> +def _folder_contains_only(path: str, extensions: Set) -> bool:
I like that you split everything into smaller functions

2022-05-01 15:58 UTC, florian-hoenicke commented on now/data_loading/utils.py
> +    sound = AudioSegment.from_mp3(file=path_to_mp3)
do we have other audio data types as well.
If this will be handled in another pr it is also fine

2022-05-01 15:58 UTC, florian-hoenicke commented on now/run_backend.py
> +    dataset = load_data(user_input)
great to just pass the user_input instead of all single attributes

2022-05-01 15:58 UTC, florian-hoenicke commented on tests/unit/data_loading/test_data_loading.py
> +""" This suite tests the data_loading.py module """
great that this is tested

2022-05-02 08:40 UTC, slettner commented on now/data_loading/data_loading.py
> +IMAGE_EXTENSIONS = {'.png', '.jpg', '.jpeg', '.tiff', '.bmp', '.gif'}
Ok, so we remove the check and just try to parse? Makes sense. For audio, we planned to load the file only to save bandwidth, should we try to parse the audio to check if its valid as well (would be costly).
Alternatively, we could filter the files to the valid extensions and set the filter to the supported types of PIL for image (I think this is what docarray uses) and librosa for audio? 

What do you think?

2022-05-02 08:44 UTC, slettner commented on now/data_loading/utils.py
> +    sound = AudioSegment.from_mp3(file=path_to_mp3)
We can use librosa which support 6 types or so. I would happy to do this in another PR. 
Created an issue here https://github.com/jina-ai/now/issues/144

This will go into the executor because we load the audio there.

2022-05-02 11:31 UTC, slettner commented on now/data_loading/data_loading.py
> +IMAGE_EXTENSIONS = {'.png', '.jpg', '.jpeg', '.tiff', '.bmp', '.gif'}
I just made the following changes:

- images and audio files are loaded best-effort. I.e. if a uri can't be loaded it is ignored
- for audio file, only the binary file data is stored but only after the format is checked so that we don't load arbitrary files from folder

The audio files are later loaded in the executor. This automatically extends the support of audio files to everything that ffmpeg support. 

Changes 6c5840bc8b3bc627a3837e4dad845db3df5d280b

2022-05-02 11:32 UTC, slettner commented
Closes https://github.com/jina-ai/now/issues/144

2022-05-02 11:41 UTC, slettner commented on now/data_loading/utils.py
> +    sound = AudioSegment.from_mp3(file=path_to_mp3)
See the comment above also.

2022-05-02 11:42 UTC, florian-hoenicke commented on now/data_loading/utils.py
> +    sound = AudioSegment.from_mp3(file=path_to_mp3)
okay, sounds good to me

2022-05-02 11:44 UTC, florian-hoenicke commented on now/data_loading/data_loading.py
> +IMAGE_EXTENSIONS = {'.png', '.jpg', '.jpeg', '.tiff', '.bmp', '.gif'}
I like this change. That means it uses all common image formats of the user

2022-05-02 12:34 UTC, florian-hoenicke commented
LGTM

2022-05-02 12:39 UTC, merged