refactor: improve test coverage for CLI
jina-ai/now pull request #1200
Opened 2023-03-16 08:40 UTC by IyadhKhalfallah

---

- [ ] This PR references an open issue
- [ ] Added a test
- [ ] Updated the documentation
- [ ] Added a screenshot of a successful customer deployment

2023-03-17 11:55 UTC, joschkabraun requested changes
In `cli/__init__` test coverage is only ~50%. We can improve this by:
- adding more tests
- removing `logs` from parser (as it's removed either way
- removing `survey` from parser (as this is handled by JAC)

2023-03-20 12:40 UTC, makram93 commented on now/cli/parser.py
> -def set_help_parser(parser=None):
Why are we removing this?

2023-03-20 12:40 UTC, makram93 commented on now/cli/__init__.py
> +    print(parser.parse_known_args())
remove this

2023-03-20 12:41 UTC, IyadhKhalfallah commented on now/cli/parser.py
> -def set_help_parser(parser=None):
@makram93 it is not used anywhere

2023-03-20 13:27 UTC, joschkabraun reviewed
As discussed in the pairing, nice increase in code cov!
Let's make sure that the other two tasks are also tested

2023-03-20 13:27 UTC, joschkabraun commented on tests/unit/test_cli.py
> +class Args:
let's use `Namespace`

2023-03-20 13:32 UTC, IyadhKhalfallah commented on now/cli/__init__.py
> +def get_run_args(parser=None):
You're right, I was passing the argument in a previous test then I removed it. Thanks for the catch

2023-03-23 09:51 UTC, joschkabraun requested changes
Small suggestion, otherwise LGTM

2023-03-23 09:51 UTC, joschkabraun commented on tests/unit/test_cli.py
> +class TestClass:
let's use `Namespace`

2023-03-23 15:24 UTC, Tanguyabel approved these changes
LGTM

2023-03-24 10:27 UTC, merged