Feat weekly latency
jina-ai/now pull request #1201
Opened 2023-03-16 12:17 UTC by joschkabraun

Closes https://github.com/jina-ai/now.private/issues/334

---

- [ ] This PR references an open issue
- [ ] Added a test
- [ ] Updated the documentation
- [ ] Added a screenshot of a successful customer deployment

2023-03-24 13:56 UTC, makram93 commented on now/executor/indexer/elastic/elastic_indexer.py
> +            num_docs = self.es.count(index=self.index_name)['count']
Does this return the total docs count even when there are more than 10_000 docs? Afaik, there is some limitation from es about the size

2023-03-27 08:21 UTC, joschkabraun commented on now/executor/indexer/elastic/elastic_indexer.py
> +            num_docs = self.es.count(index=self.index_name)['count']
No that is only with `es.search` but to get only the count of documents we need to use
- https://elasticsearch-py.readthedocs.io/en/latest/api.html#elasticsearch.Elasticsearch.count
- https://www.elastic.co/guide/en/elasticsearch/reference/master/search-count.html

2023-03-29 08:33 UTC, makram93 commented on now/executor/indexer/elastic/elastic_indexer.py
> +            num_docs = self.es.count(index=self.index_name)['count']
Awesome, this will be super helpful!

2023-03-29 08:44 UTC, makram93 requested changes

2023-03-29 08:44 UTC, makram93 commented on now/admin/benchmark_flow.py
> +    with ProcessPoolExecutor(max_workers=n_qps_calls) as executor:
```suggestion
    with ProcessPoolExecutor(max_workers= n_qps_workers) as executor:
```

2023-03-29 08:44 UTC, makram93 commented on now/admin/benchmark_flow.py
> +        for i in range(n_qps_workers):
```suggestion
        for i in range(n_qps_calls):
```

2023-03-29 11:34 UTC, joschkabraun commented on now/admin/benchmark_flow.py
> +    n_qps_workers: int = 10,
The `ThreadPoolExecutor` executes functions which are mostly waiting such that only 2 threads running at a time is okay. You can also see [here](https://jinaai.slack.com/archives/C04UACZBRRU/p1679508694793719?thread_ts=1679508686.258449&cid=C04UACZBRRU) that e.g. P99 decreases with number of parallel calls (i.e. workers). So that the limitation of 2 cores isn't an issue in this case.

2023-03-29 11:35 UTC, joschkabraun commented on now/admin/benchmark_flow.py
> +        for i in range(n_qps_workers):
Good catch!

2023-03-29 15:29 UTC, IyadhKhalfallah approved these changes
Nice work, LGTM 🚀

2023-04-03 14:49 UTC, makram93 approved these changes
LGTM!  🚀

2023-04-03 15:14 UTC, merged