feat: add s3 param for demos
jina-ai/now pull request #1251
Opened 2023-04-05 11:21 UTC by IyadhKhalfallah

---

- [ ] This PR references an open issue
- [ ] Added a test
- [ ] Updated the documentation
- [ ] Added a screenshot of a successful customer deployment

2023-04-05 13:08 UTC, makram93 commented on now/data_loading/data_loading.py
> +def list_files_from_s3_bucket(
Do you intend to call this function on the API side for the S3 data preview?

2023-04-05 13:42 UTC, Tanguyabel commented on now/data_loading/data_loading.py
> +        objects = list(bucket.objects.filter(Prefix=folder_prefix))
```suggestion
    objects = bucket.objects.filter(Prefix=folder_prefix)
    if top_n:
        objects = objects.limit(top_n))
    objects = list(objects)
```

2023-04-05 13:45 UTC, IyadhKhalfallah commented on now/data_loading/data_loading.py
> +def list_files_from_s3_bucket(
Yes

2023-04-05 13:47 UTC, IyadhKhalfallah commented on now/data_loading/data_loading.py
> +        objects = list(bucket.objects.filter(Prefix=folder_prefix))
@Tanguyabel The suggested solution actually filters everything, and then it limits. Thus, the performance will drop when I want to take only the first 10 elements. Adding `.limit(top_n)` however will limit before getting the actual data, so it is very efficient that way!

2023-04-05 14:18 UTC, joschkabraun requested changes
After adding documentation + test this LGTM

2023-04-05 14:18 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +def validate_shrink_data(file_paths):
Can you add documentation on the functionality this function executes?

2023-04-05 14:21 UTC, IyadhKhalfallah commented on now/data_loading/data_loading.py
> +def validate_shrink_data(file_paths):
Sure, will do!

2023-04-06 08:46 UTC, Tanguyabel approved these changes

2023-04-06 08:46 UTC, Tanguyabel commented on now/data_loading/data_loading.py
> +        objects = list(bucket.objects.filter(Prefix=folder_prefix))
Sure, I thought of this, and thought the query is not evaluated until you generate a list from it. But if you are sure performances are impacted, then please leave it as it.

2023-04-06 08:57 UTC, joschkabraun approved these changes

2023-04-12 09:14 UTC, merged