feat: elastic index cleanup
jina-ai/now pull request #1269
Opened 2023-04-20 13:30 UTC by IyadhKhalfallah

---

- [ ] This PR references an open issue
- [ ] Added a test
- [ ] Updated the documentation
- [ ] Added a screenshot of a successful customer deployment

2023-04-20 13:37 UTC, makram93 requested changes
How will this script run? Will somebody manually run it every time it is needed?
Can we schedule a cron job to run this script daily to avoid manual interference?

2023-04-20 14:01 UTC, girishc13 commented
> How will this script run? Will somebody manually run it every time it is needed? Can we schedule a cron job to run this script daily to avoid manual interference?

The script needs to be run manually for now until we can get a secure way of listing all the deployments in jcloud. This is why the automatic job in the es-index-manager was removed.

2023-04-21 09:04 UTC, makram93 approved these changes

2023-04-21 09:05 UTC, Tanguyabel approved these changes

2023-04-21 12:32 UTC, merged