feat: add flow id to meta
jina-ai/now pull request #1276
Opened 2023-04-27 15:24 UTC by IyadhKhalfallah

---

- [ ] This PR references an open issue
- [ ] Added a test
- [ ] Updated the documentation
- [ ] Added a screenshot of a successful customer deployment

2023-05-05 06:49 UTC, makram93 requested changes

2023-05-05 06:49 UTC, makram93 commented on now/executor/gateway/hubble_report.py
> +                    'flowId': namespace.split('-')[1] if namespace else namespace,
you can rely on `user_input.flow_name`
```suggestion
                    'flowId': user_input.flow_name + '-' + namespace,
```

2023-05-09 08:28 UTC, shazhou2015 commented
Is this PR ready to merge now? @IyadhKhalfallah @makram93

2023-05-09 09:04 UTC, makram93 commented on now/executor/gateway/hubble_report.py
> +        namespace = os.environ.get('K8S_NAMESPACE_NAME')
We can remove this, now that we have full flow name

2023-05-10 08:21 UTC, girishc13 commented
LGTM

2023-05-10 08:25 UTC, Tanguyabel approved these changes

2023-05-10 08:26 UTC, merged