feat: update logo shown on frontend
jina-ai/now pull request #128
Opened 2022-04-28 11:37 UTC by makram93

I have updates the torch requirements to `torch>=1.10.2` and the logo looks like this:

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/6537525/165743711-c09785a3-d040-4060-9773-a877220c6646.png">

2022-04-28 12:50 UTC, joschkabraun commented on setup.py
> +torch_requirement = ['torch>=1.10.2']
Do we support torch>=1.10.2?

2022-04-28 13:29 UTC, joschkabraun approved these changes
LGTM

2022-04-28 14:11 UTC, joschkabraun approved these changes

2022-05-01 16:42 UTC, florian-hoenicke commented on requirements.txt
> +torchvision>=0.11.3
should be handled in a different pr next time

2022-05-01 16:44 UTC, florian-hoenicke requested changes
Great initiative updating the logo.
However, the logo should be jpg or SVG.

2022-05-01 16:45 UTC, florian-hoenicke requested changes
why are the banners added?

2022-05-03 07:18 UTC, makram93 commented
> Great initiative updating the logo. However, the logo should be jpg or SVG.

Are you referring to the `favicon.png`? I cross-referenced with other repo - docarray and jina, both of which have favicon and banner in png format.



> why are the banners added?

It is not important but to have uniformity with other repos such as [here](https://github.com/jina-ai/jina/blob/master/docs/conf.py#L168), I added it for NOW. Usage of this can be found [here](https://github.com/wpilibsuite/sphinxext-opengraph/blob/main/README.md#:~:text=ogp_image,defined%20by%20ogp_site_name.).

2022-05-03 07:19 UTC, makram93 commented on requirements.txt
> +torchvision>=0.11.3
I will revert this for this PR

2022-05-03 22:21 UTC, florian-hoenicke requested changes

2022-05-03 22:21 UTC, florian-hoenicke commented on now/run_all_k8s.py
> +            docker_frontend_tag = '0.0.8-dev-update-logo'
I think this should be just 0.0.8.
Or correct me please @joschkabraun if I'm mistaken.

2022-05-04 12:05 UTC, florian-hoenicke approved these changes
LGTM

2022-05-04 12:07 UTC, makram93 commented on now/run_all_k8s.py
> +            docker_frontend_tag = '0.0.8-dev-update-logo'
I have updated the version. It should be `0.0.8` now

2022-05-04 12:12 UTC, merged