feat: add text-to-text app and update indexing in bff
jina-ai/now pull request #237
Opened 2022-06-01 13:50 UTC by joschkabraun

Closes #235 and #244.

- [x] Add Sentence-BERT for text-to-text search to improve search results over CLIP text encoder.
- [x] Update BFF indexing to allow for indexing with `tags` attribute to retrieve those later.

Minor updates:
- [x] Refactor 'app' folder to move logic for fine-tuning to the apps.
- [x] Update test run time

2022-06-07 07:48 UTC, slettner commented on now/apps/base/app.py
> +    def set_flow_yaml(self, finetuning: bool):
Is there a reason for renaming and removing and implementation? I am used to the previous naming convention for setter.

2022-06-07 07:51 UTC, slettner commented on now/apps/base/app.py
> +    def set_flow_yaml(self, finetuning: bool):
Just read further, I assume it is because of the finetuning arg. 
Could this also be passed to the app constructor itself? Probably it is not available at that time?

2022-06-07 08:13 UTC, slettner commented on now/apps/image_to_image/app.py
> +    def set_flow_yaml(self, finetuning: bool = False):
Maybe we can consider the finetuning arg as a separate property of the app and set it before the flow yaml is set. This way we could keep the old signature for `set_flow_yaml`.

2022-06-07 08:13 UTC, slettner commented on now/apps/image_to_image/app.py
> +        self._flow_yaml = os.path.join(flow_dir, 'flow-clip.yml')
Is there a reason why this is already set here? Look very similar to the code in `set_flow_yaml`

2022-06-07 08:16 UTC, slettner commented on now/finetuning/settings.py
> +        pre_trained_embedding_size=app_instance.pre_trained_embedding_size[
Good change to move this to the app!

2022-06-07 08:19 UTC, slettner commented on now/apps/image_to_image/app.py
> +    def set_flow_yaml(self, finetuning: bool = False):
On the other side we have to make sure that the two setters are called in the right order because `flow_yaml` depends on the finetuning arg .. not sure here

2022-06-07 08:22 UTC, slettner commented on now/apps/image_to_image/app.py
> +    def set_flow_yaml(self, finetuning: bool = False):
Maybe we have to refactor the construction process a bit at some point. I could imagine that a builder pattern or something similar would make different construction steps and their dependencies more explicit but that is a separate PR. 

I guess it is best to keep it as you proposed it @joschkabraun :)

2022-06-07 09:44 UTC, joschkabraun commented on now/apps/base/app.py
> +    def set_flow_yaml(self, finetuning: bool):
We currently have `JinaNOWApp` and `UserInput`. The former one is static and provides the options associated with each app. The latter one is dynamic and changes with each user input, e.g. fine-tuning.
Maybe there is a better way to let those two objects interact.

2022-06-07 09:48 UTC, joschkabraun commented on now/apps/base/app.py
> +    def set_flow_yaml(self, finetuning: bool):
I think a better solution is to rename this to `get_flow_yaml` and call that at the appropriate times. Thanks for the input!

2022-06-07 10:12 UTC, joschkabraun commented on now/apps/image_to_image/app.py
> +    def set_flow_yaml(self, finetuning: bool = False):
I agree, I am not happy with how it currently is handled. Let's refactor this later on!

2022-06-07 10:51 UTC, slettner commented on now/apps/base/app.py
> +    def set_flow_yaml(self, finetuning: bool):
understand, I think I have to look a bit more into `JinaNowApp` to understand what it represents.

2022-06-07 15:51 UTC, makram93 reviewed
Overall looks good to me! Some minor comments :)

2022-06-08 11:57 UTC, joschkabraun commented on now/apps/music_to_music/app.py
> +        }
Yes, it is set to `Qualities.MEDIUM` by default: https://github.com/jina-ai/now/blob/1e39d77347da3fcab39558e9730dba0db9e473ee/now/finetuning/settings.py#L39

2022-06-08 11:58 UTC, joschkabraun commented on now/apps/image_to_image/app.py
> +        self._flow_yaml = os.path.join(flow_dir, 'flow-clip.yml')
Good point!

2022-06-08 11:59 UTC, joschkabraun commented on now/apps/text_to_text/app.py
> +        self._flow_yaml = os.path.join(flow_dir, 'flow-clip.yml')
Yes, thanks!

2022-06-09 11:16 UTC, joschkabraun commented on now/apps/base/app.py
> +        self._flow_yaml = os.path.join(curdir, 'flow.yml')
I think pointing to the other flow files makes a lot of sense. We can let it point to the same directory once we migrate the apps out of the repository.

2022-06-13 09:13 UTC, makram93 requested changes
LGTM! 🚀 
Some minor comments

2022-06-13 09:13 UTC, makram93 commented on now/apps/text_to_text/flow-sbert.yml
> +      memory: 8G
This should be updated to include `resources` under `jcloud`. For more reference you can read this [thread](https://jinaai.slack.com/archives/C01E03LN3K7/p1654676429965409)
Also, please update other flows accordingly. I'm sorry I didn't do it in my last PR

2022-06-13 11:17 UTC, merged