feat: add apps as subcommand
jina-ai/now pull request #241
Opened 2022-06-07 07:27 UTC by makram93

Add apps as a subcommand and make arguments supported for each apps unique to them... 

- Users can now enter `jina-now start -h` to get the below help screen, where `image_to_image`, `image_to_text` and `text_to_image` are the subcommand corresponding to each app.  <img width="616" alt="image" src="https://user-images.githubusercontent.com/6537525/172320342-9ab069a5-ffce-45ab-a191-d3f3067b099c.png">

- When the user enters `jina-now start image_to_image -h`, he/she gets the help (or additional arguments) for that respective app only
- There's also an argument `--app` whose value/choices are the same as `subcommands` and is picked from `Apps` Enum. If used, the dialog to select the app will not show. Also, when using the `subcommand` the `--app` argument's value is overridden. For e.g: `jina-now start --app image_to_text image_to_image` will have the `app=image_to_image` when argument parsing is done.

2022-06-07 09:40 UTC, joschkabraun commented
Great PR! I would refactor it such that all the configurations of the apps are handled within the app and not somewhere else.

2022-06-07 13:41 UTC, makram93 commented on now/cli/parser.py
> +    )
Thanks for the suggestion. I like it too.. Keeping all maintenance in one place.

2022-06-09 09:23 UTC, florian-hoenicke commented on now/apps/base/app.py
> +                help=self.description,
nice. I like this way of getting the attributes. Minimizes the effort of implementing the derived class

2022-06-09 09:25 UTC, florian-hoenicke commented on now/cli/parser.py
> +    url_str = '\n'.join(f'- {v[0]:<15} {k:10.10}\t{v[1]}' for k, v in urls.items())
What is this logic doing?

2022-06-09 09:26 UTC, makram93 commented on now/cli/parser.py
> +    url_str = '\n'.join(f'- {v[0]:<15} {k:10.10}\t{v[1]}' for k, v in urls.items())
Ah this is from the core repo... It just prints the extra message at the end
<img width="443" alt="image" src="https://user-images.githubusercontent.com/6537525/172814336-3073ea06-9ade-4eca-ab79-4bc5531ed162.png">

2022-06-09 09:27 UTC, makram93 commented on now/finetuning/embeddings.py
> +        uses=f'jinahub+sandbox://{encoder_uses}',
Yes, sorry. I was working on it and by mistake, it got added to this PR. Thanks! :)

2022-06-09 09:30 UTC, florian-hoenicke requested changes

2022-06-09 09:30 UTC, florian-hoenicke commented on now/apps/base/app.py
> +        return ''
raise NotImplemented error. This is a mandatory attribute without default value

2022-06-09 09:30 UTC, florian-hoenicke commented on now/cli/parser.py
> +    ImageToImage().set_app_parser(sub_parser, formatter=_chf)
If you add a new app, you would have to make a code change here. For instance, the MusicToMusic app would have to be enabled as you are stating in the comment.
A better way of doing it is to automatically add everything which is in the Apps list. in the constants.py

2022-06-09 10:29 UTC, makram93 commented on now/cli/parser.py
> +    ImageToImage().set_app_parser(sub_parser, formatter=_chf)
Thanks for the suggestion! 👍

2022-06-09 12:12 UTC, florian-hoenicke commented on now/cli/parser.py
> +    for app in Apps():
nice - I like

2022-06-09 12:13 UTC, florian-hoenicke commented
Well done - that is a lean solution

2022-06-09 12:13 UTC, merged