Feat share button
jina-ai/now pull request #259
Opened 2022-06-13 22:01 UTC by makram93

Add social share button

2022-06-16 09:48 UTC, joschkabraun requested changes
Nice, adding of sharing button!

2022-06-16 09:48 UTC, joschkabraun commented on deployment/playground/playground.py
> +            print(data_dir + DATA + f'.txt10-{docarray_version}.bin')
don't need the print

2022-06-16 09:48 UTC, joschkabraun commented on deployment/playground/playground.py
> +    HOST = "grpcs://nowapi-1cf62a2f29.wolf.jina.ai"  # query_parameters.get('host')[0]
You forgot to comment out the values for testing

2022-06-16 09:48 UTC, joschkabraun commented on now/deployment/deployment.py
> +    return
What is the purpose of this? If that is intended, we should remove this function.

2022-06-20 18:57 UTC, makram93 commented on deployment/playground/playground.py
> +    HOST = "grpcs://nowapi-1cf62a2f29.wolf.jina.ai"  # query_parameters.get('host')[0]
Was testing it locally, forgot to revert this. Thanks for pointing it out

2022-06-22 08:48 UTC, merged