feat: add tags
jina-ai/now pull request #398
Opened 2022-08-24 16:41 UTC by azayz

2022-08-24 19:11 UTC, florian-hoenicke requested changes

2022-08-24 19:11 UTC, florian-hoenicke commented on now/data_loading/data_loading.py
> +        folder = d.uri.split('/')[-2]
it can still be the case that two subfolders are identical even though they are in different parent folders. This would lead to collisions
Instead, you can use `d.uri.rsplit('/', 1)[0]`

2022-08-24 19:11 UTC, florian-hoenicke commented on now/data_loading/data_loading.py
> +        folder = d.uri.split('/')[-2]
I think you don't have to determin the folder again

2022-08-25 07:31 UTC, azayz commented on now/data_loading/data_loading.py
> +        folder = d.uri.split('/')[-2]
I think I do because I go through the documents twice, one (L63) to put gif paths in the dictionary and second (L68) to determine if a json file's folder path corresponds to a gif (exists in the dict)

2022-08-25 09:45 UTC, joschkabraun requested changes

2022-08-25 09:45 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +        if not d.uri.endswith('.json') and folder not in dic:
loading the json file will fail as the json is on s3 or another cloud bucket

2022-08-25 09:45 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +
This logic will update the tags of the last document in the same folder as the json.
I would extend this to:
- test that only one file is in the same folder to make sure that we assign the tags to the right document (might even need to be extended to check that only the one file in the folder which matches the output modality of the app)
- if there are multiple files in folder, match json with file which has the same stem

2022-08-25 09:45 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +    for i, d in enumerate(da):
I would filter returned docarray to not contain .json files anymore as they already have been been processed

2022-08-25 15:32 UTC, azayz commented on now/data_loading/data_loading.py
> +
I believe this is on the client's side to ensure that his data follows the specific structure otherwise It would be hard to generalize

2022-08-25 18:44 UTC, florian-hoenicke requested changes

2022-08-25 18:44 UTC, florian-hoenicke commented on now/data_loading/data_loading.py
> +
> if there are multiple files in folder, match json with file which has the same stem
yes, that would be a good idea. If you want to skip it in this pr to keep it small it is also fine.
> test that only one file is in the same folder to make sure that we assign the tags to the right document
in that case, I would drop the file if it is just an annotation and keep if it is just a content file

2022-08-26 13:03 UTC, joschkabraun reviewed
After comments, good to go! :rocket:

2022-08-26 13:03 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +            da = _load_tags_from_json(da, user_input, True)
add `if any([doc.uri.endswith('.json') for doc in da])`

2022-08-26 13:03 UTC, joschkabraun commented on now/data_loading/data_loading.py
>              da = _load_from_disk(app, user_input)
with add `if any([doc.uri.endswith('.json') for doc in da])` we can also activate for local storage

2022-08-29 09:27 UTC, florian-hoenicke commented on now/data_loading/data_loading.py
> +    path_splits = path.split('/')
```
'a/b/c/d/e.json'.split('/', 1)
Out[3]: ['a', 'b/c/d/e.json']
```

2022-08-29 09:37 UTC, florian-hoenicke approved these changes
LGTM

2022-08-29 09:55 UTC, merged