Refactor dialog app options
jina-ai/now pull request #459
Opened 2022-09-02 12:14 UTC by makram93

2022-09-05 11:31 UTC, joschkabraun submitted a review, later dismissed

2022-09-05 11:31 UTC, joschkabraun commented on now/now_dataclasses.py
> +    app_instance: Optional['JinaNOWApp'] = None  # noqa: F821
we should either have an attribute with `Apps` or `JinaNOWApp` but not both

2022-09-05 11:31 UTC, joschkabraun commented on now_common/options.py
> +def _check_if_existing():
Given the new location of the function, the name isn't descriptive enough anymore such that I would change it

2022-09-05 11:31 UTC, joschkabraun commented on now/apps/image_to_text/app.py
> +                and user_input.data == 'custom'
other apps also check `user_input.is_custom_dataset`

2022-09-05 11:31 UTC, joschkabraun commented on now/now_dataclasses.py
> -    is_custom_dataset: Optional[bool] = None
this attribute is used in some tests and executors AFAIK

2022-09-05 11:31 UTC, joschkabraun commented on now_common/options.py
> +def _setup_cluster(user_input: UserInput, **kwargs) -> None:
Is that correct? The name is very similar to `run_all_k8s.setup_cluster` ...

2022-09-05 11:31 UTC, joschkabraun commented on now/dialog.py
> +    return user_input.app_instance, user_input
given that now `user_input` contains the app; we don't need to return both

2022-09-05 11:31 UTC, joschkabraun commented on tests/integration/test_end_to_end.py
> -        (
I think you forgot to uncomment those again

2022-09-05 11:31 UTC, joschkabraun commented on tests/unit/test_dialog.py
> +        UserInput(),
The last parameter is the `expected_user_input`; so we test them all to be empty? I.e. the tests says everything is good, when we don't actually have set anything?

2022-09-05 11:54 UTC, joschkabraun commented on now/dialog.py
> +    configure_option(JinaNOWApp.ask_app(), user_input, **kwargs)
If we refactor this, we can get rid of having both `app` and `app_instance` in `user_input` which I believe is confusing to ask.
Also, an app shouldn't be able to configure this as we need to ask this basic question at the beginning of `jina now start`.

2022-09-05 11:55 UTC, joschkabraun commented on now/finetuning/run_finetuning.py
> -from now.now_dataclasses import UserInput
Why importing `UserInput` from `now_common.options` and not from `now.now_dataclasses` where it is actually located?

2022-09-05 11:59 UTC, makram93 commented on tests/unit/test_dialog.py
> +        UserInput(),
It is updated inside the function

2022-09-05 12:16 UTC, makram93 commented on now/now_dataclasses.py
> -    is_custom_dataset: Optional[bool] = None
Removed the occurences. We only rely on data='custom'

2022-09-05 14:04 UTC, joschkabraun commented on tests/unit/test_dialog.py
> +        UserInput(),
Ok. Let's remove it from the `parametrize` then

2022-09-06 13:44 UTC, joschkabraun requested changes
We also need to update `.gitignore` to not save `.lock` files in `dask-worker-space`.

2022-09-06 13:44 UTC, joschkabraun commented on now/dialog.py
> +    configure_option(JinaNOWApp.ask_app(), user_input, **kwargs)
I would remove `ask_app` from `JinaNOWApp` as it's part of the framework and not a single app

2022-09-06 13:44 UTC, joschkabraun commented on now/apps/base/app.py
> ~        """
I think `property` makes more sense or lmk if `staticmethod` makes more sense

2022-09-06 13:44 UTC, joschkabraun commented on now/apps/base/app.py
> +    def ask_app():
we can remove that after changing `dialog`

2022-09-06 13:44 UTC, joschkabraun commented on now/apps/base/app.py
> ~        Set to True if this app is enabled for the end user.
I would update the docstring to reflect how this property is now going to be used. Also, would show how it can be extended

2022-09-06 13:44 UTC, joschkabraun commented on now/run_backend.py
> +    parameters['user_input'].pop('app_instance')
I don't think that is a good solution as this changes the interface and executor don't expect `app` attribute anymore

2022-09-06 14:54 UTC, makram93 commented on now/run_backend.py
> +        'user_input': user_input.__dict__,
Yes, it works the same way since pydantic dataclasses under the hood has dataclasses.dataclass

2022-09-06 15:00 UTC, makram93 commented on now/run_backend.py
> +    parameters['user_input'].pop('app_instance')
We can not send an class object to as param and currently all user_input is convert to dict and passed as param. We have to remove the app_instance, however, since `app` is not expected anymore I will remove it from that line. Thanks for pointing it out

2022-09-07 11:28 UTC, violenil commented on now_common/options.py
> +        },
should `Apps.TEXT_TO_TEXT_AND_IMAGE` be an option here?

2022-09-07 11:30 UTC, makram93 commented on now_common/options.py
> +        },
Yes It should be but only added to this list once this feature is integrated and ready to use.

2022-09-07 11:58 UTC, joschkabraun approved these changes
LGTM! :rocket: Really nice refactoring :) I like how now arguments are exposed to the CLI

2022-09-07 12:10 UTC, merged