feat: adapt finetuning to nest
jina-ai/now pull request #470
Opened 2022-09-06 14:07 UTC by jupyterjazz

2022-09-07 08:48 UTC, joschkabraun submitted a review, later dismissed
We should move any app dependent logic from `settings.py` into the apps to have it all in the same place.

2022-09-07 08:48 UTC, joschkabraun commented on now/finetuning/run_finetuning.py
>          callbacks=callbacks,
would leave it as `_maybe_add_embeddings` as it only will add embeddings if they don't exist

2022-09-07 10:35 UTC, violenil commented on now/finetuning/settings.py
> +        model_name=user_input.app.finetuning_model_name(encoder_type),
how will this work when we want to finetune two models (sbert and clip)? Will we get two `FinetuneSettings`?

2022-09-07 13:12 UTC, jupyterjazz commented on now/finetuning/settings.py
> +        model_name=user_input.app.finetuning_model_name(encoder_type),
Exactly!

2022-09-07 21:33 UTC, florian-hoenicke requested changes
I think it is good that you are tackling this.
It is a necessary refactoring.
The open point of discussion is where to put the fine-tuning logic.
I think the base app should be very general and not include app-specific things like fine-tuning. We should rather put it into our common package for now.

At a later point in time I would suggest to have mixins (similar to docarray) for all the things we have in the common package.

2022-09-07 21:33 UTC, florian-hoenicke commented on now/apps/text_to_text_and_image/app.py
> +    def finetuning_model_name(self, encoder_type: Optional[str] = None) -> str:
This property makes the assumption that each app uses a model to fine-tune.

2022-09-07 21:33 UTC, florian-hoenicke commented on now/apps/text_to_text_and_image/app.py
> +    def finetuning_model_name(self, encoder_type: Optional[str] = None) -> str:
I think finetuning should not be a property of a base app

2022-09-07 21:33 UTC, florian-hoenicke commented on now/apps/base/app.py
> +    def loss_function(self, encoder_type: Optional[str] = None) -> str:
I don't think finetuning should be part of the base app for two reasons:
1. an app might not need fine-tuning
2. an app might use multiple loss functions and models. So it is hard to generalize.

The first point could be tackled by introducing a fine-tuning Mixin

2022-09-08 08:13 UTC, joschkabraun commented
I think we can move all that logic to the `setup` function. Some things are shared by many apps which then can go into `now_common`. The new losses, etc. for `text-to-text-and-image` go in that app folder.

2022-09-08 15:31 UTC, merged