feat: add filtering playground
jina-ai/now pull request #473
Opened 2022-09-07 14:09 UTC by azayz

2022-09-09 11:39 UTC, joschkabraun requested changes
Given that we are getting rid of docarray indexer, we should move all the logic / changes in the post processor into the `NOWAnnLiteIndexer` then we also don't have to worry about building new Postprocessor and securitizing it

2022-09-09 11:39 UTC, joschkabraun commented on now_common/flow/flow-clip.yml
> +    uses: jinahub+docker://NOWPostprocessorV2/v0.0.5
any `flow.yaml` needs to be updated to the new post-processor

2022-09-09 11:39 UTC, joschkabraun commented on deployment/playground/playground.py
> +            client = Client(host=params.host)
This seems a bit like an antipattern given that we usually call the BFF and now we call the client.. what do you think?

2022-09-09 11:39 UTC, joschkabraun commented on now_executors/NOWPostprocessor/executor.py
> +    @requests(on='/tags')
Should use `secure_request` as NOWPreprocessor does in order to secure the data

2022-09-09 11:39 UTC, joschkabraun commented on now_executors/NOWPostprocessor/executor.py
> +class NOWPostprocessorV2(Executor):
post processor needs to extend `NOWAuthExecutor` given that is handling data

2022-09-09 16:19 UTC, azayz commented on deployment/playground/playground.py
> +            client = Client(host=params.host)
I do agree with you but it felt unnecessary to create new BFF endpoint which will not be exposed to the clients (/tags), a direct call from the playground to the flow seemed more logical  to retrieve just the tags and their values

2022-09-09 16:32 UTC, joschkabraun requested changes
I wouldn't change the `NOWPostprocessor` but move all those changes into `NOWAnnLiteIndexer` as this is the only indexer moving forward after https://github.com/jina-ai/now/pull/491 has been merged. You can modify `NOWAnnLiteIndexer` already and changes will be automatically built on CI.

2022-09-12 08:35 UTC, joschkabraun reviewed
The PR looks good! For consistency, we should also handle the tags for the `update` and `delete` endpoint`.

2022-09-12 08:35 UTC, joschkabraun commented on deployment/playground/src/search.py
> +    print('search by text : ', filter_selection)
would remove print

2022-09-12 08:35 UTC, joschkabraun commented on deployment/playground/playground.py
> +            response = client.post(on='/tags')
in case the fow is secured, we need to also provide the `token` of the user

2022-09-12 08:35 UTC, joschkabraun commented on now_executors/NOWAnnLiteIndexer/executor.py
> +        if os.path.isfile('./tags.pkl'):
Nice that you persist this! I would persist it though in `self.workspace` if it exists (some logic is in `NOWAuthExecutor`)

2022-09-12 08:35 UTC, joschkabraun commented on now_executors/NOWAnnLiteIndexer/executor.py
> +    def get_tags_and_values(self, **kwargs):
can you please add some docs here on what it returns and the format of it

2022-09-12 14:31 UTC, makram93 reviewed
Playground changes look good. Nice work! 👍 
For Indexer, I have left some comments, let me know if the suggestion makes sense.

2022-09-12 20:51 UTC, azayz commented on now_executors/NOWAnnLiteIndexer/executor.py
> +                        self.tags_values[tag].remove(value)
I agree, thanks for the valuable comment, I changed the code accordingly

2022-09-12 20:52 UTC, azayz commented on now_executors/NOWAnnLiteIndexer/executor.py
> +                self.tags_values[tag].add(value)
I don't see how moving the logic inside will reduce iterations, can you elaborate ?

2022-09-14 13:03 UTC, makram93 approved these changes
LGTM! 🚀

2022-09-14 13:54 UTC, joschkabraun approved these changes
LGTM! :rocket:

2022-09-14 13:54 UTC, joschkabraun commented on now_executors/NOWAnnLiteIndexer/executor.py
> +        for id, tags in self.doc_id_tags.items():
I would replace with `self.doc_id_tags.values()`

2022-09-16 11:35 UTC, merged