feat: add elastic indexer
jina-ai/now pull request #474
Opened 2022-09-07 14:52 UTC by violenil

This PR introduces the ElasticIndexer which should be used for the Nest app.

2022-09-09 11:26 UTC, joschkabraun commented
I am not sure if you already plan on doing that. But when you are ready to push the first version, can put building of the indexer on CI similar to how it is done for the `NOWPreprocessor`, `NOWAuthExecutor` and `NOWAnnLiteIndexer` (https://github.com/jina-ai/now/blob/main/.github/workflows/ci.yml#L89). For that it's also important to log out of the jina account before pushing.

2022-09-11 07:52 UTC, florian-hoenicke requested changes
This is a good step to add the elastic search indexer to the NOW repo.
It will give all NOW apps more reliability.
I requested some changes which are required to make the elastic search indexer work with the other apps.

2022-09-11 07:52 UTC, florian-hoenicke commented on now_executors/elastic_indexer/elastic_indexer.py
> +if __name__ == "__main__":
Could you please create an integration test out of that code snippet instead of having it as the main function?

2022-09-11 07:52 UTC, florian-hoenicke commented on now_executors/elastic_indexer/elastic_indexer.py
> +        es_connection_str: Optional[str] = 'http://localhost:9200',
How is access to private remote clusters handled? Is everything we require contained in the connection string?

2022-09-11 07:52 UTC, florian-hoenicke commented on now_executors/elastic_indexer/elastic_indexer.py
> +        es_mapping: Optional[Dict] = None,
is there a reasonable default value? I think by default, it should assume we just insert documents with single embeddings.

2022-09-11 07:52 UTC, florian-hoenicke commented on now_executors/elastic_indexer/elastic_indexer.py
> +    def __init__(
we should also add a limit parameter

2022-09-11 07:52 UTC, florian-hoenicke commented on now_executors/elastic_indexer/elastic_indexer.py
> +        self.es = Elasticsearch(es_connection_str, verify_certs=False)
verify certs = False does look a bit wrong. Is this introducing some security issue or is it fine?

2022-09-11 07:52 UTC, florian-hoenicke commented on now_executors/elastic_indexer/elastic_indexer.py
> +            self.es_mapping = MAPPING
MAPPING can directly be taken as default value

2022-09-11 07:52 UTC, florian-hoenicke commented on now_executors/elastic_indexer/elastic_indexer.py
> +    def __init__(
I think it would make sense to also add `dim` and explain in the docstring that `dim` and `metric` are only used in case no mapping is defined

2022-09-11 07:52 UTC, florian-hoenicke commented on now_executors/elastic_indexer/elastic_indexer.py
> +        distance: str = 'cosine',
```suggestion
        metric: str = 'cosine',
```

2022-09-11 07:52 UTC, florian-hoenicke commented on now_executors/elastic_indexer/elastic_indexer.py
> +    def __init__(
please add `traversal_paths`

2022-09-11 07:52 UTC, florian-hoenicke commented on now_executors/elastic_indexer/elastic_indexer.py
> +        self, docs: Union[Document, DocumentArray], limit: Optional[int] = 20, **kwargs
allow filtering by tags as well similar to annlite

2022-09-11 07:52 UTC, florian-hoenicke commented on now_executors/elastic_indexer/elastic_indexer.py
> +
We need a list endpoint for the sync job to get all existing file URIs.

2022-09-11 07:52 UTC, florian-hoenicke commented on now_executors/elastic_indexer/elastic_indexer.py
> +    def _transform_docs_to_es(self, docs: DocumentArray) -> List[Dict]:
I think this function should also support the simple case where we just have one document with a single embedding. If this is supported, all the other NOW apps can use this indexer.  Maybe, you could make the transformation based on the provided mapping. But if it is too complicated, then we need another way to support single documents.

2022-09-11 07:52 UTC, florian-hoenicke commented on now_executors/elastic_indexer/elastic_indexer.py
> +    def _build_es_query(
Score function should also handle the simple case where we just have one document with one embedding

2022-09-12 14:08 UTC, girishc13 reviewed
Hi there, don't mind me randomly popping in to provide some suggestions. Feel free to ignore the some suggestions if it doesn't support the immediate goal.

2022-09-12 14:44 UTC, violenil commented on now_executors/elastic_indexer/elastic_indexer.py
> +    def __init__(
Is it not sufficient to have a limit parameter on the search endpoint?

2022-09-12 18:05 UTC, joschkabraun requested changes
Can you put building of this indexer on CI similar to how it is done for the `NOWPreprocessor`, `NOWAuthExecutor` and `NOWAnnLiteIndexer` (https://github.com/jina-ai/now/blob/main/.github/workflows/ci.yml#L89). For that it's also important to log out of the jina account before pushing to get a secret to build it.

2022-09-13 13:36 UTC, violenil commented on now_executors/elastic_indexer/elastic_indexer.py
> +        self.es = Elasticsearch(es_connection_str, verify_certs=False)
resolved using `es_config`

2022-09-13 15:14 UTC, jupyterjazz reviewed
This is so exciting!

added few minor comments

2022-09-13 15:14 UTC, jupyterjazz commented on now_executors/elastic_indexer/elastic_indexer.py
> +        Index new `Document`s by adding them to the Elasticsearch indeex.
```suggestion
        Index new `Document`s by adding them to the Elasticsearch index.
```

2022-09-13 15:14 UTC, jupyterjazz commented on now_executors/elastic_indexer/elastic_indexer.py
> +            print("No embeddings extracted")
should we raise an error here?

2022-09-13 15:14 UTC, jupyterjazz commented on now_executors/elastic_indexer/elastic_indexer.py
> +                if chunk.modality == "text":
let's stay consistent with single quotes

2022-09-13 15:15 UTC, jupyterjazz commented on now_executors/elastic_indexer/elastic_indexer.py
> +            "dims": 5,
why do we have 5 here?

2022-09-14 06:49 UTC, violenil commented on now_executors/elastic_indexer/elastic_indexer.py
> +            "dims": 5,
Good question 😅 I think that was from one of my tests. Will change to 768.

2022-09-14 06:50 UTC, violenil commented on now_executors/elastic_indexer/elastic_indexer.py
> +            print("No embeddings extracted")
Good point, I guess we should raise an error if we assume by default there should be at least one embedding, and none are extracted.

2022-09-14 08:30 UTC, violenil commented on now_executors/elastic_indexer/elastic_indexer.py
> +            result = self.es.search(
Thanks for your suggestion @girishc13! I will take note of this multi-search api and perhaps we can use this in future. For now, I think this solution is sufficient. 

Can you suggest how to 'unmask' error from this search call though? That would be really helpful.

2022-09-14 08:49 UTC, girishc13 commented on now_executors/elastic_indexer/elastic_indexer.py
> +            result = self.es.search(
The method automatically raises one the errors specified [here](https://elasticsearch-py.readthedocs.io/en/v8.4.1/exceptions.html).

2022-09-16 08:20 UTC, violenil commented on now_executors/elastic_indexer/manifest.yml
> +keywords: [index, trivial]
Done.

2022-09-16 12:34 UTC, florian-hoenicke requested changes
Great implementation. I can not await to see this live. Good work.
The following things need to be done to have it work with the current apps:
- [ ] test-end-to-end should work with one of the apps.
- [x] ~cluster needs to be deployed (choose some cost-efficient deployment)~
  - using local deployment for now
- [x] ~serialize the whole document when indexing and retrieve it on search~
  - saving all parts of document as fields in index (dynamic mapping + chunk fields predefined)
- [x] remove embedding when indexing the documents
- [x] ~create a follow-up ticket for delete endpoint (deleting by tags)~
  - implemented in [7bfd1b5](https://github.com/jina-ai/now/pull/474/commits/7bfd1b57e65efc2dbe2d1e5d7af7786b6eae4d8e)

2022-09-29 15:00 UTC, joschkabraun commented on now_executors/elastic_indexer/tests/test_integration.py
> +def test_indexing(multimodal_da):
All tests of executors are now under `tests/now_executors/...` such that they will executed under CI

2022-09-29 15:01 UTC, joschkabraun commented on .github/workflows/ci.yml
> +      - name: Build and push executor
Similar to the other executors, I would execute the tests before building it.

2022-10-06 15:01 UTC, florian-hoenicke commented on now/apps/text_to_text_and_image/app.py
> +                    "kubectl",
custom kubectl path should be taken to have this run for users without kubectl installed

2022-10-06 15:07 UTC, florian-hoenicke commented on now_common/options.py
> +            # 'disabled': AVAILABLE_SOON,
needs to be disabled for now

2022-10-07 09:40 UTC, violenil commented on now/apps/text_to_text_and_image/app.py
> +                    "kubectl",
Have changed this in `utils.py` where this is called for the `text-to-text` app. Currently running the `text-to-text-and-image` app.

2022-10-07 15:37 UTC, joschkabraun reviewed
Some minor comments, otherwise LGTM :)

2022-10-07 15:37 UTC, joschkabraun commented on now/apps/text_to_text/flow-sbert.yml
> +      dims: ${{ ENV.N_DIM }}
I would suggest to add `dim` as well to keep backward compatability with AnnLite. Except for we are switching every app to Elasticsearch

2022-10-07 15:37 UTC, joschkabraun commented on now/apps/text_to_text/app.py
> ~
Is there a particular reason to only use `elastic` for the `text-to-text` app and not the others?

2022-10-07 15:37 UTC, joschkabraun commented on now_common/utils.py
> +    if elastic:
That is duplicate code to `setup` in `text_to_image_and_text`, I would suggest to put that into an own function

2022-10-07 15:37 UTC, joschkabraun commented on now_common/utils.py
> ~
Given that we not only get the indexer configuration but also spin up Elasticsearch, I would change it to `setup_indexer_get_config` or something similar.

2022-10-07 18:37 UTC, violenil commented on now/apps/text_to_text/app.py
> ~
I have not tested it with the other apps, plus the deployment can only run locally (not remote) so I have limited the use of this indexer to the text-to-text app for now. I also suspect there might be unforeseen errors that pop up when using this indexer with other apps. I think this can be tested/introduced in a separate (smaller) pr.

2022-10-07 19:09 UTC, violenil commented on now_common/utils.py
> +    if elastic:
True. I had separated the process of creating the `env_dict` for the text-to-text-and-image app from the common setup functions, and not considered that there are some overlaps. I have refactored this in [8ef8981](https://github.com/jina-ai/now/pull/474/commits/8ef8981094641ec63070375446d64170cda5cc9b)

2022-10-09 20:50 UTC, florian-hoenicke approved these changes

2022-10-09 20:51 UTC, merged