Fix local finetuning
jina-ai/now pull request #489
Opened 2022-09-09 12:38 UTC by makram93

When a finetune-enabled dataset is used to deploy locally, it fails to deploy pods for embedding creation. This fixes the namespace issue and also filters the data based on the output modality

2022-09-09 13:12 UTC, joschkabraun commented on now_executors/NOWPreprocessor/executor.py
> +        return self._preprocess_maybe_cloud_download(docs=docs, is_indexing=is_indexing)
I would suggest write a new endpoint & function which is called `encode` which concatenates the output of `index` and `search`. Introducing this `is_indexing` parameter is very confusing for someone calling the `index` endpoint.

2022-09-12 08:46 UTC, makram93 commented on now_executors/NOWPreprocessor/executor.py
> +        return self._preprocess_maybe_cloud_download(docs=docs, is_indexing=is_indexing)
I just realized that we do not need it as a param at all or to write a different function for `/encode` as the existing logic works fine. I wanted to parameterize it but I will revert this change.

2022-09-12 09:19 UTC, joschkabraun commented on now_executors/NOWPreprocessor/executor.py
> +        return self._preprocess_maybe_cloud_download(docs=docs, is_indexing=is_indexing)
What changed?
By latest changes in `main` we skip the this encoding step as we reuse precomputed `embedding` again.

2022-09-12 16:03 UTC, jupyterjazz approved these changes
LGTM!

2022-09-12 16:13 UTC, joschkabraun requested changes
Using this will remove any `input_modality` documents from the demo datasets and they will be disregarded in the finetuning. For the `text-to-image` app: This leads to the finetuned MLP to only see input samples of the fom (tensor, 0) (from images) but never (0, tensor) (from text). Therefore, the MLP which maps the text to the final embedding will be left with the initialized weights. I would suggest to
- implement `encode` endpoint in `NOWPreprocessor` to combine results form `index` and `search` endpoint

2022-09-13 12:28 UTC, makram93 commented
> Using this will remove any `input_modality` documents from the demo datasets and they will be disregarded in the finetuning. For the `text-to-image` app: This leads to the finetuned MLP to only see input samples of the fom (tensor, 0) (from images) but never (0, tensor) (from text). Therefore, the MLP which maps the text to the final embedding will be left with the initialized weights. I would suggest to
> 
> * implement `encode` endpoint in `NOWPreprocessor` to combine results form `index` and `search` endpoint

Thanks for the suggestion, it makes the code more readable. I have updated this PR accordingly

2022-09-13 13:00 UTC, joschkabraun approved these changes
Nice fix! LGTM :rocket:

2022-09-13 13:01 UTC, merged