fix #41
jina-ai/now pull request #51
Opened 2022-04-04 14:39 UTC by joschkabraun

still WIP

2022-04-04 16:24 UTC, florian-hoenicke submitted a review, later dismissed

2022-04-04 17:57 UTC, joschkabraun commented on now/cloud_manager.py
> +        out, err = cmd('docker images kindest/node')
I incorporated that which lead to the overloading `cmd` function to taking in lists as arguments as well. Otherwise the splitting of the command string lead to issues.

2022-04-05 06:56 UTC, florian-hoenicke commented on now/cloud_manager.py
> +        out, err = cmd('docker images kindest/node')
you could also use the python api. I think that would be the cleanest
https://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.list

2022-04-05 06:57 UTC, makram93 reviewed
Looks good. Some comments

2022-04-05 06:57 UTC, makram93 commented on now/deployment/deployment.py
> +            command, stdout=subprocess.PIPE, stderr=subprocess.PIPE
I think you should remove this `.split()` in else part too.

2022-04-05 06:57 UTC, makram93 commented on now/deployment/deployment.py
> +    if not isinstance(command, list):
```suggestion
    if isinstance(command, str):
```

2022-04-05 12:59 UTC, joschkabraun commented
Incorporated changes. Left in option to send list of commands to `cmd` as it seemed useful in the future.

2022-04-05 15:35 UTC, makram93 commented on now/cloud_manager.py
> +        kindest_images = docker.from_env().images.list('kindest/nod')
```suggestion
        kindest_images = docker.from_env().images.list('kindest/node')
```

2022-04-05 15:56 UTC, joschkabraun commented on now/cloud_manager.py
> +        kindest_images = docker.from_env().images.list('kindest/nod')
thank you!

2022-04-05 15:58 UTC, makram93 approved these changes
LGTM!

2022-04-06 07:48 UTC, florian-hoenicke requested changes
docker==5.0.3 has to be added to requirements_pip.txt

2022-04-06 08:02 UTC, florian-hoenicke approved these changes

2022-04-06 08:02 UTC, merged

2022-04-06 08:02 UTC, florian-hoenicke commented
Thanks. Nice first pr :)