feat: add autocomplete
jina-ai/now pull request #579
Opened 2022-10-11 07:36 UTC by azayz

2022-10-11 14:06 UTC, makram93 commented on tests/now_executors/NOWAutoCompleteExecutor/test_unit.py
> +            Document(text='fuck'),
Maybe you can code word this too, `f*ck` instead, just like `l3sbi4n`

2022-10-11 14:07 UTC, makram93 commented
Are we also planning to implement autocorrection of the search term as well?

2022-10-12 08:16 UTC, joschkabraun requested changes
If I understand your PR correctly, then the auto suggestion only works on completing a word given its beginning letters, is that correct? Can you extend that functionality to also include suggesting next words which are often follow the current one?

2022-10-12 08:33 UTC, azayz commented on now/apps/music_to_music/app.py
> +            super().setup(
it won't work if the flow_yaml isn't set

2022-10-12 08:33 UTC, azayz commented on now/apps/text_to_text_and_image/flow.yml
> +  - name: autocomplete_executor
good catch

2022-10-12 08:33 UTC, azayz commented on now/apps/text_to_video/flow-video-clip.yml
> +  - name: autocomplete_executor
good catch

2022-10-12 08:33 UTC, azayz commented on now/apps/text_to_video/flow-video-clip-high-performance.yml
> +  - name: autocomplete_executor
good catch

2022-10-12 08:33 UTC, azayz commented on now/apps/text_to_video/ft-flow-video-clip.yml
> +  - name: autocomplete_executor
good catch

2022-10-12 08:33 UTC, azayz commented on now/apps/text_to_video/ft-flow-video-clip-high-performance.yml
> +  - name: autocomplete_executor
good catch

2022-10-12 10:40 UTC, joschkabraun commented on now/apps/music_to_music/app.py
> +            super().setup(
flow yaml will be set in `common_setup`

2022-10-12 13:46 UTC, azayz commented on tests/now_executors/NOWAutoCompleteExecutor/test_unit.py
> +            Document(text='fuck'),
added

2022-10-17 08:32 UTC, girishc13 commented
I have two `suggestions`:

- From the api perspective limit the size of characters or words using a threshold. This will prevent issues due to crawling attacks or misuse of the api. It also doesn't make sense to provide suggestions for very long word or sentence.
- You can also use [this](https://github.com/minimaxir/big-list-of-naughty-strings) resource to improve the integration or e2e testing for the api.

2022-10-18 11:54 UTC, violenil reviewed
Left some questions, mostly for my own understanding :) Looks great!

2022-10-18 11:54 UTC, violenil commented on .github/workflows/ci.yml
> -    needs: [ update-preprocessor-if-required, update-qdrant-executor-if-required, update-bff-playground-if-required, update-elastic-executor-if-required]
How come these executor tests (for qdrant and elastic) are no longer run?

2022-10-18 11:54 UTC, violenil commented on deployment/bff/app/v1/routers/txt2video.py
> +    return docs.to_dict()
Does it make sense to have a 'base router' file that holds functions that all routers can use? To reduce the amount of duplicate code here.

2022-10-18 11:54 UTC, violenil commented on now/executor/autocomplete/executor.py
> +    def __init__(self, search_traversal_paths: str = '@r', words=None, *args, **kwargs):
are `words` usually of type `Dict`?

2022-10-18 11:54 UTC, violenil commented on now/executor/autocomplete/executor.py
> +                    if not NOWAutoCompleteExecutor.contains_profanity(word):
I think we should still allow users to search using some profane terms if they wish to, but we should not cache them or use them for our autocompletion. Are we disregarding profane words altogether? Just for my own understanding.

2022-10-18 13:13 UTC, azayz commented on deployment/bff/app/v1/routers/txt2video.py
> +    return docs.to_dict()
you mean a function where e put the `process_query` and `jina client post` functions

2022-10-18 13:17 UTC, azayz commented on deployment/bff/app/v1/routers/text2text.py
> +    "/suggestion",
how about `/autocomplete`

2022-10-20 07:07 UTC, makram93 commented on deployment/bff/app/v1/routers/txt2video.py
> +    return docs.to_dict()
This endpoint is limited to only `text` input modality, hence we can not add to base.

2022-10-20 07:37 UTC, makram93 reviewed
Overall looks good. Nice work. 
Are we going ahead with the playground changes for now and incorporate the custom components as and when it is ready?

2022-10-20 07:37 UTC, makram93 commented on deployment/playground/src/search.py
> +def get_suggestion(text, jwt):
Maybe you can omit this function and reuse the search function adding an additional param to it `endpoints` which specifies the host end?
```suggestion
def get_suggestion(text, jwt, endpoint='search'):
.
.
.
URL_HOST = = f"{domain}/api/v1/{params.input_modality}-to-{params.output_modality}/{endpoints}"
```

2022-10-20 07:37 UTC, makram93 commented on now/executor/autocomplete/executor.py
> +            if doc.text and not NOWAutoCompleteExecutor.contains_profanity(doc.text):
`contains_profinity` returns True if it contains some profanity right? Then shouldn't this check be? :
```suggestion
            if doc.text and NOWAutoCompleteExecutor.contains_profanity(doc.text):
```

2022-10-20 07:39 UTC, makram93 commented on now/executor/autocomplete/executor.py
> +            if doc.text and not NOWAutoCompleteExecutor.contains_profanity(doc.text):
Ah okay, never mind. I got what this is doing. So you add the searched words if it is not profane one.

2022-10-20 09:03 UTC, azayz commented on deployment/playground/src/search.py
> +def get_suggestion(text, jwt):
applied

2022-10-20 09:57 UTC, violenil commented on now/executor/autocomplete/executor.py
> +                    if not NOWAutoCompleteExecutor.contains_profanity(word):
Great!

2022-10-20 11:06 UTC, violenil commented on docs/user-guides/production.md
> +For aplications with Text as a modality input, we provide `autocomplete` feature. This feature learns slowly from your users's search requests
```suggestion
For applications with Text as input modality, we provide the `autocomplete` feature. This feature learns slowly from the user's search requests
```

2022-10-20 12:42 UTC, azayz commented
![Screenshot from 2022-10-20 13-40-15](https://user-images.githubusercontent.com/40893766/196951488-7bd5e7c2-1a7b-4933-8e3d-8cedb52b14b7.png)

2022-10-20 12:42 UTC, azayz commented on docs/user-guides/production.md
> +For aplications with Text as a modality input, we provide `autocomplete` feature. This feature learns slowly from your users's search requests
Thanks, applied

2022-10-24 11:45 UTC, joschkabraun commented on deployment/bff/app/v1/routers/txt2video.py
> +    return docs.to_dict()
Once we refactor bff into the apps, we should do that by checking in the baseclass if `input_modality == 'text'`

2022-10-24 11:57 UTC, joschkabraun approved these changes
LGTM! Some minor comments.

2022-10-24 11:57 UTC, joschkabraun commented on docs/user-guides/production.md
> +For applications with Text as input modality, we provide the `autocomplete` feature. This feature learns slowly from the user's search requests
text is lower case

2022-10-24 11:57 UTC, joschkabraun commented on now/executor/autocomplete/executor.py
> +        self.words = words if words else {}
We should persist `words` to the workspace similar to how the authentication executor does it with any secrets. The issue is we lose the state if the executor restarts.

2022-10-24 11:57 UTC, joschkabraun commented on now/executor/autocomplete/executor.py
> +        self.auto_complete = AutoComplete(words=self.words)
What's the introduced latency of that object creation for a very large corpus? Do you have any numbers on how long that takes for words to contain millions of words?

2022-10-24 11:57 UTC, joschkabraun commented on now/executor/autocomplete/requirements.txt
> +Levenshtein==0.20.5
do we use levenhstein requirements?

2022-10-24 11:57 UTC, joschkabraun commented on now/executor/autocomplete/executor.py
> +            if doc.text and not NOWAutoCompleteExecutor.contains_profanity(doc.text):
Given that `contains_profanity` is only one line of code, I don't think we need an extra function for that.

2022-10-24 11:57 UTC, joschkabraun commented on requirements-test.txt
> +python-Levenshtein==0.20.5
do we use levenhstein requirements?

2022-10-25 09:49 UTC, azayz commented on now/executor/autocomplete/requirements.txt
> +Levenshtein==0.20.5
yes it's needed for levenshtein python

2022-10-25 09:50 UTC, azayz commented on requirements-test.txt
> +python-Levenshtein==0.20.5
yes needed for fast autocomplete, I tried removing and I got errors

2022-10-25 15:08 UTC, florian-hoenicke commented on .github/workflows/ci.yml
>        - name: Set up Python 3.7
Please add test run for Autocomplete

2022-10-25 15:17 UTC, florian-hoenicke commented on now/executor/abstract/base_indexer/base_indexer.py
> +                if not (
Maybe it is not needed anymore? Or can be fixed at another level in another pr

2022-10-25 16:23 UTC, florian-hoenicke requested changes
The fixes for tags can be done in a separated pr to have it handled in the right way

2022-10-26 08:16 UTC, azayz commented
![Screenshot from 2022-10-26 09-15-30](https://user-images.githubusercontent.com/40893766/197972442-41367e69-fb3a-49ec-b613-ea66ce15a0ec.png)
![Screenshot from 2022-10-26 09-14-57](https://user-images.githubusercontent.com/40893766/197972447-c7077b47-69a6-4dac-90a3-5d14d86f9428.png)

2022-10-27 10:22 UTC, makram93 commented
@azayz Can we move the `search` button to align with the search bar? You can use columns to keep them side-by-side. This way we can move the suggestion up to be close to the search bar.

2022-10-27 11:12 UTC, violenil approved these changes
LGTM! Good job 🚀

2022-10-27 11:40 UTC, florian-hoenicke approved these changes
Well done. This is a big feature!

2022-10-27 11:40 UTC, merged