test: run multimodal demo in end-to-end-tests
jina-ai/now pull request #597
Opened 2022-10-17 11:00 UTC by violenil

2022-10-17 13:00 UTC, florian-hoenicke commented on now/app/text_to_text_and_image/flow.yml
> +    is_onnx: True
why is this flag needed? Can we do without?

2022-10-17 13:02 UTC, violenil commented on now/app/text_to_text_and_image/flow.yml
> +    is_onnx: True
We are using an onnx model artifact, without this flag the executor cant be loaded. Perhaps we can use a pytorch model instead (this is supported with FinetunerExecutor)

2022-10-20 08:01 UTC, azayz commented on now/app/text_to_text_and_image/app.py
> +        env_dict['HOSTS'] = indexer_config.get('hosts')
why get ?

2022-10-20 08:01 UTC, azayz commented on now/app/text_to_text_and_image/app.py
> +        finetune_settings.train_val_split_ration = 0.75
any reason for this change ?

2022-10-20 12:23 UTC, violenil commented on now/app/text_to_text_and_image/app.py
> +        finetune_settings.train_val_split_ration = 0.75
yes because the test split was too small for finetuner, I think it was only 30 instances, while finetuner requires a minimum 32 samples to make batch.

2022-10-20 12:29 UTC, violenil commented on now/app/text_to_text_and_image/app.py
> +        env_dict['HOSTS'] = indexer_config.get('hosts')
this will handle errors better, while fetching a key like `dict[key]` will throw a KeyError

2022-10-20 12:32 UTC, violenil commented on deployment/bff/app/v1/models/text_and_image.py
> +NowTextAndImageResponseModel.update_forward_refs()
I am not sure, honestly. The `NowImageResponseModel` has this too, so that is why I made sure to include this call too.

2022-11-07 08:14 UTC, azayz commented on .test_durations
> +    "tests/integration/data_loading/test_demo_datasets.py::test_dataset_is_available[text-and-image-extracted-data-online-shop-50-flat]": 0.20864115236327052,
just out of curiosity why does this have to change ?

2022-11-07 08:14 UTC, azayz commented on deployment/bff/app/v1/routers/text2text.py
> +        parameters={'limit': data.limit, 'filter': filter_query, 'apply_bm25': True},
I think the apply_bm25 is not needed for this endpoint

2022-11-07 08:14 UTC, azayz commented on now/executor/indexer/elastic/elastic_indexer.py
> +        docs.summary()
these were used for debugging so you can remove

2022-11-07 08:18 UTC, violenil commented on .test_durations
> +    "tests/integration/data_loading/test_demo_datasets.py::test_dataset_is_available[text-and-image-extracted-data-online-shop-50-flat]": 0.20864115236327052,
I changed the formatting of the output modality (changed underscores to dashes because underscores are not permitted in URLs) and so this test naming also changed.

2022-11-07 08:23 UTC, violenil commented on tests/unit/test_finetuning/test_run_finetuning.py
> +    # assert settings.perform_finetuning
Currently, the text-to-text-and-image app has finetuning disabled, so it cannot be tested. Finetuning is disabled for this app because FinetunerExecutor currently does not support `access_paths`, which are required for encoding nested documents (inherently the data structure of `text-to-text-and-image` app).

2022-11-07 10:49 UTC, violenil commented on deployment/bff/app/v1/routers/text2text.py
> +        parameters={'limit': data.limit, 'filter': filter_query, 'apply_bm25': True},
Although it is not strictly necessary, I think it is quite a nice feature to allow for text-to-text search, since this is one of the few applications with input+output modality that allow bm25 scoring. So I think we should keep it :) 
If an indexer is used (eg. Qdrant) that does not support bm25 scoring, it will just ignore this parameter anyway.

2022-11-07 10:53 UTC, jupyterjazz reviewed
Great work! :rocket: :partying_face:

left some minor comments

2022-11-07 10:53 UTC, jupyterjazz commented on now/app/text_to_text/flow-sbert.yml
> +    disable_reduce: true
what's `disable_reduce`?

2022-11-07 10:53 UTC, jupyterjazz commented on now/app/text_to_text_and_image/app.py
> +        )
if you want to avoid `KeyError` and return `None` if there's no indexer resources:
```suggestion
        env_dict['INDEXER_MEM'] = indexer_config.get('indexer_resources', {}).get(
            'INDEXER_MEM'
        )
```

2022-11-07 10:53 UTC, jupyterjazz commented on now/app/text_to_text_and_image/app.py
> +        env_dict['N_DIM'] = [768, 512]
would be nice to have constants for the dimensions

2022-11-07 10:53 UTC, jupyterjazz commented on now/executor/indexer/elastic/elastic_indexer.py
> +        docs[0].summary()
these summaries should also be removed

2022-11-07 10:53 UTC, jupyterjazz commented on now/executor/indexer/elastic/elastic_indexer.py
> +        doc: Document, traversal_paths: str
instead of 
`if 'r' in traversal_paths:
`
why not `traversal_paths == '@r'`

2022-11-07 10:53 UTC, jupyterjazz commented on now/executor/indexer/elastic/elastic_indexer.py
> +        doc: Document, traversal_paths: str
this might cause some problems in the future when traversal paths will contain field names..

2022-11-07 10:53 UTC, jupyterjazz commented on now/executor/indexer/elastic/elastic_indexer.py
> +                    c for c in doc2.chunks if c.uri is not None and c.uri != ''
I think this could also work?
```suggestion
                    c for c in doc1.chunks if c.text
                ]  # doc1 from SBert with text embedding
                image_chunks = [
                    c for c in doc2.chunks if c.uri
```

2022-11-07 10:53 UTC, jupyterjazz commented on tests/executor/indexer/elastic/conftest.py
> +                    Document(uri='https://jina.ai'),  # not encoded by SBERT
why are we passing 'https://jina.ai' as an uri?

2022-11-07 10:53 UTC, jupyterjazz commented on tests/unit/data_loading/test_data_loading.py
> +            assert c.text is not None or c.uri is not None
```suggestion
            assert c.text or c.uri
```

2022-11-07 12:19 UTC, violenil commented on now/app/text_to_text/flow-sbert.yml
> +    disable_reduce: true
This parameters allows an executor to gather results (or DocumentArrays) from multiple previous executors (specified with `needs`), ie. it gets a `docs_matrix` consisting of a list of DocumentArrays, where each DocumentArray comes from a different executor. If this parameter is not set, the Indexer only receives output from the last executor in the `needs` parameter.

2022-11-07 12:19 UTC, violenil commented on now/app/text_to_text_and_image/app.py
> +        env_dict['N_DIM'] = [768, 512]
Good idea!

2022-11-07 12:23 UTC, violenil commented on now/executor/indexer/elastic/elastic_indexer.py
> +        doc: Document, traversal_paths: str
The traversal path could contain 'r' as well as 'c', for example '@r,c' in which case this condition would not hold. We will need to refactor this in the future when traversal paths contain field names. But I don't think  `traversal_paths == '@r'` solves this issue for now.

2022-11-07 12:24 UTC, violenil commented on tests/executor/indexer/elastic/conftest.py
> +                    Document(uri='https://jina.ai'),  # not encoded by SBERT
Will replace with random but realistic uri.

2022-11-07 13:30 UTC, violenil commented on now/executor/indexer/elastic/elastic_indexer.py
> +                    c for c in doc2.chunks if c.uri is not None and c.uri != ''
Done.

2022-11-07 13:30 UTC, violenil commented on now/executor/indexer/elastic/elastic_indexer.py
> +        docs[0].summary()
Done.

2022-11-07 13:31 UTC, violenil commented on now/app/text_to_text_and_image/app.py
> +        env_dict['N_DIM'] = [768, 512]
Done.

2022-11-07 13:31 UTC, violenil commented on now/app/text_to_text_and_image/app.py
> +        )
Done.

2022-11-07 13:32 UTC, violenil commented on tests/unit/data_loading/test_data_loading.py
> +            assert c.text is not None or c.uri is not None
Done.

2022-11-07 13:48 UTC, violenil commented on deployment/bff/app/v1/routers/txt2txt_and_img.py
> +    for text, image, uri, tags in zip(data.texts, data.images, data.uris, data.tags):
> this will error if they don't have same length

That would be expected, as we expect these to have the same length.

2022-11-07 16:28 UTC, joschkabraun requested changes
Really great work! :rocket:
Some small comments

2022-11-07 16:28 UTC, joschkabraun commented on now/executor/indexer/elastic/elastic_indexer.py
> +                docs = self._join_docs_matrix_into_chunks(
Is now `docs_matrix` deterministic?

2022-11-07 16:28 UTC, joschkabraun commented on now/executor/indexer/elastic/elastic_indexer.py
> +            else:
this doesn't work with documents for which we directly uploaded `blob` instead of `uri`

2022-11-07 16:28 UTC, joschkabraun commented on deployment/bff/app/v1/routers/text2text.py
> +        parameters={'limit': data.limit, 'filter': filter_query, 'apply_bm25': True},
Why do we need `apply_bm25`, `limit` and `filter` for the `suggestion` endpoint?

2022-11-07 16:28 UTC, joschkabraun commented on deployment/bff/app/v1/routers/text2text.py
> +        parameters={'limit': data.limit, 'filter': filter_query, 'apply_bm25': True},
For remote deployment for `text2text` we use Qdrant, right? I assume `apply_bm25` will then simply be ignored, right?

2022-11-07 16:28 UTC, joschkabraun commented on now/app/text_to_text_and_image/pretrained_flow.yml
> +      memory: 4G
Are `4G` actually needed? E.g. `text2video` uses `1G`

2022-11-07 16:28 UTC, joschkabraun commented on now/common/options.py
> -            'disabled': AVAILABLE_SOON,
Wuhu!!

2022-11-07 16:28 UTC, joschkabraun commented on now/common/preprocess.py
> ~            return to_thumbnail_jpg(d)
Can be simplified to `if d.text`

2022-11-07 16:28 UTC, joschkabraun commented on now/common/preprocess.py
> ~    for d in da:
Can be simplified to `if d.text`

2022-11-07 16:28 UTC, joschkabraun commented on now/common/utils.py
> ~        config['FINETUNE_ARTIFACT'] = finetune_settings.finetuned_model_artifact
Doesn't that deactivate the `text2text` app remotely?

2022-11-07 16:33 UTC, joschkabraun commented on now/common/utils.py
> +            'ElasticIndexer is currently not supported for remote deployment. Please use local deployment.'
Doesn't that deactivate the `text2text` app remotely?

2022-11-07 16:33 UTC, joschkabraun commented on now/common/preprocess.py
> +        if d.text and d.text != '':
Can be simplified to if `d.text`

2022-11-07 16:45 UTC, florian-hoenicke commented on now/common/options.py
> -            'disabled': AVAILABLE_SOON,
🥳 🥳 🥳

2022-11-07 16:54 UTC, florian-hoenicke commented on now/app/text_to_text_and_image/flow.yml
> +    /search: encode
is it still necessary to define these two endpoints or can we also do without?

2022-11-08 07:55 UTC, violenil commented on now/executor/indexer/elastic/elastic_indexer.py
> +                docs = self._join_docs_matrix_into_chunks(
When I was implementing this, only one app was passing a `docs_matrix` to the indexer, which is the multimodal app with multiple encoders. In this sense, I was assuming that this `docs_matrix` would be deterministic, and also assumed a strict order for the DocumentArrays in the `docs_matrix`. Now that I have looked at [your PR](https://github.com/jina-ai/now/pull/601) I realize this may not be the case if OCR is enabled. 
Can you think of a way to better structure this?

2022-11-08 07:59 UTC, violenil commented on now/app/text_to_text_and_image/flow.yml
> +    /search: encode
It is not necessary, though this flow.yml is not currently used in the app. It would be used again when finetuning is enabled for text-to-text-and-image, and these endpoints (and also the whole yml) can then be refactored.

2022-11-08 08:03 UTC, violenil commented on now/app/text_to_text_and_image/pretrained_flow.yml
> +      memory: 4G
Ah ok, I was not sure what would be needed. I will amend this :)

2022-11-08 08:03 UTC, violenil commented on deployment/bff/app/v1/routers/text2text.py
> +        parameters={'limit': data.limit, 'filter': filter_query, 'apply_bm25': True},
Indeed! Should just be ignored.

2022-11-08 08:04 UTC, violenil commented on deployment/bff/app/v1/routers/text2text.py
> +        parameters={'limit': data.limit, 'filter': filter_query, 'apply_bm25': True},
The app was failing when I had not passed these parameters also to the suggestion endpoint. I cannot remember the reason exactly, will take another look.

2022-11-08 08:25 UTC, azayz approved these changes
LGTM after comments above

2022-11-08 08:35 UTC, joschkabraun commented on now/common/utils.py
> +            'ElasticIndexer is currently not supported for remote deployment. Please use local deployment.'
But isn't `elastic=True` in `setup` for `text2text`?

2022-11-08 12:50 UTC, violenil commented on now/executor/indexer/elastic/elastic_indexer.py
> +            else:
Would it make sense to check the `modality` or `mime_type` instead?

2022-11-08 12:53 UTC, violenil commented on now/common/utils.py
> +            'ElasticIndexer is currently not supported for remote deployment. Please use local deployment.'
Changing this default to `elastic=False`

2022-11-08 14:25 UTC, violenil commented on now/app/text_to_text_and_image/flow.yml
> +    /search: encode
I have refactored this in anticipation of enabling finetuning again in this app in a future PR :)

2022-11-08 15:25 UTC, violenil commented on now/executor/indexer/elastic/elastic_indexer.py
> +                docs = self._join_docs_matrix_into_chunks(
We can do some refactoring on this once core find a solution to [this issue](https://github.com/jina-ai/jina/issues/5330).

2022-11-09 12:23 UTC, merged