Fix add sync
jina-ai/now pull request #627
Opened 2022-10-31 08:39 UTC by makram93

2022-10-31 12:41 UTC, florian-hoenicke commented on tests/integration/test_end_to_end.py
> +        'api_key': False,
should it be None as default value?

2022-10-31 12:43 UTC, florian-hoenicke commented on tests/integration/test_end_to_end.py
> +        'api_key': False,
ah okay, nevermind. I got it. It is a boolean asking if they want to secure it via api_key

2022-10-31 12:43 UTC, joschkabraun reviewed
Nice PR! Some minor comments

2022-10-31 12:43 UTC, joschkabraun commented on now/common/options.py
> +    ],
I would not let it check that the user has set the api key. Otherwise other users don't have access to the playground without extra calling the flow again

2022-10-31 12:43 UTC, joschkabraun commented on now/common/options.py
> @@ -312,8 +327,8 @@
Did you mean `if not user_input.api_key:`?

2022-10-31 12:43 UTC, joschkabraun commented on now/common/options.py
> @@ -312,8 +327,8 @@
Did you mean `if not user_input.api_key`?

2022-10-31 12:43 UTC, joschkabraun commented on now/common/options.py
> +    prompt_message='Do you want to generate an api_key to access this deployment?',
I think we can change `'value'` to `uuid.uuid4().hex` for `True` and to `None` for `False`. Then we don't need to set it to bool.

2022-10-31 12:43 UTC, joschkabraun commented on now/now_dataclasses.py
> +    api_key: Optional[Union[StrictBool, str]] = None
By comment in `options.py` we can remove type `StrictBool`

2022-10-31 15:28 UTC, florian-hoenicke commented
<img width="574" alt="image" src="https://user-images.githubusercontent.com/11627845/199045669-c61c1a9c-c75d-4256-b7a9-e8f5b453c070.png">
I don't get asked anymore if I want to specify email addresses

2022-10-31 15:28 UTC, florian-hoenicke requested changes

2022-10-31 16:12 UTC, makram93 commented on now/common/options.py
> +    prompt_message='Do you want to generate an api_key to access this deployment?',
Nice idea

2022-10-31 16:12 UTC, makram93 commented on now/common/options.py
> +    ],
Can you elaborate what you mean about the users making an extra call to the flow?

2022-10-31 16:13 UTC, makram93 commented on tests/integration/test_end_to_end.py
> +        'api_key': False,
Updated it

2022-11-01 04:38 UTC, joschkabraun commented on now/common/options.py
> +    ],
It's similar to what Florian said that one doesn't get asked anymore about adding user emails. One would have to update user emails after program termination.

2022-11-01 04:50 UTC, joschkabraun approved these changes
Minor comments, then LGTM!

2022-11-01 04:50 UTC, joschkabraun commented on now/common/options.py
> ~
it's API key

2022-11-01 04:50 UTC, joschkabraun commented on now/run_backend.py
> +        user_input.api_key = uuid.uuid4().hex
I would add a print out to let the user know that this is the API key. For the case that they update the api keys in the future, they will need to keep that one for the sync job.

2022-11-01 04:50 UTC, joschkabraun commented on now/run_backend.py
> +        update_api_keys(user_input.deployment_type, user_input.api_key, host)
We need to let this run as a for loop for now in order to ensure every replica of an executor receives the updated API keys if we have multiple replicas of the same executor.

2022-11-01 04:50 UTC, joschkabraun commented on tests/integration/test_end_to_end.py
> +        'api_key': False,
I would change it to `None`

2022-11-01 08:18 UTC, makram93 commented on now/run_backend.py
> +        user_input.api_key = uuid.uuid4().hex
Yes at the end this will be printed along with playground & bff url

2022-11-03 10:47 UTC, makram93 commented on now/app/music_to_music/demo-data-flow-music.yml
> +      api_keys: ${{ ENV.API_KEY }}
Nice suggestion! Have updated my code

2022-11-03 14:48 UTC, azayz approved these changes
LGTM

2022-11-07 08:23 UTC, merged