fix: add timeout
jina-ai/now pull request #630
Opened 2022-10-31 18:08 UTC by azayz

2022-11-03 10:26 UTC, makram93 requested changes
Some minor changes, otherwise it looks good.

2022-11-03 10:26 UTC, makram93 commented on deployment/playground/playground.py
> +                        match.load_uri_to_text(timeout=10)
The version needs to be updated in the playground as well. Make sure it is not failing after the version upgrade by doing local tests and opening streamlit

2022-11-03 10:26 UTC, makram93 commented on deployment/playground/src/search.py
> +            query_doc.load_uri_to_blob(timeout=10)
Does it throw an error on timeout or just suppress it and continue the execution?

2022-11-03 10:26 UTC, makram93 commented on deployment/playground/src/search.py
> +            query_doc.load_uri_to_blob(timeout=10)
Also, I would suggest reducing the timeout value.... maybe to 5? It will greatly factor in indexing large datasets with lots of invalid urls

2022-11-03 12:50 UTC, jupyterjazz reviewed
Do we have some experimentation results? i.e. how this change affected speed of indexing certain datasets

2022-11-03 13:05 UTC, azayz commented on deployment/playground/src/search.py
> +            query_doc.load_uri_to_blob(timeout=10)
I believe 5 is too fast, I think this is also a tradeoff of how fast you want to index your data vs how incomplete your indexed data will be, I believe having complete indexed data is more important than speed, what do you think ?

2022-11-03 14:50 UTC, azayz commented on deployment/playground/src/search.py
> +            query_doc.load_uri_to_blob(timeout=10)
surpress and continue the execution

2022-11-03 14:52 UTC, azayz commented on deployment/playground/src/search.py
> +            query_doc.load_uri_to_blob(timeout=10)
throws an error 
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out 

do you think this might be problematic ?

2022-11-03 14:54 UTC, makram93 commented on deployment/playground/src/search.py
> +            query_doc.load_uri_to_blob(timeout=10)
If it throws an error and terminates the program then we should add it in try-except block so as to continue with other docs

2022-11-03 14:54 UTC, makram93 commented on deployment/playground/src/search.py
> +            query_doc.load_uri_to_blob(timeout=10)
Okay 👍

2022-11-03 15:05 UTC, azayz commented on deployment/playground/src/search.py
> +            query_doc.load_uri_to_blob(timeout=10)
I see but the indexing continues when I tried it, I think this is because I added continue on error argument in indexing

2022-11-03 20:46 UTC, azayz commented on deployment/playground/playground.py
> +                        match.load_uri_to_text(timeout=10)
I tested locally with text to image with cars dataset and playground works fine

2022-11-06 22:06 UTC, florian-hoenicke approved these changes
LGTM

2022-11-06 22:08 UTC, florian-hoenicke commented
> Do we have some experimentation results? i.e. how this change affected speed of indexing certain datasets

@jupyterjazz It will only have positive effects. Before, it was not timing out and led to permanent blocking of the indexing process.

2022-11-06 22:09 UTC, merged