refactor: converge image-text apps
jina-ai/now pull request #669
Opened 2022-11-15 08:56 UTC by makram93

2022-11-18 14:13 UTC, azayz commented on now/common/flow/flow-clip.yml
> +  - name: autocomplete_executor
I assume you accidently added this file into the commit

2022-11-20 23:56 UTC, makram93 commented on deployment/bff/app/app.py
>      text2text,
No, it will be removed in the second iteration because text2text uses SBERT model as opposed to CLIP

2022-11-20 23:56 UTC, makram93 commented on deployment/bff/app/app.py
> +    im_txt2im_txt_mount = '/api/v1/image-and-text-to-image-and-text'
Yes, good idea. Will do!

2022-11-21 00:04 UTC, makram93 commented on deployment/bff/app/v1/routers/txt2video.py
> +    for video, uri, tags in zip_longest(data.videos, data.uris, data.tags):
Zip ends at the shortest iterator. zip_longest() will go through all entries, and if one of the iterators runs out early, it gets replaced with None

2022-11-21 00:04 UTC, makram93 commented on now/common/flow/flow-clip.yml
> +  - name: autocomplete_executor
Ah yes, nice catch

2022-11-22 08:10 UTC, florian-hoenicke requested changes

2022-11-22 08:10 UTC, florian-hoenicke commented on tests/integration/test_end_to_end.py
> +        'secured': False,
why is this set to false? Is the test failing if you make secured deployments?

2022-11-22 08:16 UTC, azayz commented on deployment/bff/app/v1/routers/im_txt2im_txt.py
> +    response_model=List[NowTextAndImageResponseModel],
I would say directly nale this to TextImageResponseModel because the use of `And` kinda implies that both modalities are necessary

2022-11-22 08:26 UTC, azayz commented on now/app/text_to_text_and_image/app.py
> +        is_indexing: bool = False,
why is this added ? this was removed in Saba's PR and was replaced by process_index

2022-11-22 08:36 UTC, florian-hoenicke commented
I tried to index 10 documents with tags but I get a not found error:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/11627845/203264398-c51fe3e8-82ac-4ca6-ad13-735c8a338446.png">

```python
?? What sort of search engine would you like to build?  📝+🏞 ▶ 📝+🏞 image-text retrieval
?? What is the output modality of your image-text retrieval system?  🏞 image
? Choose a name for your application:
? How do you want to provide input? (format: https://docarray.jina.ai/)  Local folder
? Please enter the path to the local folder:  /Users/florianhonicke/Downloads/lottiefiles/10
? Enter comma-separated search fields:
? Where do you want to deploy your search engine?  ⛅️ Jina Cloud
? Do you want to secure the flow?  ✅ yes
? Do you want to generate an api_key to access this deployment?  ✅ yes
? Do you want to provide additional users access to this flow?  ⛔ no
💿  Loading files from disk
🏭 Loading data from folder

[...]

[11/22/22 09:28:16] DEBUG    Successfully reached status: ALIVE with gateway grpcs://nowapi-d593d3e20b.wolf.jina.ai                                                                                                                      flow.py:293
╭───────────────── 🎉 Flow is available! ──────────────────╮
│                                                          │
│   ID            d593d3e20b                               │
│   Endpoint(s)   grpcs://nowapi-d593d3e20b.wolf.jina.ai   │
│                                                          │
╰──────────────────────────────────────────────────────────╯
▶ indexing 11 documents
  DONE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:11 100% ETA: 0:00:00 1 steps done in 11 seconds
⭐ Success - your data is indexed

╭──────────────────────────────────────────────────────── 🎉 ['image', 'text']-['image', 'text'] app is NOW ready! ────────────────────────────────────────────────────────╮
│                                                                                                                                                                          │
│   Api docs     https://nowrun.jina.ai/api/v1/image-or-text-to-image-or-text/docs                                                                                         │
│   API Key      cc6d74b11008491199af7930d2055594                                                                                                                          │
│   Playground   https://nowrun.jina.ai/?host=grpcs://nowapi-d593d3e20b.wolf.jina.ai&input_modality=image-or-text&output_modality=image-or-text&data=custom&secured=True   │
│                                                                                                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


```

2022-11-22 09:10 UTC, makram93 commented on tests/integration/test_end_to_end.py
> +        'secured': False,
No, it was just for debugging purposes. I will enable this

2022-11-22 09:11 UTC, makram93 commented on now/app/text_to_text_and_image/app.py
> +        is_indexing: bool = False,
Oh okay, then I have to adapt the test cases. Thanks for pointing this out

2022-11-22 09:57 UTC, joschkabraun requested changes
Nice refactoring! I think we can push it even further in this step to make the `app` concept disappear from the CLI.

2022-11-22 09:57 UTC, joschkabraun commented on deployment/bff/app/v1/routers/im_txt2im_txt.py
> +        if bool(text) + bool(uri) > 1:
all the if statements can be put into one statement

2022-11-22 09:57 UTC, joschkabraun commented on deployment/bff/app/v1/routers/txt2video.py
> +    for video, uri, tags in zip_longest(data.videos, data.uris, data.tags):
why is `zip_longest` now needed?

2022-11-22 09:57 UTC, joschkabraun commented on now/admin/deploy_text_to_video.py
> +app = Apps.IMAGE_TEXT_RETRIEVAL
we can actually remove `app` from this file as it isn't used AFAIK

2022-11-22 09:57 UTC, joschkabraun commented on now/common/options.py
> +        {'name': '📝 ▶ 📝 text to text search (SBERT)', 'value': Apps.TEXT_TO_TEXT},
I would remove `(SBERT)` as the user doesn't care about that

2022-11-22 09:57 UTC, joschkabraun commented on now/common/options.py
> +    depends_on=APP,
To be more aligned with the future refactoring, I think we can already remove the app question. By
1. ask for output modality (image, text, image_and_text, music, video)
2. ask for input modality (which will be adjusted depending on output modality)
Then in the code internally we can create the appropriate app.

2022-11-22 09:57 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +        output_modality = user_input.output_modality or app.output_modality
why is the `or` needed? Shouldn't `user_input.output_modality` suffice?

2022-11-22 09:57 UTC, joschkabraun commented on now/executor/preprocessor/executor.py
> +        """If necessary downloads data from cloud bucket. Applies preprocessing to document as defined by apps.
I think plural is correct as we process multiple documents during `index` typically, right?

2022-11-22 09:57 UTC, joschkabraun commented on tests/integration/test_end_to_end.py
> -            'local',
Should we add the test back or was there a reason to remove it?

2022-11-22 09:57 UTC, joschkabraun commented on tests/unit/apps/test_preprocessing.py
> -# def test_music_preprocessing(is_indexing, resources_folder_path):
I think `test_music_preprocessing` was only temporary disabled by Saba's PR as his PR doens't work with it

2022-11-22 12:02 UTC, makram93 commented on deployment/bff/app/v1/routers/txt2video.py
> +    for video, uri, tags in zip_longest(data.videos, data.uris, data.tags):
For indexing, we accept a list of images/uris/tags and if the user does not pass tags but only the uris then `zip` won't iterate through all of them as it only executes till the shortest length

2022-11-22 12:26 UTC, makram93 commented on now/executor/preprocessor/executor.py
> +        """If necessary downloads data from cloud bucket. Applies preprocessing to document as defined by apps.
Pycharm told me this: `The verb after "to" should be in the base form.` therefore I changed XD
Will put s back

2022-11-22 12:28 UTC, makram93 commented on now/data_loading/data_loading.py
> +        output_modality = user_input.output_modality or app.output_modality
`user_input.output_modality` depends on the apps and will only be set when the user selects the image-text retrieval app. In other cases, this will be none and the output modality can be taken directly from the app, hence the use of `or`

2022-11-22 12:29 UTC, makram93 commented on now/common/options.py
> +    depends_on=APP,
I think it is a good idea. But I would try to achieve this in the second iteration. This PR is already large and removing the usage of `app` will need refactoring in a lot of places, especially in test cases.

2022-11-22 12:39 UTC, makram93 commented on tests/unit/apps/test_preprocessing.py
> -# def test_music_preprocessing(is_indexing, resources_folder_path):
Yes, this change exists in the main branch itself

2022-11-22 14:24 UTC, makram93 commented
> Did you try to make deployments manually?

Yes I did and it works. For local testing you will have to run the playground and the bff locally first and also change `domain` to local bff. SInce these changes are introduced in this PR it is not yet available on `nowrun.jina.ai` 
![image](https://user-images.githubusercontent.com/6537525/203338583-4a9fcbba-a485-4454-bf0d-b0c8643d1bab.png)

2022-11-22 14:27 UTC, joschkabraun commented on now/common/options.py
> +    depends_on=APP,
Actually for those changes they only really touch the dialog and maybe a few tests. But you are right, the PR is already large, such that we can also tackle that in the next PR.

2022-11-22 14:30 UTC, joschkabraun commented on tests/unit/apps/test_preprocessing.py
> -# def test_music_preprocessing(is_indexing, resources_folder_path):
Yes, so I would add it back as it should be reactivated in a future PR. I would simply add `@pytest.mark.skip(reason="Temporarily deactivated until music2music app is reactivated.")`

2022-11-22 14:32 UTC, joschkabraun commented on tests/integration/test_end_to_end.py
> -            'local',
You are right we test different deployment options. But currently we only test `text-to-image` and `image-to-text`. But we don't test `image-to-image`.

2022-11-22 14:40 UTC, makram93 commented on tests/integration/test_end_to_end.py
> -            'local',
Will add that test

2022-11-22 14:55 UTC, florian-hoenicke commented
I get the following error:
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/11627845/203345962-e6f9036e-51db-4361-b0e6-6fa44ca94d32.png">

2022-11-23 15:29 UTC, merged