feat: add migration to jcloud
jina-ai/now pull request #674
Opened 2022-11-16 13:38 UTC by azayz

2022-11-16 13:59 UTC, deepankarm requested changes
https://github.com/jina-ai/now/blob/e2702669a7d48f4522629edd98e709712712563a/now/deployment/deployment.py#L9

:point_up: needs update as `name` and `env_file` are not supported anymore.

2022-11-21 15:42 UTC, joschkabraun approved these changes
LGTM!

2022-11-21 15:42 UTC, joschkabraun commented on requirements.txt
>  requests==2.27.1
why are we not using jina version 3.9.4 here

2022-11-22 07:57 UTC, azayz commented on requirements.txt
>  requests==2.27.1
you're right I missed this

2022-11-22 08:40 UTC, deepankarm approved these changes
:+1:

2022-11-22 08:44 UTC, merged