Refactor simplify preprocessing
jina-ai/now pull request #695
Opened 2022-11-23 10:07 UTC by florian-hoenicke

2022-11-28 17:33 UTC, florian-hoenicke commented on requirements.txt
> +pydantic==1.9.2
This was required for the qdrant executor. Otherwise the build takes very long and is stale at some point

2022-11-29 11:06 UTC, joschkabraun requested changes
Nice refactoring!
Left some comments

2022-11-29 13:45 UTC, florian-hoenicke commented on deployment/bff/app/v1/routers/im_txt2im_txt.py
> +            'access_paths': '@cc',
the external clip encoder still requires the path. If we deploy that one with access_paths cc then it is solved

2022-11-29 13:51 UTC, florian-hoenicke commented on now/executor/preprocessor/Dockerfile
> +WORKDIR /workdir
Whenever the files in the work dir are changed, the cache is invalidated

2022-11-29 13:58 UTC, florian-hoenicke commented on now/app/base/app.py
> ~        """
thanks done

2022-11-29 13:58 UTC, florian-hoenicke commented on now/app/base/preprocess.py
> +import io
Nice finding. I changed it to 
```            
            has_preprocessing_changed:
            - 'now/app/base/**'
            - 'now/common/preprocess.py'
            - 'now/executor/preprocessor/**'
            - 'now/executor/abstract/auth/**'
```

2022-11-29 15:04 UTC, violenil reviewed
I love this refactoring! Good work 🚀 left some questions/comments.

2022-11-29 15:04 UTC, violenil commented on tests/common/test_preprocess.py
> -    assert len(result[0].chunks[0].chunks) == 0
Are these text preprocessing tests still present somewhere else, ie. is this functionality (like splitting) tested elsewhere?

2022-11-29 15:04 UTC, violenil commented on tests/executor/preprocessor/test_unit.py
> +    assert res_search[0].chunks[0].chunks[0].text == 'test'
Might be nice to add a case here with a document where text is a bit longer (2 or 3 sentences) and make sure all sentences are now chunks.

2022-11-29 15:41 UTC, florian-hoenicke commented on now/app/base/preprocess.py
> +    """If necessary, loads text for all documents. If asked for, splits documents by sentences.
Thanks for noticing. I will update the docstring

2022-11-29 17:28 UTC, florian-hoenicke commented on now/executor/abstract/base_indexer/base_indexer.py
> +        chunks_size = int(parameters.get('chunks_size', 3))
Very good finding! chunks_size was just some bad hack I did in the past. Each modality might have a variable number of chunks. Therefore, a constant number does not make sense

2022-11-29 17:36 UTC, florian-hoenicke commented on now/executor/abstract/base_indexer/base_indexer.py
> +        # TODO please remove theses checkf for empty docs
thanks, I don't know what I was writing :)

2022-11-29 17:38 UTC, florian-hoenicke commented on now/executor/autocomplete/executor.py
> +        flat_docs = docs['@r']
True thanks

2022-11-29 17:38 UTC, florian-hoenicke commented on now/executor/autocomplete/executor.py
> +        for doc in docs['@r']:
thanks

2022-11-29 17:39 UTC, florian-hoenicke commented on now/executor/indexer/elastic/elastic_indexer.py
> +        for i, dim in enumerate(self.dims):
Thanks, yes. I was just trying to get it passed.

2022-11-29 17:53 UTC, florian-hoenicke commented on tests/executor/preprocessor/test_unit.py
> +    assert res_search[0].chunks[0].chunks[0].text == 'test'
Nice, done

2022-11-29 17:54 UTC, florian-hoenicke commented on tests/common/test_preprocess.py
> -    assert len(result[0].chunks[0].chunks) == 0
Good catch - added that case

2022-11-29 18:45 UTC, merged