feat: add schema functions
jina-ai/now pull request #712
Opened 2022-11-28 16:44 UTC by azayz

2022-11-30 10:41 UTC, florian-hoenicke requested changes
A great feature you are implementing. Here are my first comments:

2022-11-30 10:41 UTC, florian-hoenicke commented on now/common/options.py
> +def _get_schema_docarray(user_input: UserInput, **kwargs):
I think the schema functionality should be in a separate file because it is not directly related to options.

2022-11-30 10:41 UTC, florian-hoenicke commented on now/common/options.py
> +        user_input.field_names = field_names
I think it is better to always create a fresh list instead of removing elements.
Something like this:
```
ignored_fieldnames = ['embedding', 'id', 'mime_type']
user_input.field_names = [field_name for field_name in field_names if field_name not in ignored_fieldnames]
```

2022-11-30 10:41 UTC, florian-hoenicke commented on now/common/options.py
> +        for el in ['embedding', 'id', 'mime_type']:
Why is it required to filter out these names?

2022-11-30 12:53 UTC, azayz commented on now/common/options.py
> +        for el in ['embedding', 'id', 'mime_type']:
not really required but the user won't want embeddings , or document id or mime type as a search field

2022-12-02 10:50 UTC, florian-hoenicke commented on now/common/detect_schema.py
> +        return []
Why do we return an empty list in that case?

2022-12-02 10:50 UTC, florian-hoenicke commented on now/common/detect_schema.py
> +        return []
Since the function is get schema local folder, why would it be a file?

2022-12-02 10:52 UTC, florian-hoenicke commented on now/common/detect_schema.py
> +                    raise ValueError(
you can provide a link to now.jina.ai

2022-12-02 10:53 UTC, florian-hoenicke commented on now/common/detect_schema.py
> +        else:
I think the whole logic here becomes too complicated. 
Do you see a way to simplify it?
For instance by breaking it down into smaller functions

2022-12-02 10:58 UTC, florian-hoenicke requested changes

2022-12-02 10:58 UTC, florian-hoenicke commented on now/data_loading/utils.py
> +def _get_s3_bucket_and_folder_prefix(user_input: UserInput):
I think we already have the code for working with S3 in our code base. I think you should find and use the existing functions.

2022-12-02 10:58 UTC, florian-hoenicke commented on tests/unit/test_detect_schema.py
> +def test_get_schema_local_folder(gif_resource_path):
I think you should use parameterize to remove the redundancy in these tests

2022-12-02 13:18 UTC, azayz commented on now/data_loading/utils.py
> +def _get_s3_bucket_and_folder_prefix(user_input: UserInput):
yes I actually did this as a refactoring so now we call this function

2022-12-06 12:30 UTC, violenil reviewed
Looks good! I am so excited about this, big changes coming! I did leave some comments. Please can you write docstrings for the functions that are imported outside of the file they're defined in, and remove their leading underscore? I think it is better to have this leading underscore on internal functions, that are not used outside of a class.
Also, please could you write an informative description for the PR? It will make it easier to understand what was done here (and this is an important PR :) )
Good work!

2022-12-06 12:30 UTC, violenil commented on now/common/detect_schema.py
> +        raise ValueError('DocumentArray doesnt exist or you dont have access to it')
```suggestion
        raise ValueError('DocumentArray does not exist or you do not have access to it')
```

2022-12-06 12:30 UTC, violenil commented on now/common/detect_schema.py
> +    )  # user has to provide the folder where folder structure begins
What do you mean by 'where folder structure begins'? Is it kind of like the base directory?

2022-12-06 12:30 UTC, violenil commented on now/common/detect_schema.py
> +    all_files = True
Would it not make sense to set `all_files` to `False` to begin with, and set it to `True` once your conditions are met? I.e. you have found all files?

2022-12-06 12:30 UTC, violenil commented on now/common/detect_schema.py
> +def _get_schema_s3_bucket(user_input: UserInput, **kwargs):
Can you please add docstrings for these functions? Especially since they will be imported in other files (and remove leading underscore)

2022-12-06 12:30 UTC, violenil commented on now/common/detect_schema.py
> +                    'File format different than expected, please check documentation.'
Link to documentation? Or anything that might be more helpful.

2022-12-06 12:30 UTC, violenil commented on now/common/detect_schema.py
> +def check_path(path, root):
This function, for example, is only used here in `detect_schema.py` so this one can have a leading underscore, if you like.

2022-12-06 12:30 UTC, violenil commented on now/common/detect_schema.py
> +        return []
```suggestion
        user_input.field_names = []
```
This function should not return anything, right? The signature shows that it doesn't, and all calls of this function don't expect any return values.

2022-12-06 12:30 UTC, violenil commented on now/common/options.py
> +
```suggestion
```

2022-12-06 12:30 UTC, violenil commented on now/common/options.py
> +    _create_app_from_output_modality(user_input)
🥳

2022-12-06 12:51 UTC, joschkabraun requested changes
Nice refactoring in dialog! I think we can push it even further.

2022-12-06 12:51 UTC, joschkabraun commented on now/common/options.py
> ~    user_input.app_instance = construct_app(app_name)
This looks like fixing a symptom. In which cases is app_instance None? Also, can't we remove output modality question now given that we ask for search fields?

2022-12-06 12:51 UTC, joschkabraun commented on now/common/options.py
> +    post_func=lambda user_input, **kwargs: _get_schema_s3_bucket(user_input),
we can remove the commented code (below)

2022-12-06 12:51 UTC, joschkabraun commented on now/common/options.py
> +
Dynamically modifying `user_input.field_names` looks dangerous to me as this isn't clear. I think it's better to let the function returning the choices, simply exclude the search fields.

2022-12-06 14:17 UTC, azayz commented on now/common/detect_schema.py
> +        return []
you are right, Ill change this

2022-12-07 12:57 UTC, azayz commented on now/common/detect_schema.py
> +    all_files = True
I think it's same logic, I believe it's easier to assume something is true and find one example that shows its false than the other way around

2022-12-07 13:02 UTC, azayz commented on now/common/options.py
> +
I tried using what we discussed during pairing but the code looked redundant for getting field names and removing the search fields can't be done in one line so I would rather use functions, however I changed the function naming to indicate more what we are doing

2022-12-08 13:55 UTC, florian-hoenicke commented on tests/unit/test_detect_schema.py
> +def test_set_field_names_from_local_folder(gif_resource_path):
please use pytest fixtures for the tests to reduce the code redundancy

2022-12-08 13:57 UTC, florian-hoenicke commented on now/common/detect_schema.py
> +def _check_folder_structure_s3_bucket(objects, folder_prefix):
well done creating separated function making it easy to follow

2022-12-08 14:00 UTC, joschkabraun requested changes

2022-12-08 14:50 UTC, makram93 requested changes

2022-12-08 14:50 UTC, makram93 commented on now/common/detect_schema.py
> +        field_names.extend(list(response.json()[0]['tags']['fields'].keys()))
Add a check here for `tags`. if they are present and not empty

2022-12-09 09:07 UTC, joschkabraun commented on now/now_dataclasses.py
> +    field_names: Optional[List] = None
when searching for this field, it's only written into to then read again from it, please remove it

2022-12-09 09:07 UTC, joschkabraun commented on now/common/options.py
> +    conditional_check=lambda user_input: user_input.field_names is not None
this depends on `user_input.search_field_candidates`; it's also the question what happens if there are no search field candidates: is that an illegal state?

2022-12-09 09:07 UTC, joschkabraun commented on now/common/options.py
> +    conditional_check=lambda user_input: user_input.field_names is not None
depends on `user_input.filter_fields_candidates`

2022-12-09 10:53 UTC, azayz commented on now/common/options.py
> +    conditional_check=lambda user_input: user_input.field_names is not None
yes that is an illegal state and an error is raised

2022-12-09 12:54 UTC, azayz commented on tests/integration/test_end_to_end.py
> +        'search_fields': [],
done

2022-12-09 13:00 UTC, azayz commented on now/now_dataclasses.py
> +    search_fields_modalities: Optional[List] = None
the modalities dict isn't read in this PR but Kalim needs this search fields to modality mapping for his PR

2022-12-09 13:25 UTC, makram93 commented on now/common/options.py
> +    and len(user_input.filter_fields_candidates) > 0
```suggestion
    and len(set(user_input.filter_fields_candidates) - set(user_input.search_fields)) > 0
```

2022-12-09 13:45 UTC, makram93 approved these changes
Nice work on extracting the schema. Hopefully, with the introduction of multimodal DocArrays our task will become much simpler.
LGTM!

2022-12-09 15:04 UTC, joschkabraun approved these changes
LGTM! Minor refactor suggestion

2022-12-09 15:04 UTC, joschkabraun commented on now/now_dataclasses.py
> +    filter_fields_candidates: Optional[List] = []
as discussed in pairing, we can remove `search_fields_candidates` as we have modalities; similarly, for `filter_fields_candidates`, introduce modalities here; then we can remove redundant code in `common/utils:_extract_tags_for_indexer`

2022-12-11 21:46 UTC, florian-hoenicke approved these changes
LGTM

2022-12-11 21:47 UTC, merged