feat: n-to-n ElasticIndexer multi modal doc
jina-ai/now pull request #735
Opened 2022-12-06 13:28 UTC by violenil

---

- [ ] This PR references an open issue
- [ ] Test added
- [ ] Documentation adjusted

2022-12-13 13:41 UTC, maximilianwerk requested changes
I did not review the tests. Good job!

The only important change for now is the was we handle `apply_default_bm25`, because it is an interface change. The other things can be addressed in a refactoring later.

2022-12-13 13:41 UTC, maximilianwerk commented on now/executor/indexer/elastic/es_converter.py
> +                    doc.tags['embeddings'][k] = v
Didn't we said, the embeddings should be put into the doc before serialization in this way? This ensures, least effort during search.

2022-12-13 13:49 UTC, violenil commented on now/executor/indexer/elastic/es_converter.py
> +                    doc.tags['embeddings'][k] = v
This is true, we should not have embeddings in the **serialized** docs, which are removed [here](https://github.com/jina-ai/now/blob/feat-elastic-multi-modal-doc/now/executor/indexer/elastic/es_converter.py#L36) in the es_converter before serializing and indexing. In the conversion here, `convert_es_to_da` is loading the serialized doc (has no embeddings) and adds the embeddings it retrieved upon search from the index as tags, on the condition that we want to do a score breakdown. We would need those embeddings then.

Perhaps, we should also use `get_score_breakdown` to define whether the embeddings from ES should be returned upon search (restrict the result from ES). This is not something I have covered yet.

2022-12-16 11:54 UTC, joschkabraun requested changes
Nice changes to the ElasticIndexer!
A few comments below.
Also, will tags from OCR detection be incorporated in this PR or in a follow-up?

2022-12-16 11:54 UTC, joschkabraun commented on now/executor/indexer/elastic/es_query_builder.py
> +                }
code redundancy: `query_json` in `else` looks like `organic` in `if pinned_queries`

2022-12-16 11:54 UTC, joschkabraun commented on now/executor/indexer/elastic/es_query_builder.py
> +        if getattr(doc, 'query_text', None):
can we define a constant for the assumption that the query has attribute `query_text`? this will make future code changes easier

2022-12-16 11:54 UTC, joschkabraun commented on now/executor/indexer/qdrant/Dockerfile
> +FROM qdrant/qdrant:v0.10.1
Out of curiosity, was there a need to this change?

2022-12-16 11:54 UTC, joschkabraun commented on now/executor/indexer/elastic/elastic_indexer.py
> +        self.default_semantic_scores = (
I find the name `default_semantic_score` somewhat confusing. By its name I would think it means the just default values for all semantic scores (e.g. cos. sim. of 0 or so). But then I would also be confused why we need default values (presumably to fill some value in if an error occurs?).
If I correctly understand, `default_semantic_score` means something else, right? If so, can you change the name please.

2022-12-16 11:54 UTC, joschkabraun commented on now/executor/indexer/elastic/elastic_indexer.py
>              print(traceback.format_exc())
should we change the `print` statements to use `self.logger`?

2022-12-16 11:54 UTC, joschkabraun commented on now/executor/indexer/elastic/elastic_indexer.py
> +            else es_mapping
all the code of the form `var = other_val if not val else val` can be written as `var = val or other_val`

2022-12-16 11:54 UTC, joschkabraun commented on now/executor/indexer/elastic/elastic_indexer.py
> +            self.default_semantic_scores = (
here is also:  `var = other_val if not val else val` -> `var = val or other_val`

2022-12-16 11:54 UTC, joschkabraun commented on now/executor/indexer/elastic/elastic_indexer.py
> +        ids = parameters.get('ids', None)
is that change reflected in docs or somewhere else on a higher level than this endpoint?

2022-12-16 12:00 UTC, violenil commented on now/executor/indexer/elastic/es_converter.py
> +                    _doc = DocumentArray(Document(doc, copy=True))
Oh strange, I remember not being able to `to_base64` on a Document. Will try it. Thanks👍🏻

2022-12-16 12:02 UTC, violenil commented on now/executor/indexer/elastic/es_preprocessor.py
> +    def average_embeddings_of_subdocuments(field_doc):
I wanted to allow in future other methods to be used instead of simple 'averaging', that is why I made it a separate function.

2022-12-16 12:03 UTC, violenil commented on now/executor/indexer/elastic/es_preprocessor.py
> +                        if field_doc[0].uri:
Yes, we make this assumption for now. Should support Videos (same uri for all frames). If there are multiple images for a document with different URI's, they will each need to be a separate field.

2022-12-16 12:04 UTC, violenil commented on now/executor/indexer/elastic/es_converter.py
> +            embedding = self.average_embeddings_of_subdocuments(field_doc)
It does, it is a staticmethod (the one-liner 😉)

2022-12-16 12:05 UTC, violenil commented on now/executor/indexer/elastic/es_query_builder.py
> +                }
True. I just wanted to be as explicit as possible, since it is really easy to loose oversight in this query building process. I can however simplify this, you are right!

2022-12-16 12:06 UTC, violenil commented on now/executor/indexer/elastic/es_query_builder.py
> +        if getattr(doc, 'query_text', None):
Yes, good idea. This is what I meant when talking about standardizing the format of our query Document from `@dataclass`. I will make this a constant.

2022-12-16 12:08 UTC, violenil commented on now/executor/indexer/qdrant/Dockerfile
> +FROM qdrant/qdrant:v0.10.1
Yes, there is a need. In order to use multimodal document from docarray, we need docarray version `0.19.0`, which in turn needs a qdrant-client with version `0.10.1`, so these docker images needed to be updated.

2022-12-16 12:17 UTC, violenil commented on now/executor/indexer/elastic/elastic_indexer.py
> +        self.default_semantic_scores = (
This `default_semantic_score` defines how Document scores (eg. cosine similarity between two fields) should be calculated. For example: 

```
default_semantic_score = [
        SemanticScore('query_text', 'title', 'clip', 1),
        SemanticScore('query_text', 'gif', 'clip', 1),
        SemanticScore('query_text', 'title', 'sbert', 1),
        SemanticScore('query_text', 'excerpt', 'sbert', 3),
        SemanticScore('query_text', 'my_bm25_query', 'bm25', 1),
    ]
```
Where a `SemanticScore` consists of 1. field from query, 2. field from document, 3. encoder and 4. weighting of this component.

If this isn't passed when searching, the `default_semantic_score` will be automatically generated as a cosine similarity between all possible fields encoded in the same vector space with a weighting of 1.

With this definition, I think the name `default_semantic_score` is suitable. Can you propose a better name? Perhaps  `default_semantic_score_combination`?

2022-12-16 12:17 UTC, violenil commented on now/executor/indexer/elastic/elastic_indexer.py
>              print(traceback.format_exc())
Ah good point! I will change this. Thanks!

2022-12-16 12:19 UTC, violenil commented on now/executor/indexer/elastic/elastic_indexer.py
> +        ids = parameters.get('ids', None)
Hmm I think this is not reflected, though it may be a new feature as far as I know. Will document it 👍🏻

2022-12-16 12:22 UTC, violenil commented
| Also, will tags from OCR detection be incorporated in this PR or in a follow-up?

I think it makes sense to incorporate this into a separate PR. In the executor tests for the NOWElasticIndexer I have also marked `test_search_chunk_using_sum_ranker` to skip, since ranking + OCR is not yet integrated. I will create a follow-up ticket for this.

2022-12-16 15:01 UTC, florian-hoenicke requested changes
What do you think about the following comments?

2022-12-16 15:01 UTC, florian-hoenicke commented on now/executor/indexer/elastic/es_converter.py
> +    def convert_es_results_to_matches(
Is this function used?

2022-12-16 15:01 UTC, florian-hoenicke commented on tests/executor/indexer/elastic/test_es_converter.py
> +def test_convert_es_results_to_matches(es_inputs):
If the related function is not used and the test is not implement, we should remove it and rather create a followup ticket to implement this.

2022-12-16 15:14 UTC, florian-hoenicke requested changes
What do you think about the following comments?

2022-12-16 15:14 UTC, florian-hoenicke commented on now/executor/indexer/elastic/es_converter.py
> +            if get_score_breakdown:
Do we use the score breakdown?

2022-12-16 15:14 UTC, florian-hoenicke commented on now/executor/indexer/elastic/es_converter.py
> +            if metric == 'cosine':
The score calculation could deserve a separate function

2022-12-16 15:14 UTC, florian-hoenicke commented on now/executor/indexer/elastic/es_preprocessor.py
> +    def preprocess_docs_map(
I think we should have a different name to preprocessing since we already have that term in use.
What about merge_docs_map?

2022-12-16 15:14 UTC, florian-hoenicke commented on now/executor/indexer/elastic/es_preprocessor.py
> +                        new_doc = Document(
merged_doc instead of new_doc?

2022-12-16 15:14 UTC, florian-hoenicke commented on now/executor/indexer/elastic/es_query_building.py
> +        if executor_name == 'preprocessor':
Since we don't do the skip connection anymore, this can be removed.

2022-12-16 15:14 UTC, florian-hoenicke commented on now/executor/indexer/elastic/es_query_building.py
> +        if executor_name == 'preprocessor':
Or what is your opinion?

2022-12-16 15:54 UTC, violenil commented on now/executor/indexer/elastic/es_converter.py
> +                    k.startswith('embedding') or k.endswith('embedding')
Because in the elasticsearch index the embeddings for each field are stored under "{field_name}-{encoder}-embedding"

2022-12-16 15:55 UTC, violenil commented on now/executor/indexer/elastic/es_converter.py
> +    def convert_es_results_to_matches(
Yes.

2022-12-16 15:56 UTC, violenil commented on tests/executor/indexer/elastic/test_es_converter.py
> +def test_convert_es_results_to_matches(es_inputs):
This function is used.

2022-12-16 15:56 UTC, violenil commented on now/executor/indexer/elastic/es_converter.py
> +            if get_score_breakdown:
Being able to get a score breakdown is a feature that was requested as part of this refactoring.

2022-12-16 15:57 UTC, violenil commented on now/executor/indexer/elastic/es_query_building.py
> +        if executor_name == 'preprocessor':
True!

2022-12-17 23:20 UTC, florian-hoenicke commented on .github/workflows/ci.yml
> +        timeout-minutes: 15
I think, we should investigate why it takes now longer

2022-12-18 13:44 UTC, violenil commented on now/executor/indexer/elastic/es_preprocessor.py
> +    def preprocess_docs_map(
I would stick with the name 'preprocessing', since we don't actually merge the `docs_map` here. The function still returns a `docs_map`. We are just preparing the docs_map for indexing.

2022-12-18 14:30 UTC, violenil commented on .github/workflows/ci.yml
> +        timeout-minutes: 15
As far as I can see, the test for executors now take 11:14 minutes. The tests I am adding to this section take a total of 32 seconds. I think this may have just pushed the session timeout over the edge. However, I don't know if there is a way to reduce the time it take for the Elasticsearch tests to run - it is already so quick.

2022-12-19 09:50 UTC, jupyterjazz reviewed
Looks great! :rocket:

added few comments

2022-12-19 09:50 UTC, jupyterjazz commented on now/executor/indexer/elastic/es_query_building.py
> +def generate_semantic_scores(
I remember you showed me a library for query building. Decided not to use it?

2022-12-19 09:50 UTC, jupyterjazz commented on now/executor/indexer/elastic/es_preprocessing.py
> +def merge_subdocuments(docs_map, encoder_to_fields) -> Dict[str, DocumentArray]:
Just a small comment, I was wondering if it makes sense for this function to be part of the `ESConverter` because it seems like `merge_subdocuments` will only be used during converting, and the separate file might be a bit confusing?

2022-12-19 09:50 UTC, jupyterjazz commented on now/executor/indexer/elastic/es_preprocessing.py
> +def merge_subdocuments(docs_map, encoder_to_fields) -> Dict[str, DocumentArray]:
Just a small comment, I was wondering if it makes sense for this function to be part of the `ESConverter` because it seems like `merge_subdocuments` will only be used during converting, and the separate file might be a bit confusing?

2022-12-19 09:50 UTC, jupyterjazz commented on now/executor/indexer/elastic/es_query_building.py
> +            yield query_field, document_field, _encoder, linear_weight
another small comment: looks like we introduced this function for only one if statement. Is this true or am I missing something? If so, do we need it?

2022-12-19 10:15 UTC, violenil commented on now/executor/indexer/elastic/es_preprocessing.py
> +def merge_subdocuments(docs_map, encoder_to_fields) -> Dict[str, DocumentArray]:
@maximilianwerk  insisted on this separation of 'preprocessing' documents, and conversion into elasticsearch format. I think this is a good way to go for now.

2022-12-19 10:19 UTC, violenil commented on now/executor/indexer/elastic/es_query_building.py
> +            yield query_field, document_field, _encoder, linear_weight
I anticipated that we might need to `get_scores` in other places in the code, whenever we need to see what semantic scores are relevant for a particular encoder. It may be overkill, but also makes the code more readable.

2022-12-19 10:23 UTC, violenil commented on now/executor/indexer/elastic/es_converter.py
> +        Transform a dictionary (mapping encoder to DocumentArray) into a list of Elasticsearch documents.
Done.

2022-12-19 10:43 UTC, florian-hoenicke approved these changes
Besides the qdrant version update, it should not have any impact on the current deployments, I consider it save to merge.

2022-12-19 12:15 UTC, joschkabraun approved these changes
LGTM!

2022-12-19 12:17 UTC, merged