fix: search with tags
jina-ai/now pull request #755
Opened 2022-12-13 08:23 UTC by jupyterjazz

Closes https://github.com/jina-ai/now/issues/714

---

- [x] This PR references an open issue
- [x] Test added
- [ ] Documentation adjusted

2022-12-15 15:17 UTC, florian-hoenicke requested changes
Since we defined the requirements of a pr, the following things are missing:
for bff/ playground:
- give screenshot of using filtering via bff
- test if it breaks client deployment

2022-12-16 10:18 UTC, violenil reviewed
Looks good! Good that you're adding a test too. Just a screenshot of the changes added to bff would be nice still.

2022-12-21 15:26 UTC, florian-hoenicke requested changes

2022-12-21 15:26 UTC, florian-hoenicke commented on tests/integration/filters/test_search_with_tags.py
> +def run_docker(tests_folder_path):
please remove the duplicated code

2022-12-21 15:26 UTC, florian-hoenicke commented on deployment/bff/app/v1/routers/helper.py
> +                query[key] = {}
you can use a defaultdict instead of having the if-condition

2022-12-21 15:26 UTC, florian-hoenicke commented on tests/integration/filters/test_search_with_tags.py
> +            uses=NOWQdrantIndexer16,
You can run the test with both - in-memory and qdrant

2022-12-21 15:26 UTC, florian-hoenicke commented on tests/integration/filters/test_search_with_tags.py
> +def get_flow():
The whole flow can be combined with the authentication check.
The recurring pattern is that we start a BFF and also a flow.

2022-12-22 15:51 UTC, florian-hoenicke approved these changes
Great work. With this, we have a solid base for future testing

2022-12-22 15:53 UTC, merged