Feat migrate demo ds
jina-ai/now pull request #761
Opened 2022-12-13 15:47 UTC by makram93

Migrate demo dataset tp docarray as multi-modal documents
---

- [ ] This PR references an open issue
- [ ] Test added
- [ ] Documentation adjusted

2022-12-15 13:37 UTC, joschkabraun commented on now/common/detect_schema.py
> -    ) = _create_candidate_search_filter_fields(field_names)
why don't we use `_create_candidate_search_filter_fields` to restrict which fields are selectable as filter fields?

2022-12-15 13:37 UTC, joschkabraun commented on now/common/options.py
> +        user_input.dataset_type in [DatasetTypes.DEMO, DatasetTypes.DOCARRAY]
Does that mean for even demo datasets we need now Jina login? I can imagine this being a bit annoying for a user wanting to play around with it.

2022-12-15 15:38 UTC, makram93 commented on now/common/options.py
> +        user_input.dataset_type in [DatasetTypes.DEMO, DatasetTypes.DOCARRAY]
If the datasets are hosted on Hubble then yes the login will be needed. Alternatively, we can move the datasets to S3 bucket to avoid this

2022-12-15 15:47 UTC, makram93 commented on now/common/detect_schema.py
> -    ) = _create_candidate_search_filter_fields(field_names)
Because the current `_create_candidate_search_filter_fields` written is from unimodal POV. In the case of multimodal, we will only check the dataclass attribute name and its type. We can use this type and also check the content to suggest if it could be candidate for filtering

2022-12-16 12:36 UTC, makram93 commented on now/common/detect_schema.py
> -    ) = _create_candidate_search_filter_fields(field_names)
Have updated the code to check the type and incase of custom type the code should check the content to determine if it is possible to add it as filter_field

2022-12-16 12:48 UTC, joschkabraun requested changes

2022-12-16 12:48 UTC, joschkabraun commented on now/common/options.py
> +    user_input.filter_fields_modalities = {
The dynamic changing of `filter_fields_modalities` looks bad to me. We avoided doing it in the detect schema PR as these are hidden changes which are difficult to understand later on.

2022-12-16 12:48 UTC, joschkabraun commented on now/common/options.py
> +    user_input.filter_fields_modalities = filter_modalities
Similarly, here

2022-12-16 12:48 UTC, joschkabraun commented on now/common/detect_schema.py
> -    ) = _create_candidate_search_filter_fields(field_names)
The current logic has those issues
- it would allow any kind of types be allowed as search fields (e.g. music, or arbitrary videos)
- as far as I understand, it only allows for usage of `text` fields for filtering. But how are e.g. floats handled?

2022-12-16 12:48 UTC, joschkabraun commented on now/deployment/flow.py
> +            except BaseException as e:
This `try ... except` block is obsolete

2022-12-16 14:08 UTC, makram93 commented on now/common/detect_schema.py
> -    ) = _create_candidate_search_filter_fields(field_names)
For the docarray/demo, this PR only allows:
-  Those dataclass fields which are text-based, their content has text and not blob or tensors hence, fields with any non-text content will be filtered out
- All items in the tags because tags can only hold string/bool/float and this matches with the allowed column's type for qdrant, i.e., `str, float, int, bool`

2022-12-19 13:10 UTC, jupyterjazz reviewed
Nice!

left few comments and questions

2022-12-19 13:10 UTC, jupyterjazz commented on deployment/playground/src/constants.py
> +root_data_dir = 'https://jina-now-demo.s3.eu-central-1.amazonaws.com/'
Should we make this uppercase?

2022-12-19 13:10 UTC, jupyterjazz commented on now/common/options.py
> +            f'Search field specified is not among the search candidates field. Kindly '
```suggestion
            f'Search field specified is not among the search candidate fields. Kindly '
```

2022-12-19 13:10 UTC, jupyterjazz commented on now/common/options.py
> +    depends_on=True,
What's the purpose of this?

2022-12-19 13:10 UTC, jupyterjazz commented on now/common/utils.py
> +            final_tags.append([tag, value])
Did you change anything here?

2022-12-19 13:34 UTC, makram93 commented on deployment/playground/src/constants.py
> +root_data_dir = 'https://jina-now-demo.s3.eu-central-1.amazonaws.com/'
Yep, okay

2022-12-19 13:37 UTC, makram93 commented on now/common/options.py
> +    depends_on=True,
It builds the hierarchy, typically what depends on what but in this case you are right, we can omit it and have no `depends_on` since it should be shown in all scenarios

2022-12-19 13:38 UTC, makram93 commented on now/common/utils.py
> +            final_tags.append([tag, value])
Yes.. filter_field_modalities holds all candidates fields and only those selected in `filter_fields` are added as final tags to be set as column in the table

2022-12-19 14:55 UTC, jupyterjazz approved these changes
LGTM!

2022-12-19 15:18 UTC, violenil approved these changes
LGTM!🚀

2022-12-19 15:34 UTC, joschkabraun approved these changes
LGTM! A few minor comments

2022-12-19 15:34 UTC, joschkabraun commented on now/common/detect_schema.py
> +        except Exception as e:
I might miss this, but doesn't this `except` also catches above `ValueError` and overwrites its hint to the available modalities for search

2022-12-19 15:34 UTC, joschkabraun commented on now/common/detect_schema.py
> +        if modality == 'text':
Can you use the constant used to define which fields are allowed for filtering (in this case which aren't). This makes it easier to unify handling of modalities

2022-12-19 15:34 UTC, joschkabraun commented on now/common/options.py
> +            'choose one of the following: {user_input.search_fields_modalities.keys()}'
This line also, needs `f'...'`

2022-12-19 15:34 UTC, joschkabraun commented on now/common/detect_schema.py
> -    ) = _create_candidate_search_filter_fields(field_names)
Okay!

2022-12-19 16:30 UTC, florian-hoenicke requested changes
LGTM once the issues are addressed mentioned by me and the others.
Great work!

2022-12-19 16:30 UTC, florian-hoenicke commented on tests/unit/test_dialog.py
> +    # (
needs to be uncommented

2022-12-19 16:46 UTC, makram93 commented on now/common/detect_schema.py
> +        except Exception as e:
Good catch! 👍

2022-12-19 17:17 UTC, joschkabraun commented on tests/unit/test_dialog.py
> -            'app': Apps.IMAGE_TEXT_RETRIEVAL,
Is there a reason to delete all those tests?

2022-12-19 23:34 UTC, makram93 commented on tests/unit/test_dialog.py
> -            'app': Apps.IMAGE_TEXT_RETRIEVAL,
These tests were specifically for `subset_laion` dataset which is not multi-modal, hence these tests are not applicable here.

2022-12-20 00:08 UTC, merged