feat: use data class in data loading
jina-ai/now pull request #768
Opened 2022-12-15 09:56 UTC by azayz

Use data class in data loading
---

- [ ] This PR references an open issue
- [ ] Test added
- [ ] Documentation adjusted

2022-12-15 15:56 UTC, florian-hoenicke requested changes

2022-12-15 15:56 UTC, florian-hoenicke commented on now/constants.py
> +def modalities_mapping():
I think it does not have to be a function but can just be a dictionary.

2022-12-15 15:56 UTC, florian-hoenicke commented on now/data_loading/data_loading.py
> +def load_data(user_input: UserInput, data_class) -> DocumentArray:
if possible, you can define a type for data_class

2022-12-15 15:56 UTC, florian-hoenicke commented on now/data_loading/data_loading.py
> +def _load_from_disk(user_input: UserInput, dataclass) -> DocumentArray:
type hint for dataclass.

2022-12-15 15:56 UTC, florian-hoenicke commented on now/data_loading/data_loading.py
> +def from_files(
maybe better name: from_local files?

2022-12-15 15:56 UTC, florian-hoenicke commented on now/data_loading/data_loading.py
> +            file = obj.key.split('/')[-1]
Some lines in this function are duplicated. We should have this logic in a separate function that is called by both functions

2022-12-16 12:14 UTC, joschkabraun requested changes

2022-12-16 12:14 UTC, joschkabraun commented on now/common/detect_schema.py
> +            first_file = file_or_directory
issue is with that solution: by chance the first file could be a not supported file type but the rest of the files are all jpegs.

2022-12-16 12:14 UTC, joschkabraun commented on now/common/detect_schema.py
> +    file_names = _check_contains_files_only_local_folder(dataset_path)
in the following is a lot of duplicate code. Similarly for s3 code

2022-12-19 17:24 UTC, florian-hoenicke requested changes

2022-12-20 08:42 UTC, jupyterjazz reviewed
Great work!

left some minor suggestions

2022-12-20 08:42 UTC, jupyterjazz commented on now/run_backend.py
> +    Create a dataclass from the user input using the selected search anf filter fields
```suggestion
    Create a dataclass from the user input using the selected search and filter fields
```

2022-12-20 08:42 UTC, jupyterjazz commented on now/run_backend.py
> +    all_modalities.update(user_input.search_fields_modalities)
```suggestion
    all_modalities = user_input.search_fields_modalities
```

2022-12-20 08:42 UTC, jupyterjazz commented on now/run_backend.py
> +    update_dict_with_no_overwrite(all_modalities, user_input.filter_fields_modalities)
I was wondering if instead of ignoring it, we should raise an error in case there's an overlap between search and filter fields..

2022-12-20 08:42 UTC, jupyterjazz commented on tests/unit/test_dataclass.py
> +    assert str(mm_doc) == "<class 'now.run_backend.MMDoc'>"
maybe better to check `mm_doc.__class__.__name__`?

2022-12-20 08:42 UTC, jupyterjazz commented on now/run_backend.py
> +    ) = create_annotations_and_class_attributes(
Agree with Florian.
Would be nice to somehow combine `create_annotations_and_class_attributes` calls for both search and filter fields.

2022-12-20 08:42 UTC, jupyterjazz commented on tests/resources/subdirectories_structure_folder/folder2/test.txt
> +hello
`subdirectories_structure_folder` seems a bit verbose, maybe just `subdirectories`?

2022-12-20 15:07 UTC, azayz commented on now/run_backend.py
> +    update_dict_with_no_overwrite(all_modalities, user_input.filter_fields_modalities)
it is expected to be an overlap, in fact these dictionaries contain candidates for search and filter fields so some fields could be used for search or for filtering. We create these dicts before the user chooses therefore there's an overlap

2022-12-20 15:10 UTC, azayz commented on now/constants.py
> +def modalities_mapping():
only partial migration I believe is possible now, full migration will add complexity to the PR and it's out of scope I would rather do it in another refactoring PR

2022-12-20 15:10 UTC, azayz commented on now/data_loading/data_loading.py
> +            file = obj.key.split('/')[-1]
done

2022-12-20 16:04 UTC, azayz commented on now/run_backend.py
> +    ) = create_annotations_and_class_attributes(
adressed

2022-12-21 11:37 UTC, joschkabraun requested changes
Only halfway reviewed it, but there are is a lot of redundancy in the `data_loading` for s3 & local files. I would recommend looking at how this is handled in `detect_schema` and follow a similar a schema.

2022-12-21 11:37 UTC, joschkabraun commented on now/common/options.py
> +    if user_input.dataset_type in [DatasetTypes.DEMO, DatasetTypes.DOCARRAY]:
Why not apply the same mapping you did for the other `DatasetTypes` to them as well to standardize it?
I think this different handling of the modalities adds unnecessary cognitive load on the developer. We should standardize it.

2022-12-21 11:37 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +    def get_subdirectories_local_path(directory):
no need to create this function

2022-12-21 11:37 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +    for subdirectory in subdirectories:
this logic fails if all the files are structured in this format e.g.
2022/uuid/file.jpeg
2022/uuid/text.txt
2022/uuid2/file.jpeg
2022/uuid2/text.txt
2021/uuid3/file.jpeg
2021/uuid3/text.txt

2022-12-21 12:40 UTC, azayz commented on tests/unit/test_dataclass.py
> +    assert str(mm_doc) == "<class 'now.run_backend.MMDoc'>"
mm_doc's class name is actually python type, so when you do that you get type 
'type'

2022-12-22 10:59 UTC, azayz commented on now/common/options.py
> +    if user_input.dataset_type in [DatasetTypes.DEMO, DatasetTypes.DOCARRAY]:
correct, applied

2022-12-22 14:07 UTC, azayz commented on now/data_loading/data_loading.py
> +    for subdirectory in subdirectories:
done

2022-12-27 10:43 UTC, joschkabraun approved these changes
Really great work!! :rocket:
Some minor comments. PR can be merged after addressing those, green CI and testing with customer flow.

2022-12-27 10:43 UTC, joschkabraun commented on now/common/detect_schema.py
> +                search_fields_modalities[field_name] = MODALITIES_MAPPING['text']
`modality = 'text'`, isn't it?

2022-12-27 10:43 UTC, joschkabraun commented on now/common/options.py
> +    if _search_modality in [Modalities.TEXT, Modalities.VIDEO, Modalities.IMAGE]:
I think we can skip this `if` condition, or is there a need for it?

2022-12-27 10:43 UTC, joschkabraun commented on now/data_loading/data_loading.py
>              return DocumentArray.load_binary(dataset_path)
We assume that the docarray is in multi-modal format, right? Then I would suggest that we check that it has this format.

2022-12-27 10:43 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +    :param s3_dataset: Whether the dataset is stored on s3
for convention, I would suggest something indicating it is a boolean, e.g. `is_s3_dataset`

2022-12-27 10:43 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +def _extract_file_and_full_file_path(obj, path=None, s3_dataset=False):
I would rename `obj` to something else to help understand that this isn't only code for s3 but in general to interact with a file system.

2022-12-27 10:43 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +def _extract_file_and_full_file_path(obj, path=None, s3_dataset=False):
Also, I would rename `s3_dataset` here as well.

2022-12-27 10:43 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +                    json_f = open(file_full_path)
for reading files, it's recommended to use a context manager

2022-12-27 10:43 UTC, joschkabraun commented on now/run_backend.py
> +def create_dataclass(user_input: UserInput):
Maybe move this into its own file under `data_loading`?

2022-12-27 10:43 UTC, joschkabraun commented on now/run_backend.py
> +        if not isinstance(f, typing.Hashable):
Not sure what the reason for this is, but it looks a bit like "solving the symptom and not the culprit". What causes the selection of fields which aren't hashable? This looks like we didn't do the right filtering earlier.

2022-12-27 10:43 UTC, joschkabraun commented on now/run_backend.py
> +        modalities_count[modality_name] = 0
can be abbreviated to `modalities_count = defaultdict(int)`

2022-12-27 10:43 UTC, joschkabraun commented on now/run_backend.py
> +        modalities_count[modality_name] = 0
can be simplified to `modalities_count = defaultdict(int)`

2022-12-27 12:20 UTC, azayz commented on now/common/detect_schema.py
> +                search_fields_modalities[field_name] = MODALITIES_MAPPING['text']
Text which is coming from docarray.typing

2022-12-27 12:23 UTC, azayz commented on now/common/options.py
> +    if _search_modality in [Modalities.TEXT, Modalities.VIDEO, Modalities.IMAGE]:
I think we keep it to make sure that search modality is among those modalities else ye'll trigger the value error, also it makes it easier to debug with the value error

2022-12-27 16:02 UTC, joschkabraun commented on now/common/detect_schema.py
> +                search_fields_modalities[field_name] = MODALITIES_MAPPING['text']
Isn't `Modalities.Text = 'text'` as it's defined this way in `constants.py`?

2022-12-27 16:03 UTC, joschkabraun commented on now/common/options.py
> +    if _search_modality in [Modalities.TEXT, Modalities.VIDEO, Modalities.IMAGE]:
We determine candidates for search modality in `detect_schema`, so this shouldn't be an error which can happen. Let's remove as otherwise, we duplicate the checks for which modalities are allowed for searching.

2022-12-28 09:09 UTC, azayz commented on now/common/detect_schema.py
> +                search_fields_modalities[field_name] = MODALITIES_MAPPING['text']
yes it is

2022-12-28 09:43 UTC, jupyterjazz approved these changes
LGTM!

left some minor comments

2022-12-28 09:43 UTC, jupyterjazz commented on now/data_loading/data_loading.py
> +            )
would be nice to add a link here guiding developers on how to create proper multimodal data

2022-12-28 09:43 UTC, jupyterjazz commented on now/data_loading/data_loading.py
> +        da = _load_from_disk(user_input=user_input, dataclass=data_class)
to stay consistent, we should call this `data_class` too

2022-12-28 09:43 UTC, jupyterjazz commented on now/data_loading/data_loading.py
> +                )
same here about the instructions

2022-12-28 10:32 UTC, azayz commented on now/common/options.py
> +    if _search_modality in [Modalities.TEXT, Modalities.VIDEO, Modalities.IMAGE]:
correct removed

2022-12-28 10:39 UTC, joschkabraun commented on now/common/detect_schema.py
> +                    Modalities.TEXT
why not use the variable `modality`?

2022-12-28 11:03 UTC, azayz commented on now/common/detect_schema.py
> +                    Modalities.TEXT
because we loop over all the modalities, so it could be that this field name is coming from docarray and the field name is text so we know this field's modality is text but the modality variable could be image or anything

2022-12-28 11:07 UTC, joschkabraun commented on now/common/detect_schema.py
> +                    Modalities.TEXT
Ah, this makes sense. Now I understand the different handling. I would suggest to move this check then out of the for loop to avoid confusion

2022-12-28 13:14 UTC, jupyterjazz approved these changes
:rocket:

2022-12-28 13:29 UTC, violenil approved these changes
Looks great!🚀

2022-12-28 13:46 UTC, azayz commented on now/data_loading/create_dataclass.py
> +def create_dataclass(user_input: UserInput):
yes and added in doctoring

2022-12-28 13:46 UTC, azayz commented on now/data_loading/create_dataclass.py
> +    and their corresponding modalities
added in doctoring

2022-12-28 14:06 UTC, merged