fix: replicas for local deployment
jina-ai/now pull request #770
Opened 2022-12-16 15:39 UTC by IyadhKhalfallah

- Added condition to add replicas for high-performance flow only in remote deployment.

- Fixed typo for timeout sending in test mode.

2022-12-16 18:16 UTC, joschkabraun requested changes
Good findings! I also really like how you simplified verbose `if if .. else else if ... else` structure 🚀 
A few things:
- we have a PR template which is required to be used
- did you have a look at the full ticket? It was also suggest to replace the readiness probe as done here: https://docs.jina.ai/concepts/flow/readiness/

2022-12-17 18:28 UTC, florian-hoenicke commented on now/app/text_to_video/app.py
> +        if dataset_len > 200_000 and is_jina_email and deployment_type == 'remote':
That is true. On the other hand apart from debugging, there would be not much benefit of allowing multiple replicas locally. I guess it could give a performance boost, but since local deployment is not for production, the performance boost does not add much value.
Therefore, I think it is fine to not support replicas on local deployments.

2022-12-17 18:39 UTC, florian-hoenicke commented on now/app/text_to_video/app.py
> +        if dataset_len > 200_000 and is_jina_email and deployment_type == 'remote':
But regarding the readiness of the client I agree. This should also be handled here. In that case, we can altogether remove the waiting logic and use `client.is_flow_ready`

Then, you can also remove your additional condition. I know, I suggested it to you in our pairing but turns out there is a better way.
1. remove the condition on local deployment you just introduced
2. remove the waiting logic for the flow to start https://github.com/jina-ai/now/blob/2ff6c826fe87dc50632bd7057b5a4ff6c18b0c10/now/deployment/flow.py#L99
3. remove the waiting logic where it tries to make empty requests to the flow (right before indexing) until it is successful https://github.com/jina-ai/now/blob/f643197c886fb4db0ca545bda9dabbb26d42d5e2/now/run_backend.py#L158
4. introduce:
```
client.is_flow_ready()
```
to make sure the flow is ready before indexing (sleep can be removed) https://github.com/jina-ai/now/blob/2ff6c826fe87dc50632bd7057b5a4ff6c18b0c10/now/deployment/flow.py#L102

2022-12-17 18:40 UTC, florian-hoenicke commented
Regarding the readiness of the client I agree. This should also be handled here. In that case, we can altogether remove the waiting logic and use `client.is_flow_ready`

Then, you can also remove your additional condition. I know, I suggested it to you in our pairing but turns out there is a better way.
1. remove the condition on local deployment you just introduced
2. remove the waiting logic for the flow to start https://github.com/jina-ai/now/blob/2ff6c826fe87dc50632bd7057b5a4ff6c18b0c10/now/deployment/flow.py#L99
3. remove the waiting logic where it tries to make empty requests to the flow (right before indexing) until it is successful https://github.com/jina-ai/now/blob/f643197c886fb4db0ca545bda9dabbb26d42d5e2/now/run_backend.py#L158
4. introduce:
```
client.is_flow_ready()
```
to make sure the flow is ready before indexing (sleep can be removed) https://github.com/jina-ai/now/blob/2ff6c826fe87dc50632bd7057b5a4ff6c18b0c10/now/deployment/flow.py#L102

2022-12-19 09:59 UTC, IyadhKhalfallah commented on now/app/text_to_video/app.py
> +        if dataset_len > 200_000 and is_jina_email and deployment_type == 'remote':
@joschkabraun this was implemented during a discussion since the local deployment doesn't really require 20 replicas. But you are right, the ticket should cover more.

2022-12-20 13:49 UTC, florian-hoenicke commented
Do we get a lot of error logs even in the normal case where everything is working?
This could pollute the logs

2022-12-20 13:52 UTC, IyadhKhalfallah commented
> Do we get a lot of error logs even in the normal case where everything is working? This could pollute the logs

@florian-hoenicke if you are referring to `check_pods_health()` it is only logging when there are errors. In normal cases, it shouldn't log anything other than the usual CLI scenario.

2022-12-20 15:28 UTC, joschkabraun approved these changes
LGTM, great work!

2022-12-21 08:55 UTC, florian-hoenicke requested changes

2022-12-21 08:55 UTC, florian-hoenicke commented on now/deployment/flow.py
> +            if pod.status and pod.status.container_statuses:
I think it should make the code more readable if the if statements are combined. What do you think?

2022-12-22 10:54 UTC, IyadhKhalfallah commented on now/deployment/flow.py
> +            if pod.status and pod.status.container_statuses:
@florian-hoenicke Could you please have a look at the new commit and let me know if that responds to the comment?

2022-12-22 12:53 UTC, florian-hoenicke submitted a review, later dismissed

2022-12-22 12:53 UTC, florian-hoenicke commented on now/deployment/flow.py
> +                raise Exception(
The exception will have no effect. because it is caught by the try

2022-12-22 13:13 UTC, IyadhKhalfallah commented on now/deployment/flow.py
> +                raise Exception(
@florian-hoenicke actually, the try is for `container_statuses[0].state.waiting.message`. That can raise an error because one of `state.waiting.reason` might not exist. And in that case, we don't want to have an error in the CLI, we just want to catch it and pass, right?

2022-12-22 15:56 UTC, merged