fix: split executor tests
jina-ai/now pull request #820
Opened 2022-12-27 11:11 UTC by IyadhKhalfallah

---

- [ ] Created two executor tests instead of one

2022-12-30 13:49 UTC, violenil commented on .github/workflows/ci.yml
>          timeout-minutes: 15
You should be able to reduce the timeout for the `executor-test` and `executor-test_indexers` now that they are split. Can you check how long they tend to take and add a few minutes buffer? Hopefully should be something more like 10 minutes or so

2022-12-30 14:32 UTC, azayz commented on .github/workflows/ci.yml
> +      - name: Upload coverage
if I understand this correctly, we have two coverage reports one for indexers and one for the rest of the executors, if so is it possible to only have one coverage report

2023-01-05 15:33 UTC, makram93 approved these changes
LGTM!

2023-01-06 08:42 UTC, jupyterjazz approved these changes
LGTM!

2023-01-06 08:42 UTC, jupyterjazz commented on .github/workflows/cd.yml
> +#        timeout-minutes: 60
should we remove this?

2023-01-06 09:56 UTC, florian-hoenicke requested changes

2023-01-06 09:56 UTC, florian-hoenicke commented on .github/workflows/ci.yml
> +          sudo apt update && sudo apt install ffmpeg
Good that you think about how to optimize the ci.
I think this is the wrong way since it introduces code duplication.
A better way is using a matrix run.
However, the best solution will be to run all the tests together and use pytest split to get the perfect split of all executors

2023-01-06 10:17 UTC, IyadhKhalfallah commented on .github/workflows/ci.yml
> +          sudo apt update && sudo apt install ffmpeg
@florian-hoenicke I think you are right about this, although I'm not sure I get your last sentence. Do you think we should keep the executor tests apart and apply the matrix run on them (like I did in the PR I just created [here](https://github.com/jina-ai/now/pull/885) or should we mix the core tests and executor tests together?

2023-01-06 10:23 UTC, closed without merging