refactor: change all fields mentions to index_fields and query_fields
jina-ai/now pull request #834
Opened 2022-12-28 15:02 UTC by violenil

---

- [ ] This PR references an open issue
- [ ] Test added
- [ ] Documentation adjusted

2022-12-29 11:18 UTC, joschkabraun requested changes
Nice refactoring!
I think we can remove anything related to query fields in the playground as well in `run_all_k8s.py`.

2022-12-29 11:18 UTC, joschkabraun commented on deployment/playground/playground.py
> +        if params.query_fields:
we can remove `query_fields` entirely from the code base in the playground and always offer the possibility to search with `text` and `image` (for now)

2022-12-29 11:18 UTC, joschkabraun commented on now/common/options.py
>              f'Search field specified is not among the search candidate fields. Please '
here is still search field used

2022-12-29 11:18 UTC, joschkabraun commented on now/common/options.py
>              'Currently only one search field is supported. Please choose one field.'
search field is still used here

2022-12-29 11:18 UTC, joschkabraun commented on now/common/utils.py
> ~        is_demo_ds = user_input.dataset_name in valid_app
This won't work, we need to check if the modality of the selected `index_fields` is in `Image` or `Video`.

2022-12-29 11:18 UTC, joschkabraun commented on now/constants.py
> +QUERY_FIELDS = [Modalities.TEXT, Modalities.IMAGE]
When removing query fields from playground, we can remove this constant

2022-12-29 11:18 UTC, joschkabraun commented on now/run_all_k8s.py
> ~        _result = status_wolf(flow_id)
we can also remove it here & in general in this class

2022-12-29 12:55 UTC, azayz reviewed
Great job, left some comments. don't forget to test lottiefiles deploment

2022-12-29 12:55 UTC, azayz commented on docs/main.md
> -<a href="https://nowrun.jina.ai/?host=grpcs://now-example-text-to-image-best-artworks.dev.jina.ai&input_modality=text&output_modality=image&data=best-artworks"  target="_blank" rel="noopener noreferr
why are we deleting these ? does it not work anymore ?

2022-12-29 12:55 UTC, azayz commented on now/app/base/app.py
> -            if Modalities.TEXT in self.input_modality:
if I understand correctly, now the autocomplete executor will always be part of the flow since we no longer have the concept of input_modality

2022-12-29 12:55 UTC, azayz commented on now/common/options.py
> +    argparse_kwargs={'type': lambda s: s.split(',') if s else UserInput().index_fields},
can you rename s into something more meaningful ?

2022-12-29 14:38 UTC, violenil commented on now/app/base/app.py
> -            if Modalities.TEXT in self.input_modality:
Yep, it is now always possible to search using text (or image) so we always need to autocomplete executor.

2022-12-29 14:39 UTC, violenil commented on docs/main.md
> -<a href="https://nowrun.jina.ai/?host=grpcs://now-example-text-to-image-best-artworks.dev.jina.ai&input_modality=text&output_modality=image&data=best-artworks"  target="_blank" rel="noopener noreferr
Nope, our examples need to be re-deployed (no input_modality/output_modality), currently they are useless links in the docs.

2022-12-30 12:57 UTC, azayz approved these changes
LGTM

2022-12-30 13:27 UTC, violenil commented
<img width="1768" alt="Screenshot 2022-12-30 at 14 18 54" src="https://user-images.githubusercontent.com/55404563/210075095-edea1aaa-7de2-4ca1-81ff-2d0ecc7c14fa.png">
Customer deployment working with these changes.

2022-12-30 13:54 UTC, joschkabraun approved these changes
As already pointed out, there are still some `search field` and `search_field` remainders in docstrings, function & variable names. After removing those, let's merge this PR! :rocket:

2022-12-30 14:53 UTC, merged