performance: schema detection takes up to a minute
jina-ai/now pull request #835
Opened 2022-12-28 15:28 UTC by IyadhKhalfallah

---

- [ ] This PR references an open issue
- [ ] Test added
- [ ] Documentation adjusted

2022-12-30 10:53 UTC, azayz requested changes

2022-12-30 10:53 UTC, azayz commented on now/common/detect_schema.py
> +def identify_s3_folder_structure(bucket, folder_prefix) -> str:
use only one function `identify_folder_structure` but add argument `is_s3_dataset` to know which code to use
 also add type hints

2022-12-30 10:53 UTC, azayz commented on now/common/detect_schema.py
> +    structure_identifier = list(bucket.objects.filter(Prefix=folder_prefix).limit(2))[
add comments to explain what are you trying to get here, it's hard to understand just by looking at the code

2022-12-30 10:53 UTC, azayz commented on now/common/detect_schema.py
> +    bucket, folder_prefix = get_s3_bucket_and_folder_prefix(user_input)
type hints

2022-12-30 10:53 UTC, azayz commented on now/common/detect_schema.py
> +        first_file = list(bucket.objects.filter(Prefix=folder_prefix).limit(2))[1]
same comment as above

2022-12-30 16:07 UTC, azayz approved these changes
LGTM after CI green, would love to see a small benchmark of the speed up

2023-01-02 11:28 UTC, joschkabraun requested changes
Nice speed-up in detection!

2023-01-02 11:28 UTC, joschkabraun commented on now/common/detect_schema.py
> ~                break
Let's remove this function if it's only used for s3 and is so short

2023-01-02 11:28 UTC, joschkabraun commented on now/common/detect_schema.py
> +def identify_folder_structure(first_file: str, folder_prefix: str) -> str:
I would add the dataset path in quotation marks; that helps with understanding the error.

2023-01-02 11:28 UTC, joschkabraun commented on now/common/detect_schema.py
> ~        ) = _extract_field_candidates_docarray(response)
what is `i` used for? I think we need to increment `i` below?

2023-01-02 11:28 UTC, joschkabraun commented on now/common/detect_schema.py
> -    :param file_paths: list of file paths
we can limit this to the first few hundred fails maybe?

2023-01-02 11:28 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +        raise Exception(f'Empty folder, data is missing.')
this code looks familiar, let's wrap it in a function

2023-01-02 11:29 UTC, joschkabraun commented on now/common/detect_schema.py
> +        raise Exception(f'Empty folder, data is missing.')
I would add the dataset path in quotation marks; that helps with understanding the error.

2023-01-02 11:30 UTC, joschkabraun commented on now/common/detect_schema.py
> +        objects = list(bucket.objects.filter(Prefix=folder_prefix))
we can limit this to the first few hundred fails maybe?

2023-01-02 11:30 UTC, joschkabraun commented on now/common/detect_schema.py
> +        i = 2
I think we need to increment `i`, don't we?

2023-01-03 08:57 UTC, joschkabraun approved these changes
LGTM!
Nice, speed-up.

2023-01-03 08:57 UTC, joschkabraun commented on now/common/detect_schema.py
> +def get_first_file_in_folder_structure(bucket, folder_prefix, dataset_path):
Let's call it `get_first_file_in_folder_structure_s3`

2023-01-04 15:55 UTC, merged