feat: use data class in es extractor
jina-ai/now pull request #856
Opened 2023-01-02 14:51 UTC by azayz

---

- [ ] This PR references an open issue
- [ ] Test added
- [ ] Documentation adjusted

2023-01-03 09:50 UTC, violenil commented on now/data_loading/elasticsearch/data_extractor.py
> +        this function returns of those documents. Otherwise, the next page is
```suggestion
        this function returns one of those documents. Otherwise, the next page is
```

2023-01-03 09:52 UTC, violenil approved these changes
LGTM! Good refactoring :)

2023-01-03 10:15 UTC, joschkabraun requested changes
Nice enhancement! We can refactor even more in the interaction with elastic.

2023-01-03 10:15 UTC, joschkabraun commented on now/data_loading/elasticsearch/connector.py
> -            **query, index=index_name, scroll='2m', size=page_size, source=False
We can remove `get_documents` and the entire class actually and only leave `get_documents_by_query` as a function to get docs from elastic.

2023-01-03 10:15 UTC, joschkabraun commented on now/data_loading/elasticsearch/data_extractor.py
> +        return DocumentArray([doc for doc in self._extract_documents()])
I believe there is a way how we can remove 3 levels of function calls; but I am not sure at a first glance how to refactor

2023-01-03 10:15 UTC, joschkabraun commented on tests/integration/data_loading/elastic/test_elasticsearch.py
> +    user_input.filter_fields_modalities = {'text': Text}
I will clarify this in a current PR but the actual type of filter fields is `str`, etc.

2023-01-03 10:15 UTC, joschkabraun commented on tests/conftest.py
> +
those fixtures are still in a different place

2023-01-04 10:35 UTC, azayz commented on now/data_loading/elasticsearch/data_extractor.py
> +        return DocumentArray([doc for doc in self._extract_documents()])
will do in another PR

2023-01-05 10:45 UTC, joschkabraun commented on now/app/base/preprocess.py
> +            d.load_uri_to_image_tensor()
Isn't the `timeout` parameter important?

2023-01-05 10:45 UTC, joschkabraun commented on now/common/detect_schema.py
> +            index_fields_modalities[field_name] = MODALITIES_MAPPING[Modalities.TEXT]
Is there a need to make it so complex again?

2023-01-05 10:45 UTC, joschkabraun commented on now/executor/preprocessor/executor.py
> +        if len(docs) > 0 and not docs[0].chunks:
let's use `is_multimodal` as a check for multi-modality

2023-01-05 12:17 UTC, azayz commented on now/executor/preprocessor/executor.py
> +        if len(docs) > 0 and not docs[0].chunks:
print(is_multimodal(DocumentArray())) returns False, sometimes we send empty documents so this will be raised

2023-01-05 12:42 UTC, azayz commented on now/common/detect_schema.py
> +            index_fields_modalities[field_name] = MODALITIES_MAPPING[Modalities.TEXT]
you are right, fixed

2023-01-05 12:42 UTC, azayz commented on now/app/base/preprocess.py
> +            d.load_uri_to_image_tensor()
I think load_uri_to_image_tensor doesn't take timeout parameter anymore

2023-01-05 12:54 UTC, joschkabraun commented on now/app/base/preprocess.py
> +            d.load_uri_to_image_tensor()
it does

2023-01-05 12:55 UTC, joschkabraun commented on now/executor/preprocessor/executor.py
> +        if len(docs) > 0 and not docs[0].chunks:
Yes, but `len(docs) > 0 and docs[0].is_multimodal()` will work.

2023-01-05 13:00 UTC, joschkabraun approved these changes
Small things, otherwise LGTM

2023-01-05 13:00 UTC, joschkabraun commented on now/common/detect_schema.py
> +            index_fields_modalities[field_name] = MODALITIES_MAPPING[Modalities.TEXT]
we don't need this check as `get_field_type` defaults to `txt`; so this should be handled by this

2023-01-06 08:56 UTC, merged