fix: filter out index fields in docarray
jina-ai/now pull request #880
Opened 2023-01-05 16:31 UTC by IyadhKhalfallah

---

- [ ] This PR references an open issue
- [ ] Test added
- [ ] Documentation adjusted

2023-01-10 09:46 UTC, joschkabraun requested changes

2023-01-10 09:46 UTC, joschkabraun commented on now/app/search_app/app.py
> +                        user_input.index_fields,
Why this change? I don't think it works.

2023-01-10 09:46 UTC, joschkabraun commented on now/data_loading/data_loading.py
>      da = set_modality_da(da)
let's handle demo data with the same function as we do with docarray usually

2023-01-10 11:30 UTC, joschkabraun requested changes
Nice work! 🚀 
Some refactor suggestions

2023-01-10 11:30 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +def _field_dict_to_mm_doc(
Please refactor this function and the one defined in the BFF to avoid duplicate code.

2023-01-10 11:30 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +def _construct_tags(document: Document, field) -> Document:
Just so we don't forget it: As in the other PR, this can be written as a one-liner.

2023-01-10 11:30 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +                f'Not a correctly encoded request. Please see the error stack for more information. \n{e}'
This exception doesn't make senes in this context.

2023-01-10 11:30 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +    dataclass = create_dataclass(user_input)
Instead of creating `dataclass` here. We should create at the top-level of `data_loading` as it's now used for all `DatasetTypes`. Then we can also remove the code for creating it in `run_backend.run`

2023-01-10 11:30 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +def get_da_with_index_fields(da: DocumentArray, user_input: UserInput):
stylistic suggestion: let's have `load_data` as first function in this file.

2023-01-13 09:06 UTC, IyadhKhalfallah commented on now/data_loading/data_loading.py
> +#     return da
This is temporarily removed, but it should be updated after solving the failing CI tests.

2023-01-13 14:17 UTC, joschkabraun requested changes

2023-01-13 14:17 UTC, joschkabraun commented on now/utils.py
> +                    data_class_kwargs[field_name_data_class] = field_value.content
these `elif` shouldn't be necessary by the construction of `field_value.content`

2023-01-13 14:17 UTC, joschkabraun commented on now/utils.py
> +def get_blob_format(blob_value):
rename to something like `extract_supported_file_type_from_blob` or so?

2023-01-13 14:17 UTC, joschkabraun commented on now/app/search_app/app.py
> +                            if k in user_input.index_fields
I believe by construction of `field_names_to_dataclass_fields` the `if` condition shouldn't be necessary

2023-01-13 14:17 UTC, joschkabraun commented on now/run_backend.py
>          user_input.field_names_to_dataclass_fields = {
this attribute will be set by `create_dataclass`

2023-01-13 14:17 UTC, joschkabraun commented on now/run_backend.py
> +    data_class = create_dataclass(user_input)
let's move `create_dataclass` into `load_data` as `data_class` isn't actally used in `app.setup`

2023-01-13 14:17 UTC, joschkabraun commented on tests/unit/data_loading/test_data_loading.py
> -def test_da_custom_ds(da: DocumentArray):
why was this test removed?

2023-01-13 14:17 UTC, joschkabraun commented on now/utils.py
> +) -> Document:
let's add the documentation back of this function

2023-01-13 14:17 UTC, joschkabraun commented on now/utils.py
> +                    data_class_kwargs[field_name_data_class] = field_value.content
The dictionary `field_dict` is now of type `Dict[str,Union[Document,ModalityModel]]` we should make this more clear. In this case `field_value.content or field_value.uri` should suffice.

2023-01-23 09:00 UTC, joschkabraun requested changes
Great solution! Some comments

2023-01-23 09:00 UTC, joschkabraun commented on now/utils.py
> +
this should be in `constants` / I believe is already present

2023-01-23 09:00 UTC, joschkabraun commented on requirements.txt
> +filetype
let's fix `filetype` as well

2023-01-23 16:37 UTC, joschkabraun commented on now/app/search_app/app.py
> @@ -51,7 +51,7 @@
So it will be fixed, with the other PR?

2023-01-23 16:39 UTC, IyadhKhalfallah commented on now/app/search_app/app.py
> @@ -51,7 +51,7 @@
The other PR is aiming to remove the dependency of filter fields from `create_dataclass`. I think it should be fixed by then (this PR #930 )

2023-01-23 16:41 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +            d._metadata['multi_modal_schema'][k]['position'] = float(i)
Isn't the type `int`?

2023-01-23 16:41 UTC, joschkabraun commented on now/deployment/deployment.py
> ~
Isn't `gateway` actually accurate?

2023-01-23 16:44 UTC, joschkabraun commented on now/deployment/deployment.py
> -        flows.append({'id': flow['id'], 'name': flow['status']['endpoints']['gateway']})
Isn't `gateway` actually accurate?

2023-01-23 17:10 UTC, jupyterjazz reviewed
Nice! 
left some comments
can you also add a unit test?

2023-01-23 17:10 UTC, jupyterjazz commented on now/data_loading/data_loading.py
> +            d._metadata['multi_modal_schema'][k]['position'] = float(i)
I think we can do both in one iteration.
Also, instead of `k` can you name it something else? `field` for example

2023-01-23 17:10 UTC, jupyterjazz commented on now/data_loading/data_loading.py
> +        d.chunks = DocumentArray(temp_da)
I think this should also work?
```suggestion
        d.chunks = [getattr(d, field) for field in user_input.index_fields]
```

2023-01-24 08:17 UTC, IyadhKhalfallah commented on now/data_loading/data_loading.py
> +            d._metadata['multi_modal_schema'][k]['position'] = float(i)
@joschkabraun This is actually of type float according to the existing format

2023-01-24 08:19 UTC, IyadhKhalfallah commented on now/deployment/deployment.py
> -        flows.append({'id': flow['id'], 'name': flow['status']['endpoints']['gateway']})
This should actually depend on the executor name. It was failing and I checked it with @makram93 , this was the fix. @makram93 maybe you have more to add here?

2023-01-24 08:20 UTC, IyadhKhalfallah commented on now/data_loading/data_loading.py
> +            d._metadata['multi_modal_schema'][k]['position'] = float(i)
I tried to combine these but I was more focused on making this more readable. The logic in it can be confusing, what do you think?

2023-01-24 08:26 UTC, joschkabraun commented on now/deployment/deployment.py
> -        flows.append({'id': flow['id'], 'name': flow['status']['endpoints']['gateway']})
Okay!

2023-01-24 08:29 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +            d._metadata['multi_modal_schema'][k]['position'] = float(i)
Where does it say that? Because executing this snippet, gives me that the type is `int`
```python
from docarray import dataclass, Document

from docarray.typing import Text


@dataclass
class MMDoc:
    title: Text
    desc: Text


doc0 = Document(MMDoc(title='title0', desc='desc0'))
print(type(doc0._metadata['multi_modal_schema']['title']['position']))
```

2023-01-24 08:35 UTC, IyadhKhalfallah commented on now/data_loading/data_loading.py
> +            d._metadata['multi_modal_schema'][k]['position'] = float(i)
@joschkabraun that's a bit confusing! The screenshot below shows the output while debugging. Your approach of checking this seems more correct though, but I'm not sure what's the cause of this
<img width="1025" alt="Screenshot 2023-01-24 at 09 33 27" src="https://user-images.githubusercontent.com/35614094/214245431-90587130-54bd-47dc-bf55-1a8bc457ddf1.png">

2023-01-24 09:43 UTC, joschkabraun approved these changes
Great work! :rocket:

2023-01-24 09:45 UTC, jupyterjazz approved these changes
LGTM!

2023-01-24 09:48 UTC, merged