fix: bug docarray pull
jina-ai/now pull request #896
Opened 2023-01-09 13:20 UTC by azayz

---

- [ ] This PR references an open issue
- [ ] Test added
- [ ] Documentation adjusted

2023-01-09 16:05 UTC, florian-hoenicke requested changes

2023-01-09 16:05 UTC, florian-hoenicke commented on now/utils.py
> +    user_input.user_name = response['data']['name']
we could change it to admin_name

2023-01-09 16:43 UTC, jupyterjazz approved these changes
LGTM!

let's have 'team-now' as a constant since it's used in so many places

2023-01-09 17:55 UTC, IyadhKhalfallah approved these changes
LGTM

2023-01-10 09:51 UTC, merged

2023-01-10 09:52 UTC, joschkabraun requested changes

2023-01-10 09:52 UTC, joschkabraun commented on now/common/detect_schema.py
> ~        raise ValueError(
Is it possible to use the previously used environment variables?

2023-01-10 09:52 UTC, joschkabraun commented on now/now_dataclasses.py
> +    admin_name: Optional[str] = None
Let's remove this attribute as it can be fetched from hubble SDK.

2023-01-10 09:55 UTC, joschkabraun commented on now/data_loading/data_loading.py
> +            'LOCAL_TESTING' in os.environ
this environment variable

2023-01-10 10:51 UTC, azayz commented on now/now_dataclasses.py
> +    admin_name: Optional[str] = None
I think we should still keep this, because this is the same behaviour as the JWT token, both info come from Hubble SDK.