Feat custom gateway
jina-ai/now pull request #921
Opened 2023-01-12 10:23 UTC by joschkabraun

---

- [ ] This PR references an open issue
- [ ] Test added
- [ ] Documentation adjusted

2023-01-30 17:40 UTC, florian-hoenicke requested changes
Looks great. Just some small things.

2023-01-30 17:40 UTC, florian-hoenicke commented on .github/workflows/ci.yml
> -      - name: Check if deployment has changed
Great to see this part go - only one way of publishing our services

2023-01-30 17:40 UTC, florian-hoenicke commented on now/app/base/app.py
> +        user_input_dict = deepcopy(user_input.__dict__)
This code block can go in a different function - something like: get_user_input_dict

2023-01-30 17:40 UTC, florian-hoenicke commented on now/app/base/app.py
> +            ] = f'jinahub+docker://2m00g87k/{NOW_GATEWAY_VERSION}'
The gateway id 2m00g87k could become a constant similar to the other executors

2023-01-30 17:40 UTC, florian-hoenicke commented on now/app/base/flow.yml
> +    team: now
can we remove this file?

2023-01-30 17:40 UTC, florian-hoenicke commented on now/constants.py
> +CG_BFF_PORT = 8080
to avoid confusions with the naming, I suggest to write it as: custom gateway instead of cg

2023-01-30 17:40 UTC, florian-hoenicke commented on now/executor/autocomplete/Dockerfile
> +FROM jinaai/jina:3.13.2-dev34-py38-standard
I guess the exact jina version is not needed here. The gateway will be built for all jina versions from my understanding

2023-01-30 17:40 UTC, florian-hoenicke commented on now/executor/gateway/.dockerignore
> +venv
we don't have this for the other executors

2023-01-30 17:40 UTC, florian-hoenicke commented on now/executor/gateway/Dockerfile
> +#FROM jinaai/jina:3.13.2-dev34-py38-standard
comment can be removed

2023-01-30 17:40 UTC, florian-hoenicke commented on now/executor/gateway/Dockerfile
> +# RUN pip install "jina==3.13.2.dev34"
comment can be removed

2023-01-30 17:40 UTC, florian-hoenicke commented on now/executor/gateway/Dockerfile
> +COPY nginx.conf /etc/nginx/nginx.conf
is the second one overwriting the first one?

2023-01-30 17:40 UTC, florian-hoenicke commented on now/executor/gateway/now_gateway.py
> +            streamlit_cmd += '-- --secured'
why does it have a double '--'

2023-01-30 17:40 UTC, florian-hoenicke commented on now/executor/gateway/now_gateway.py
> +        application.add_route(
application can be imported locally within the function

2023-01-30 17:40 UTC, florian-hoenicke commented on now/executor/gateway/now_gateway.py
> +        sleep(10)
what happens if you remove this?

2023-01-30 17:40 UTC, florian-hoenicke commented on now/executor/gateway/now_gateway.py
> +    # class DummyEncoder(Executor):
Is this main function needed for local testing?

2023-01-30 17:40 UTC, florian-hoenicke commented on now/executor/gateway/playground/playground.py
> +def deploy_streamlit(secured: bool):
does it mean the secured flag is not coming anymore from the parameters but instead directly from the user_input within the gateway?

2023-01-31 08:44 UTC, florian-hoenicke requested changes

2023-01-31 08:44 UTC, florian-hoenicke commented on tests/executor/preprocessor/test_integration.py
> +    with Flow().config_gateway(
looks like the method Flow().config_gateway() is called multiple time in the flow with the same parameters. What about unifying them to reduce the duplication

2023-02-01 16:20 UTC, joschkabraun commented on now/executor/gateway/Dockerfile
> +COPY nginx.conf /etc/nginx/nginx.conf
no

2023-02-01 16:21 UTC, joschkabraun commented on now/executor/gateway/now_gateway.py
> +            streamlit_cmd += '-- --secured'
To pass arguments to the function streamlit executes. This is streamlit syntax

2023-02-01 16:22 UTC, joschkabraun commented on now/executor/gateway/playground/playground.py
> +def deploy_streamlit(secured: bool):
Yes, we don't need to pass arguments anymore in the URL but directly in the gateway

2023-02-01 20:50 UTC, florian-hoenicke requested changes

2023-02-01 20:50 UTC, florian-hoenicke commented on now/app/base/app.py
> +            # update gateway version
instead of the comment, you could use a function def update_gateway_version

2023-02-01 20:50 UTC, florian-hoenicke commented on now/app/base/app.py
>              # append user_input and api_keys to all executors except the remote executors
can also go to a new function

2023-02-01 20:50 UTC, florian-hoenicke commented on tests/integration/offline_flow/flow.py
> +        # monkeypatch.patch(
commented code can be removed

2023-02-02 10:29 UTC, azayz reviewed
Great work, huge PR

2023-02-02 10:29 UTC, azayz commented on now/executor/gateway/playground/src/search.py
> +    url_host = f"http://localhost:{NOWGATEWAY_BFF_PORT}/api/v1/search-app/{endpoint}"
should this be localhost ?

2023-02-02 10:29 UTC, azayz commented on tests/executor/indexer/test_elastic_in_flow.py
> +        with Flow().config_gateway(
just to know, this is how to add a custom gateway to the flow ?

2023-02-02 10:29 UTC, azayz commented on now/executor/gateway/bff/app/v1/routers/helper.py
> +    async for response in streamer.stream_docs(
is this the new way of making index requests ?

2023-02-02 10:32 UTC, joschkabraun commented on now/executor/gateway/bff/app/v1/routers/helper.py
> +    async for response in streamer.stream_docs(
Yes

2023-02-02 10:32 UTC, joschkabraun commented on tests/executor/indexer/test_elastic_in_flow.py
> +        with Flow().config_gateway(
Yes

2023-02-02 10:32 UTC, joschkabraun commented on now/executor/gateway/playground/src/search.py
> +    url_host = f"http://localhost:{NOWGATEWAY_BFF_PORT}/api/v1/search-app/{endpoint}"
Yes because we send the requests from playground to the same machine

2023-02-02 10:34 UTC, joschkabraun commented on now/data_loading/create_dataclass.py
> +    ImageType, image_setter, image_getter = create_blob_type('Image')
With that we change the default loading of `Image` and `Video` from `uri` -> `tensor` to `uri` -> `blob`. Two reasons:
- blob is much smaller than tensor
- issue with docarray serialization of tensor when using http protocol

2023-02-02 10:34 UTC, joschkabraun commented on now/admin/update_api_keys.py
> +    request_body = get_default_request_body(secured=True)
We don'd need to specify at all actually, hence removed

2023-02-02 10:35 UTC, joschkabraun commented on .github/workflows/cd.yml
> -  update-deployment-if-required:
Yes

2023-02-02 10:35 UTC, joschkabraun commented on .github/workflows/ci.yml
> -          IMAGE_TAG: ${{ env.BFF_PLAYGROUND_TAG }}
We can use the GitHub action for it instead as with all other executors

2023-02-02 10:36 UTC, joschkabraun commented on tests/integration/offline_flow/flow.py
> +        # todo: fix this similar to how 'client_with_mocked_jina_client' is fixed
ah yes, we can remove this. Thank you!

2023-02-02 10:37 UTC, joschkabraun commented on tests/unit/bff/v1/routers/test_search.py
> +    # the mock writes the call args into the response tags, not url isn't written anymore by changes in mock
Yes in the mock we simply put as url the endpoint we called (see comment `the mock writes the call args into the response tags`). But we already test that the mock writes it in something in the next line.

2023-02-02 10:38 UTC, joschkabraun commented on now/admin/search.py
> +    result = Client(host=host).post(
Otherwise we would need to use an `asyncio` loop as `jina_client_post` is now async due to custom gateway.

2023-02-02 13:18 UTC, florian-hoenicke commented on now/executor/gateway/Dockerfile
> +RUN pip install -U git+https://github.com/jina-ai/jina@master
I think so as well. Otherwise, updates on the core will break our deployments.
If it is a feature they have not released, we can also specify a commit hash here

2023-02-02 15:45 UTC, joschkabraun commented on now/executor/gateway/Dockerfile
> +RUN pip install -U git+https://github.com/jina-ai/jina@master
Actually I can remove this line given that the Docker image.

2023-02-02 15:47 UTC, joschkabraun commented on now/executor/gateway/Dockerfile
> +RUN pip install -U git+https://github.com/jina-ai/jina@master
Which will be fixing the jina version

2023-02-02 17:55 UTC, joschkabraun commented
> How can I start the gateway locally? I tried `jina gateway --uses config.yml`
> 
> but then I get an import error: `ImportError: can not import module from /Users/`

If you look at the stack trace, you need to install the `now` package for that option. Otherwise, you can always do
```python
from jina import Flow

from now.executor.gateway import NOWGateway

with Flow().config_gateway(
        uses=NOWGateway,
        protocol=['http'],
        port=[8081],
        env={'JINA_LOG_LEVEL': 'DEBUG'},
        uses_with={'with_playground': False},
    ) as f:
    f.block()
```

2023-02-02 17:56 UTC, joschkabraun commented on .github/workflows/cd.yml
> -  update-deployment-if-required:
yes, if that was a question

2023-02-03 14:42 UTC, jupyterjazz approved these changes
Major PR! :partying_face: :rocket:

2023-02-03 14:42 UTC, jupyterjazz commented on now/executor/gateway/now_gateway.py
> +        # note order is important
why is the order important?

2023-02-03 14:42 UTC, jupyterjazz commented on now/executor/gateway/playground/playground.py
> +            key=f'remove_{modality}_field',
can you put a screenshot for changes on the playground side?

2023-02-03 14:42 UTC, jupyterjazz commented on now/run_backend.py
>          data_class=data_class,
I think `data_class` is not used in setup and we can remove it

2023-02-03 14:42 UTC, jupyterjazz commented on tests/integration/local/conftest.py
> +        self.flow = (
I just remembered your suggestion to use the setup function instead of this, not suggesting to implement it in this pr though, but I'll create a ticket for that

2023-02-03 14:47 UTC, joschkabraun commented on now/executor/gateway/now_gateway.py
> +        # note order is important
I observed that otherwise there can be issues with streamlit not starting. I am not sure why tbh.

2023-02-03 14:48 UTC, joschkabraun commented on now/executor/gateway/playground/playground.py
> +            key=f'remove_{modality}_field',
I put a screenshot in slack: https://jinaai.slack.com/archives/C01E03LN3K7/p1675353328508529?thread_ts=1675191865.501849&cid=C01E03LN3K7
But didn't change any appearance or functionality but only resolved a bug.

2023-02-03 14:56 UTC, joschkabraun commented on tests/integration/local/conftest.py
> +        self.flow = (
Which `setup` function do you mean?

2023-02-03 15:00 UTC, jupyterjazz commented on tests/integration/local/conftest.py
> +        self.flow = (
so instead of creating flows in the `conftest.py`, we can call `app_instance.setup` to make the tests as close to `run_backend.run()` as possible

2023-02-03 15:03 UTC, joschkabraun commented on tests/integration/local/conftest.py
> +        self.flow = (
Ah yes I remember. This is a great suggestion. Let's create ticket.

2023-02-03 15:28 UTC, jupyterjazz commented on tests/integration/local/conftest.py
> +        self.flow = (
https://github.com/jina-ai/now/issues/1022

2023-02-03 17:12 UTC, azayz approved these changes
LGTM

2023-02-05 15:42 UTC, florian-hoenicke requested changes
I made a deployment and encountered the following issue:
1.
a) I opened the playground  `...-http.wolf.jina.ai/playground`
b) Then I reloaded the page (command+ R)
The URL is now reduced to the root and won't display the playground.

2. 
a) I deployed 23 documents of some client data 
b) opened the playground
c) typed in some text and hit the search button

Igot the following error when sending a search request:
```
Exception in BFF, but the root cause can still be in the flow: Traceback (most recent call last):
  File '/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py', line 162, in __call__
    await self.app(scope, receive, _send)
  File '/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py', line 84, in __call__
    await self.app(scope, receive, send)
  File '/usr/local/lib/python3.8/site-packages/starlette/exceptions.py', line 93, in __call__
    raise exc
  File '/usr/local/lib/python3.8/site-packages/starlette/exceptions.py', line 82, in __call__
    await self.app(scope, receive, sender)
  File '/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py', line 21, in __call__
    raise e
  File '/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py', line 18, in __call__
    await self.app(scope, receive, send)
  File '/usr/local/lib/python3.8/site-packages/starlette/routing.py', line 670, in __call__
    await route.handle(scope, receive, send)
  File '/usr/local/lib/python3.8/site-packages/starlette/routing.py', line 266, in handle
    await self.app(scope, receive, send)
  File '/usr/local/lib/python3.8/site-packages/starlette/routing.py', line 65, in app
    response = await func(request)
  File '/usr/local/lib/python3.8/site-packages/fastapi/routing.py', line 251, in app
    response = actual_response_class(response_data, **response_args)
  File '/usr/local/lib/python3.8/site-packages/starlette/responses.py', line 187, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File '/usr/local/lib/python3.8/site-packages/starlette/responses.py', line 49, in __init__
    self.body = self.render(content)
  File '/usr/local/lib/python3.8/site-packages/starlette/responses.py', line 190, in render
    return json.dumps(
  File '/usr/local/lib/python3.8/json/__init__.py', line 234, in dumps
    return cls(
  File '/usr/local/lib/python3.8/json/encoder.py', line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File '/usr/local/lib/python3.8/json/encoder.py', line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant
```

2023-02-06 10:31 UTC, joschkabraun commented
> 2. a) I deployed 23 documents of some client data b) opened the playground c) typed in some text and hit the search button
> 
> Igot the following error when sending a search request:
> 
> ```
> Exception in BFF, but the root cause can still be in the flow: Traceback (most recent call last):
>   File '/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py', line 162, in __call__
>     await self.app(scope, receive, _send)
>   File '/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py', line 84, in __call__
>     await self.app(scope, receive, send)
>   File '/usr/local/lib/python3.8/site-packages/starlette/exceptions.py', line 93, in __call__
>     raise exc
>   File '/usr/local/lib/python3.8/site-packages/starlette/exceptions.py', line 82, in __call__
>     await self.app(scope, receive, sender)
>   File '/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py', line 21, in __call__
>     raise e
>   File '/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py', line 18, in __call__
>     await self.app(scope, receive, send)
>   File '/usr/local/lib/python3.8/site-packages/starlette/routing.py', line 670, in __call__
>     await route.handle(scope, receive, send)
>   File '/usr/local/lib/python3.8/site-packages/starlette/routing.py', line 266, in handle
>     await self.app(scope, receive, send)
>   File '/usr/local/lib/python3.8/site-packages/starlette/routing.py', line 65, in app
>     response = await func(request)
>   File '/usr/local/lib/python3.8/site-packages/fastapi/routing.py', line 251, in app
>     response = actual_response_class(response_data, **response_args)
>   File '/usr/local/lib/python3.8/site-packages/starlette/responses.py', line 187, in __init__
>     super().__init__(content, status_code, headers, media_type, background)
>   File '/usr/local/lib/python3.8/site-packages/starlette/responses.py', line 49, in __init__
>     self.body = self.render(content)
>   File '/usr/local/lib/python3.8/site-packages/starlette/responses.py', line 190, in render
>     return json.dumps(
>   File '/usr/local/lib/python3.8/json/__init__.py', line 234, in dumps
>     return cls(
>   File '/usr/local/lib/python3.8/json/encoder.py', line 199, in encode
>     chunks = self.iterencode(o, _one_shot=True)
>   File '/usr/local/lib/python3.8/json/encoder.py', line 257, in iterencode
>     return _iterencode(o, 0)
> ValueError: Out of range float values are not JSON compliant
> ```
I could reproduce this error on `main`. Created a bug ticket for it: https://github.com/jina-ai/now.private/issues/284

2023-02-06 14:14 UTC, violenil commented on now/app/base/app.py
> +    def get_gateway_sub(self, user_input) -> Dict:
```suggestion
    def get_gateway_stub(self, user_input) -> Dict:
```

2023-02-06 14:14 UTC, violenil commented on now/app/base/app.py
> +        gateway_sub = {
```suggestion
        gateway_stub = {
```

2023-02-06 14:14 UTC, violenil commented on now/app/base/app.py
> +            gateway_sub['jcloud'][
```suggestion
            gateway_stub['jcloud'][
```

2023-02-06 14:15 UTC, violenil commented on now/app/base/app.py
> +        return gateway_sub
```suggestion
        return gateway_stub
```

2023-02-06 14:15 UTC, violenil commented on now/app/base/app.py
> +            'gateway': self.get_gateway_sub(user_input),
```suggestion
            'gateway': self.get_gateway_stub(user_input),
```

2023-02-06 14:30 UTC, violenil reviewed
Looks great! Good work 🚀

2023-02-06 15:38 UTC, joschkabraun commented
> <img alt="image" width="851" src="https://user-images.githubusercontent.com/11627845/216982161-763f8d9b-feff-490b-9e15-36e391f923e1.png">
> 
> The plus buttons are broken. @violenil confirmed they are there on main.
> On your branch the generated HTML looks like this: <img alt="image" width="669" src="https://user-images.githubusercontent.com/11627845/216983001-4073d274-6bae-4ac7-8d6a-842f5bd045f0.png"> But on main it is this: <img alt="A907F80F-DE31-4530-AF88-5B648F32384E" width="515" src="https://user-images.githubusercontent.com/11627845/216983045-7040939d-6387-4f30-abe9-3c45dcde27fd.png">

Good catch, thank you! It is fixed now
<img width="1349" alt="Screenshot 2023-02-06 at 16 38 22" src="https://user-images.githubusercontent.com/47435119/217015521-0b958de4-3874-4158-a760-5e095af61651.png">

2023-02-06 16:14 UTC, florian-hoenicke commented
We could have the following to solve the streamlit issue:
```
        location / {
            proxy_pass http://localhost:8501/;
          }
        location /api {
            proxy_pass http://localhost:8080;
        }

        location /flow {
            proxy_pass http://localhost:8082;
        }
        ```
        What do you think?

2023-02-06 16:16 UTC, joschkabraun commented
> We could have the following to solve the streamlit issue:
> 
> ```
>         location / {
>             proxy_pass http://localhost:8501/;
>           }
>         location /api {
>             proxy_pass http://localhost:8080;
>         }
> 
>         location /flow {
>             proxy_pass http://localhost:8082;
>         }
> ```
> 
>  ```
>     What do you think?
> ```

Yes, we had this also with the previous deployment. Will try it out. Thank you!

2023-02-06 20:03 UTC, merged