fix: support tags for s3 and local folders
jina-ai/now pull request #930
Opened 2023-01-13 08:42 UTC by IyadhKhalfallah

---

- [ ] This PR references an open issue
- [ ] Test added
- [ ] Documentation adjusted

2023-01-13 09:24 UTC, makram93 commented on now/data_loading/create_dataclass.py
> +            dict_fields[key] = str
Why are we setting all the filter field types to `str`? Can they not be float/int types and are these not supported by the indexer?

2023-01-13 09:26 UTC, IyadhKhalfallah commented on now/data_loading/create_dataclass.py
> +            dict_fields[key] = str
@makram93 The only available modality for filtering in `Text`. So, reverting it to python types would be `str`, right?

2023-01-13 09:57 UTC, jupyterjazz commented on now/data_loading/create_dataclass.py
> +            dict_fields[key] = str
We can filter integers/floats too

2023-01-13 10:57 UTC, makram93 commented on now/data_loading/create_dataclass.py
> +            dict_fields[key] = str
@IyadhKhalfallah, That is only applicable when checking dataclass field, i.e. , the dc field that are of type `Text` should be eligible for filter, however any fields in the tags are also eligible, same goes for the content in the json files (in case of s3 source)

2023-01-13 14:04 UTC, joschkabraun requested changes

2023-01-13 14:04 UTC, joschkabraun commented on now/data_loading/create_dataclass.py
> +    update_dict_filter_field_types(all_modalities, user_input.filter_fields)
Instead of patching the filter field types here, why setting them all to string when we create them? (So, solving the issue on a more top-level)

2023-01-17 07:38 UTC, IyadhKhalfallah commented on now/data_loading/create_dataclass.py
> +            dict_fields[key] = str
@makram93 @jupyterjazz I was discussing this with @florian-hoenicke on Friday and we agreed that we can only accept text (string) in filters. Could we discuss this again if you don't agree?

2023-01-20 09:48 UTC, jupyterjazz commented on now/data_loading/data_loading.py
> +        docs.append(doc)
I think we need to flatten these tags, otherwise `value` might be a dict. That's what we do when we present the tags in the cli

Related to this ticket
https://github.com/jina-ai/now/issues/945

I thought we'd fix it after the refactoring but we might as well do it here, wdyt?

2023-01-23 09:06 UTC, joschkabraun commented on now/data_loading/create_dataclass.py
> -    file_mapping_to_dataclass_fields = {
nice!

2023-01-23 09:06 UTC, joschkabraun commented on now/data_loading/create_dataclass.py
> +            file_mapping_to_dataclass_fields[f] = f'filter_{filter_count}'
I think we don't want to have `filter_X` in dataclass anymore, do we?

2023-01-23 09:07 UTC, joschkabraun commented
Can we also make sure that loading tags for customer works fine?

2023-01-23 09:29 UTC, IyadhKhalfallah commented on now/data_loading/create_dataclass.py
> +            file_mapping_to_dataclass_fields[f] = f'filter_{filter_count}'
You're definitely right. I'm pairing with @jupyterjazz about this later to align, since he already worked on removing the `filter_X` logic

2023-01-23 09:30 UTC, IyadhKhalfallah commented
> Can we also make sure that loading tags for customer works fine? That is part of the UAC.

I'll test this with lottiefiles and add a screenshot here after making the changes

2023-01-23 11:04 UTC, violenil commented
Please also add a short description to this PR :)

2023-01-24 16:37 UTC, joschkabraun commented
Let's also make sure that changes from https://github.com/jina-ai/now/pull/880 are reversed.
Let's also check in the end-to-end test that the returned documents contain the right tags from s3.

2023-01-27 11:04 UTC, IyadhKhalfallah commented on now/data_loading/create_dataclass.py
> +            file_mapping_to_dataclass_fields[f] = f'filter_{filter_count}'
For more context, this is to be changed in #974

2023-01-30 09:34 UTC, joschkabraun requested changes

2023-01-30 09:34 UTC, joschkabraun commented on .github/workflows/cd.yml
> +          S3_CUSTOM_MM_DATA_PATH: ${{ secrets.S3_CUSTOM_MM_DATA_PATH }}
what's the difference to `S3_CUSTOM_DATA_PATH`?

2023-01-30 09:34 UTC, joschkabraun commented on now/app/base/app.py
> +                if chunk.tags:
Why is it needed to update `tags` in the flow/preprocessor from the chunks?

2023-01-30 09:34 UTC, joschkabraun commented on tests/integration/remote/assertions.py
> -    for doc in response_json:
Why do we remove this testing?

2023-01-30 09:46 UTC, IyadhKhalfallah commented on .github/workflows/cd.yml
> +          S3_CUSTOM_MM_DATA_PATH: ${{ secrets.S3_CUSTOM_MM_DATA_PATH }}
`S3_CUSTOM_DATA_PATH` is a link to a folder structure that is not nested (doesn't test MM structure). The one I added is a subfolder structure

2023-01-30 09:50 UTC, IyadhKhalfallah commented on now/app/base/app.py
> +                if chunk.tags:
In `maybe_download_from_s3()`, we are adding URIs to the tags in chunks but we are not updating the tags of the document itself. That is why tags are missing in S3 actually. The change here is to get the tags from the chunks and set them back to the document

2023-01-30 09:58 UTC, jupyterjazz requested changes

2023-01-30 09:58 UTC, jupyterjazz commented on now/data_loading/create_dataclass.py
> -    }
since filter field creation happens outside dataclass, it should be removed from here

2023-01-30 09:58 UTC, jupyterjazz commented on tests/integration/remote/test_e2e_s3_bucket.py
> +def test_backend_custom_mm_data(
These two tests are very similar so let's parametrize it

2023-01-30 09:58 UTC, jupyterjazz commented on tests/integration/local/test_end_to_end.py
> -from tests.integration.local.data import artworks_data, elastic_data, pop_lyrics_data
this needs to be imported, that's why ci is failing now

2023-01-30 10:20 UTC, IyadhKhalfallah commented on .pre-commit-config.yaml
> -        exclude: ^now/thirdparty/
Importing the data does not pass with this pre-commit. I'll add that back when required

2023-01-30 10:31 UTC, IyadhKhalfallah commented on tests/integration/local/test_end_to_end.py
> -from tests.integration.local.data import artworks_data, elastic_data, pop_lyrics_data
This was removed automatically in the pre-commit, thanks 🎉

2023-01-30 12:36 UTC, jupyterjazz requested changes
thanks for making the changes!
left some comments

2023-01-30 12:36 UTC, jupyterjazz commented on tests/integration/remote/test_e2e_s3_bucket.py
> +    model_key: str,
we can drop `model_key` argument and assign add it to kwargs like `field + '_model' for field in index_fields`

2023-01-30 12:36 UTC, jupyterjazz commented on now/data_loading/create_dataclass.py
> +            file_mapping_to_dataclass_fields[f] = f'filter_{filter_count}'
there's no need to have filter fields in the `file_mapping_to_dataclass_fields` anymore because we don't create them in the dataclass

2023-01-30 12:36 UTC, jupyterjazz commented on now/app/base/app.py
> +                        dict_tags.update({key: value})
```suggestion
                    dict_tags.update(chunk.tags)
```

2023-01-30 12:36 UTC, jupyterjazz commented on now/app/base/app.py
> +                if chunk.tags:
can't we do this inside `maybe_download_from_s3()`? i.e. only when we actually use that function

2023-01-30 12:37 UTC, IyadhKhalfallah commented on now/data_loading/create_dataclass.py
> +            file_mapping_to_dataclass_fields[f] = f'filter_{filter_count}'
@jupyterjazz I think this is a bigger change and will be addressed in #974

2023-01-30 12:37 UTC, IyadhKhalfallah commented on now/data_loading/create_dataclass.py
> +            file_mapping_to_dataclass_fields[f] = f'filter_{filter_count}'
Removing this will propagate some errors that need to be solved

2023-01-30 13:50 UTC, jupyterjazz commented on now/data_loading/create_dataclass.py
> +            file_mapping_to_dataclass_fields[f] = f'filter_{filter_count}'
Oh ok, I thought that was included in the scope of this ticket. 
Currently I'm working on a bug which is related to removing filter fields from dataclass and I'll do the removal then if that's ok for you

2023-01-30 13:52 UTC, IyadhKhalfallah commented on now/data_loading/create_dataclass.py
> +            file_mapping_to_dataclass_fields[f] = f'filter_{filter_count}'
@jupyterjazz Sure, thanks 🙏

2023-01-30 14:30 UTC, jupyterjazz commented on now/utils.py
> +    d.tags.update(dict_tags)
Thanks for addressing the comments!
One last thing from my side:

I think we can do this
```suggestion
    for chunk in d.chunks:
        d.tags.update(d.chunks.tags)
```
but now that I think about it, what will happen if there is more than one chunk with uris? One of them will be lost, right? We would update the dict first with `{uri: first_uri}`, and then `{uri: second_uri}`, do I understand it correctly?

Also, maybe it's simpler to do this update outside the threads? We could just iterate over the docs after line 285 in `maybe_download_from_s3` and update `d.tags`

2023-01-30 14:50 UTC, florian-hoenicke commented on now/utils.py
> +    d.tags.update(dict_tags)
Why does the chunk have tags?

2023-01-30 15:00 UTC, IyadhKhalfallah commented on now/utils.py
> +    d.tags.update(dict_tags)
@florian-hoenicke I am not sure how we are using that, I kept it just in case. But I think we can remove it from being there

2023-01-30 16:49 UTC, jupyterjazz commented on now/utils.py
> +    d.tags.update(dict_tags)
> Why does the chunk have tags?

We keep the original S3 uri like that. Not sure if it's needed though.
https://github.com/jina-ai/now/blob/0b05a264ca629f9e107e4adba9f3b744000a3b2d/now/utils.py#L224

> what will happen if there is more than one chunk with uris?

Also, looking at the code, if we have more than one chunk with S3 uri one of them will get lost but I don't think that's a big deal rn. 

I think we can just iterate over the `docs` in the end of `maybe_download_from_s3` and update tags:
```python
for d in docs:
    for c in d.chunks:
        d.tags.update(c.tags)
```

2023-01-30 17:00 UTC, jupyterjazz commented on now/utils.py
> +    d.tags.update(dict_tags)
Or maybe we can even do it on this iteration
https://github.com/jina-ai/now/blob/0b05a264ca629f9e107e4adba9f3b744000a3b2d/now/utils.py#L262
so that we don't have to iterate over the docs twice

2023-01-31 09:54 UTC, jupyterjazz commented on now/data_loading/data_loading.py
> +                        dict_tags[el] = value
I think we can replace this part by

```python
with open(file_full_path) as f:
    dict_tags.update(flatten_dict(json.load(f))
```

so we don't need the last for loop

2023-01-31 17:55 UTC, joschkabraun approved these changes
Nice! 🚀

2023-01-31 17:55 UTC, joschkabraun commented
Does customer deployment work with latest changes?

2023-02-01 09:37 UTC, jupyterjazz approved these changes
Great work! 🚀

2023-02-01 09:39 UTC, IyadhKhalfallah commented on now/executor/preprocessor/executor.py
> +            # As _maybe_download_from_s3 moves S3 URI to tags['uri'], need to move it back for post-processor & accurate
Thankfully your PR solves this @jupyterjazz 🤣

2023-02-01 09:53 UTC, IyadhKhalfallah commented
> Does customer deployment work with latest changes?

@joschkabraun I just tested and it works as expected 🚀

2023-02-01 09:53 UTC, merged