feat: expose semantic scores in bff
jina-ai/now pull request #942
Opened 2023-01-17 12:36 UTC by violenil

This PR exposes the `semantic_scores` parameter in the BFF and playground. This parameter is already supported in the indexer, but only receives default values currently. The aim is to allow the user to customize this semantic scoring by adding their own field combinations and weights. 

---

- [x] This PR references an open issue
- [x] Test added
- [ ] Documentation adjusted

2023-01-20 08:52 UTC, azayz requested changes

2023-01-20 08:52 UTC, azayz commented on deployment/playground/playground.py
> +                        on='/get_index_fields',
same code for tags and get_index_fields endpoints can we refactor into one function ?

2023-01-20 08:52 UTC, azayz commented on deployment/playground/playground.py
> +                value=0.5,
default value is 0.5 ? shouldn't it be 1 ?

2023-01-20 08:52 UTC, azayz commented on deployment/playground/playground.py
> +            value=0.5,
same here

2023-01-20 08:52 UTC, azayz commented on now/constants.py
> +TAG_OCR_DETECTOR_TEXT_IN_DOC = '_ocr_detector_text_in_doc'
this was removed. merge issues ?

2023-01-20 09:11 UTC, violenil commented on deployment/playground/playground.py
> +                        on='/get_index_fields',
Yes! Good idea.

2023-01-20 09:11 UTC, violenil commented on deployment/playground/playground.py
> +                value=0.5,
I was pairing with someone (can't remember who) and they suggested 0.5 as default value. Up for discussions though :)

2023-01-20 09:12 UTC, violenil commented on now/constants.py
> +TAG_OCR_DETECTOR_TEXT_IN_DOC = '_ocr_detector_text_in_doc'
ah yes, let me remove. Bad rebase on my part

2023-01-20 09:25 UTC, jupyterjazz commented on deployment/playground/playground.py
> +                value=0.5,
🚀  I'm the someone 🚀 
Because from the user standpoint I should also be able to increase importance of a certain field by actually increasing it and not by decreasing others, it makes more sense to me

2023-01-20 09:35 UTC, violenil commented on deployment/playground/playground.py
> +                value=0.5,
Then I leave it the way it is :)

2023-01-20 09:37 UTC, jupyterjazz approved these changes
LGTM!

2023-01-20 09:37 UTC, jupyterjazz commented on deployment/playground/playground.py
> +        st.session_state.encoder = 'clip'
are we still keeping the encoder option here even though:
1. we should in the end choose the encoder that was used for the index field?
2. we only have 1 encoder now?

2023-01-20 09:37 UTC, jupyterjazz commented on now/executor/indexer/elastic/es_query_building.py
> +) -> List[Tuple]:
would be nice to have an example in the docstring

2023-01-20 11:54 UTC, violenil commented on deployment/playground/playground.py
> +        st.session_state.encoder = 'clip'
Good question! I would like to leave the encoder in the selection box, as a 'placeholder', as we have the model selection ticket already in progress by @azayz .

2023-01-20 11:56 UTC, violenil commented on now/executor/indexer/elastic/es_query_building.py
> +) -> List[Tuple]:
Yes, will amend. I removed `SemanticScore` and simplified to `Tuple` because we can't send a named tuple in the flow. Will provide an example from the tests in the docstring.

2023-01-20 12:40 UTC, jupyterjazz commented on deployment/playground/playground.py
> +        st.session_state.encoder = 'clip'
Hmm, still feels like an unnecessary complexity to me. If there's more than one encoder for an index field, why not encode the query with all of them.. I'm not sure I see the benefit users can get with choosing the specific encoder. But it's ok, we can go with this and maybe revisit the issue later 👍

2023-01-20 13:34 UTC, violenil commented on now/executor/indexer/elastic/es_query_building.py
> +) -> List[Tuple]:
done.

2023-01-20 14:24 UTC, florian-hoenicke requested changes

2023-01-20 14:24 UTC, florian-hoenicke commented on deployment/playground/playground.py
> +        q_field = query_field.selectbox(
a function can be used for the select box since it is duplicate code

2023-01-22 16:44 UTC, violenil commented on deployment/playground/playground.py
> +        q_field = query_field.selectbox(
Could you please make a suggestion? I am just calling the selectbox method multiple times with, with different parameters.

2023-01-23 07:20 UTC, violenil commented
Deployment with customer (lf):

<img width="390" alt="Screenshot 2023-01-23 at 08 07 57" src="https://user-images.githubusercontent.com/55404563/213984786-50adcb0c-3344-45da-8cc8-9b7a309336f7.png">

2023-01-23 08:53 UTC, azayz approved these changes

2023-01-23 08:58 UTC, merged