feat: model choice dialog
jina-ai/now pull request #962
Opened 2023-01-20 14:43 UTC by azayz

---

- [ ] This PR references an open issue
- [ ] Test added
- [ ] Documentation adjusted

2023-01-23 11:17 UTC, violenil approved these changes
Looks great! Yay! Please could you add a short description to the PR and also a screenshot of a working customer deployment?

2023-01-23 11:31 UTC, joschkabraun requested changes
Really nice work! :rocket:
I suggest adding a test for using both `sbert` and `clip` to make sure this also works.

2023-01-23 11:31 UTC, joschkabraun commented on now/now_dataclasses.py
> +    model_choices: Optional[Dict] = {}
let's add the expected types for the keys and values

2023-01-23 11:31 UTC, joschkabraun commented on tests/integration/test_end_to_end.py
> +            ['clip'],
can we have one test where we use `clip` and `sbert` for different fields?

2023-01-23 13:22 UTC, makram93 commented on now/app/search_app/app.py
>                  'dim': dim,
Is this still needed?

2023-01-23 13:48 UTC, azayz commented on tests/integration/test_end_to_end.py
> +            ['clip'],
added

2023-01-23 14:13 UTC, azayz commented on now/now_dataclasses.py
> +    model_choices: Optional[Dict] = {}
added

2023-01-25 14:35 UTC, joschkabraun reviewed
Can we add back an end-to-end test using Sbert and CLIP to make sure this functionality works?

2023-01-25 14:35 UTC, joschkabraun commented on now/executor/indexer/elastic/elastic_indexer.py
> +        print('Docs Maps Values: ', docs_map.values())
please remove print statements

2023-01-25 14:35 UTC, joschkabraun commented on now/executor/indexer/elastic/elastic_indexer.py
> +        print('ES Queries: ', es_queries)
here as well

2023-01-25 14:35 UTC, joschkabraun commented on now/executor/indexer/elastic/elastic_indexer.py
> +        print('Results: ', results)
here as well

2023-01-25 14:35 UTC, joschkabraun commented on now/executor/indexer/elastic/es_query_building.py
> +                continue
isn't that more like an error?

2023-01-25 15:12 UTC, joschkabraun commented
Also, test customer deployment is missing.

2023-01-25 15:53 UTC, azayz commented
<img width="901" alt="Screenshot 2023-01-25 at 16 52 51" src="https://user-images.githubusercontent.com/40893766/214610683-84a5978c-9e9f-4053-9bce-3d2d8c3bd447.png">
<img width="901" alt="Screenshot 2023-01-25 at 16 51 55" src="https://user-images.githubusercontent.com/40893766/214610689-6e930bed-c90f-4531-a1a4-ee4df345964f.png">

2023-01-25 15:54 UTC, azayz commented
<img width="901" alt="Screenshot 2023-01-25 at 16 54 12" src="https://user-images.githubusercontent.com/40893766/214611049-a5431802-f4f6-4987-a69a-181dc3aee79a.png">

2023-01-25 16:09 UTC, azayz commented on now/executor/indexer/elastic/es_query_building.py
> +                continue
yes this is a wacky way to fix query modalities to multiple models routing otherwise we would have many empty combinations for example this happened when searching using an image only but the query_image_sbert embedding was empty, I ll address this in a separate ticket

2023-01-25 16:21 UTC, makram93 requested changes
LGTM! A minor suggestion

2023-01-25 16:33 UTC, joschkabraun approved these changes
Small comment, otherwise LGTM! 🚀

2023-01-25 16:33 UTC, joschkabraun commented on now/constants.py
> +MODALITY_TO_MODELS = {
it's only used in `dialog` right? let's use it only there then

2023-01-25 16:33 UTC, joschkabraun commented on now/executor/indexer/elastic/es_query_building.py
> +                continue
Ok! Let's create a ticket and link it here to have the reference.

2023-01-25 16:50 UTC, makram93 approved these changes

2023-01-26 09:00 UTC, merged

2023-01-26 09:54 UTC, azayz commented on now/executor/indexer/elastic/es_query_building.py
> +                continue
https://github.com/jina-ai/now/issues/979

2023-01-26 09:54 UTC, azayz commented on now/constants.py
> +MODALITY_TO_MODELS = {
I think it's best to keep all constants on one place