feat: activate serverless in preprocessor
jina-ai/now pull request #966
Opened 2023-01-23 11:13 UTC by IyadhKhalfallah

---

- [ ] This PR references an open issue
- [ ] Test added
- [ ] Documentation adjusted

2023-01-23 16:38 UTC, makram93 approved these changes
LGTM! 🚀 

Will this serverless automatically scale up?

2023-01-23 16:50 UTC, joschkabraun requested changes

2023-01-23 16:50 UTC, joschkabraun commented on now/app/search_app/app.py
> ~        return DemoDatasetNames.DEEP_FASHION, DemoDatasetNames.BIRD_SPECIES
we can actually remove `SERVERLESS_EXECUTOR_PREFIX` and the `EXECUTOR_PREFIX` constant as it's simply given by the jina framework. The usage of the latter in `now/testing` isn't relevant anymore as we don't use `NOW_TESTING` anymore since this PR: https://github.com/jina-ai/now/pull/954

2023-01-23 16:50 UTC, joschkabraun commented on now/app/search_app/app.py
> ~            and 'NOW_EXAMPLES' not in os.environ
let's not use on-demand capacity

2023-01-23 16:50 UTC, joschkabraun commented on now/app/search_app/app.py
> +            'uses': f'{SERVERLESS_EXECUTOR_PREFIX}{name_to_id_map.get("NOWPreprocessor")}/{NOW_PREPROCESSOR_VERSION}',
we can actually remove SERVERLESS_EXECUTOR_PREFIX and the EXECUTOR_PREFIX constant as it's simply given by the jina framework. The usage of the latter in now/testing isn't relevant anymore as we don't use NOW_TESTING anymore since this PR: https://github.com/jina-ai/now/pull/954

2023-01-23 16:50 UTC, joschkabraun commented on now/app/search_app/app.py
>                      'capacity': 'on-demand',
let's remove on-demand capacity

2023-01-23 16:50 UTC, joschkabraun commented on now/deployment/deployment.py
> +        executor_name = list(flow['status']['endpoints'].keys())[0]
How is it different now?

2023-01-24 08:39 UTC, IyadhKhalfallah commented on now/app/search_app/app.py
> +            'uses': f'{SERVERLESS_EXECUTOR_PREFIX}{name_to_id_map.get("NOWPreprocessor")}/{NOW_PREPROCESSOR_VERSION}',
@joschkabraun Could you please clarify this more? I'm not sure where to find these constants in the jina framework

2023-01-24 08:41 UTC, IyadhKhalfallah commented on now/deployment/deployment.py
> +        executor_name = list(flow['status']['endpoints'].keys())[0]
This test was failing because the `'endpoints'` key doesn't always contain `'gateway'`. In this case, we would take the executer attributed to that key, which is the `executor_name` variable I introduced

2023-01-24 09:44 UTC, joschkabraun commented on now/deployment/deployment.py
> +        executor_name = list(flow['status']['endpoints'].keys())[0]
Okay, good to know!

2023-01-24 09:45 UTC, joschkabraun approved these changes
Great work! :rocket:

2023-01-25 16:09 UTC, IyadhKhalfallah commented
Proof with demo dataset (best-artworks) deployment:
![Screenshot 2023-01-25 at 16 55 07](https://user-images.githubusercontent.com/35614094/214614856-abc69d3a-f288-4865-a276-670591c988b7.png)

2023-01-26 12:46 UTC, merged