test: add local folder e2e tests
jina-ai/now pull request #986
Opened 2023-01-27 13:28 UTC by jupyterjazz

Closes #985 

Adding local and remote e2e tests for local folder

---

- [x] This PR references an open issue
- [x] Added a test
- [ ] Updated the documentation
- [ ] Added a screenshot of a successful customer deployment

2023-01-30 14:01 UTC, azayz reviewed
LGTM after comments, thanks for adding another test and increasing robustness

2023-01-30 14:53 UTC, jupyterjazz commented on tests/unit/data_loading/test_data_loading.py
> +    assert len(loaded_da) == 10
it has 10 subfolders now

2023-01-30 15:01 UTC, jupyterjazz commented on tests/integration/local/test_end_to_end.py
> +    assert len(response.json()) == min(10, len(docs))
The code above is the same as 
```python
if len(docs) < 10:
    assert len(response.json()) == len(docs)
else:
    assert len(response.json()) == 10
```
So the values are known beforehand, and the test is deterministic as well. 

But it's not needed anymore, so I already removed it

2023-01-30 15:17 UTC, jupyterjazz commented on tests/integration/local/test_end_to_end.py
> +from tests.integration.local.data import (
it's confusing indeed, i'll move it inside the conftest then

2023-01-31 09:50 UTC, azayz reviewed
LGTM after final comment

2023-01-31 09:50 UTC, azayz commented on tests/integration/local/conftest.py
> +class SimpleDoc:
I have already created a fixture for this to avoid redundancy, maybe you can use it https://github.com/jina-ai/now/pull/981/files#diff-e52e4ddd58b7ef887ab03c04116e676f6280b824ab7469d5d3080e5cba4f2128R25

2023-01-31 13:54 UTC, florian-hoenicke requested changes
Putting more binary files lets the git history grow and will over time slow down our work.
Alternative approach:
We use the data from the bucket and just download them before we run the test with local data

2023-01-31 15:46 UTC, closed without merging