fix: semantic scores
jina-ai/now pull request #989
Opened 2023-01-27 16:03 UTC by violenil

Playground is failing when trying to search using custom semantic scores.

---

- [x] This PR references an open issue
- [ ] Added a test
- [ ] Updated the documentation
- [ ] Added a screenshot of a successful customer deployment

2023-01-31 15:05 UTC, azayz reviewed
Great Job

2023-01-31 15:05 UTC, azayz commented on deployment/playground/playground.py
> +            key='encoder_' + str(i),
what's i here ? can we rename to something better ?

2023-01-31 15:05 UTC, azayz commented on now/executor/indexer/elastic/elastic_indexer.py
> +    @secure_request(on='/get_encoder_to_fields', level=SecurityLevel.USER)
this is the previous endpoint in preprocessor right ? get_index_fields but with encoder aswell, my question is where should this endpoint be in elastic indexer or preprocessor ?

2023-01-31 19:37 UTC, violenil commented on deployment/bff/app/v1/models/search.py
> +        description='List of lists where each nested list contains a query_field, index_field, encoder_name and weight.'
we cannot pass tuples in a flow

2023-02-01 07:11 UTC, violenil commented on deployment/playground/playground.py
> +            key='encoder_' + str(i),
`i` is really just iterating over the number of semantic scores the user has added using the `Add semantic score` button

2023-02-01 07:16 UTC, violenil commented on now/executor/indexer/elastic/elastic_indexer.py
> +    @secure_request(on='/get_encoder_to_fields', level=SecurityLevel.USER)
I moved it to the indexer because the indexer already holds the `encoder_to_fields` (and `document_mappings`) which this endpoint takes advantage of. I don't think it matters too much which executor gets this endpoint, but it was more convenient for me this way. Let me know if you disagree.

2023-02-01 08:33 UTC, joschkabraun commented on deployment/bff/app/v1/models/search.py
> +        description='List of lists where each nested list contains a query_field, index_field, encoder_name and weight.'
But this is the search request model so what we put into the bff

2023-02-01 08:39 UTC, joschkabraun reviewed
Small comment

2023-02-01 08:39 UTC, joschkabraun commented on deployment/playground/playground.py
> +    if q_field.startswith('image'):
Can we use the `MODALITY_TO_MODELS` constant for that?

2023-02-01 11:26 UTC, makram93 requested changes

2023-02-01 11:26 UTC, makram93 commented on deployment/playground/playground.py
> +                    endpoint='/get_encoder_to_fields',
Can we expose this endpoint in the bff as well so that the FE can also consume it for cloud apps? They do not use Jina Client, hence they won't be able to get this `encoder_to_fields` for semantic scores.

2023-02-01 16:08 UTC, violenil commented on deployment/playground/playground.py
> +                    endpoint='/get_encoder_to_fields',
after some more discussion we decided to move this to another PR, exposing the `/get_index_fields` endpoint in the BFF. Similarly, the `/tags` endpoint should also be exposed in the BFF, so the FE can also consume it. I will create a ticket for this.

2023-02-01 17:45 UTC, violenil commented on deployment/playground/playground.py
> +    if q_field.startswith('image'):
Its not possible to import from `now.constants` currently, since we don't have `now` as dependency for playground/bff

2023-02-02 08:03 UTC, violenil commented on deployment/bff/app/v1/models/search.py
> +        description='List of lists where each nested list contains a query_field, index_field, encoder_name and weight.'
Done. Semantic scores are now tuples :)

2023-02-02 08:07 UTC, violenil commented on deployment/playground/playground.py
> +                    endpoint='/get_encoder_to_fields',
Created ticket #1008

2023-02-02 10:33 UTC, azayz approved these changes
LGTM

2023-02-02 10:34 UTC, azayz commented
it would be great to see if modifying the semantic scores shows effect on results

2023-02-02 10:53 UTC, joschkabraun commented on deployment/bff/app/v1/routers/search.py
> +    if data.semantic_scores:
To simplify this, let's set `default=[]` in the `SearchRequestModel` definition

2023-02-02 10:53 UTC, joschkabraun commented on deployment/playground/playground.py
> +    if q_field.startswith('image'):
It is dependency for BFF, we can simply add it to the playground.

2023-02-02 10:53 UTC, joschkabraun commented on deployment/playground/playground.py
>                  'Select query field for bm25 scoring',
Can we apply `bm25` to multiple fields independently?

2023-02-02 16:42 UTC, violenil commented on deployment/playground/playground.py
>                  'Select query field for bm25 scoring',
Yes, you can add bm25 on different query fields (you need to select which query field should be considered for the bm25 calculation). As for the documents, we currently just concatenate all index fields of modality `Text` and use this for bm25 score calculation, ie. you cannot select the index field on the document which should be used for bm25.

2023-02-03 09:37 UTC, jupyterjazz approved these changes
LGTM!

2023-02-03 09:37 UTC, jupyterjazz commented on now/executor/indexer/elastic/elastic_indexer.py
> +        print(
you have some prints left in this fn

2023-02-03 09:37 UTC, jupyterjazz commented on deployment/playground/playground.py
> +                )
maybe we can avoid fetching the data twice and change `get_info_from_endpoint` so that if `info` is None it returns the whole tags

2023-02-06 11:52 UTC, violenil commented on deployment/playground/playground.py
> +                )
done

2023-02-06 11:52 UTC, violenil commented on now/executor/indexer/elastic/elastic_indexer.py
> +        print(
thanks!

2023-02-06 12:28 UTC, violenil commented
> it would be great to see if modifying the semantic scores shows effect on results

@azayz for your request, here's the birds demo data deployment, where I search with two different semantic score definitions:

1) searching with the text query 'cat' only comparing on the `label` index field using SBert encoder.
<img width="658" alt="Screenshot 2023-02-06 at 13 25 02" src="https://user-images.githubusercontent.com/55404563/216971218-df67a144-542f-4801-9500-2b6afbe18845.png">

2) searching with text query 'cat' comparing on both `label` (using SBert) and `image` (using CLIP) fields.
<img width="658" alt="Screenshot 2023-02-06 at 13 25 25" src="https://user-images.githubusercontent.com/55404563/216971406-13304438-1e42-4e05-a1b8-d048ebf6367c.png">

There are definitely differences. Only indexed 50 documents, and perhaps my query is not very suitable, but at least you can see there are changes when semantic scores are customized and adjusted.

2023-02-06 14:44 UTC, makram93 approved these changes

2023-02-06 14:50 UTC, merged